
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.Xe||(g.Xe=0);g.Xe++;
(function(a){function b(p,r,q){var u=new XMLHttpRequest;u.open("GET",p,!0);u.responseType="arraybuffer";u.onprogress=function(w){var m=r;w.total&&(m=w.total);if(w.loaded){u.oe?g.Ee[p].loaded=w.loaded:(u.oe=!0,g.Ee||(g.Ee={}),g.Ee[p]={loaded:w.loaded,total:m});var v=m=w=0,x;for(x in g.Ee){var C=g.Ee[x];w+=C.total;m+=C.loaded;v++}w=Math.ceil(w*g.Xe/v);g.setStatus&&g.setStatus("Downloading data... ("+m+"/"+w+")")}else!g.Ee&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
p);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)q(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(p){console.error("package error:",p)}function d(){function p(w,m,v){this.start=w;this.Ke=m;this.audio=v}function r(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);p.prototype.zf=w;w=a.files;for(var m=0;m<
w.length;++m)p.prototype.oe[w[m].filename].onload();g.removeRunDependency("datafile_index.data")}g.FS_createPath("/","shaders",!0,!0);p.prototype={oe:{},open:function(w,m){this.name=m;this.oe[m]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.vf(this.zf.subarray(this.start,this.Ke))},vf:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.oe[this.name]=null}};for(var q=a.files,u=0;u<q.length;++u)(new p(q[u].start,
q[u].end,q[u].audio)).open("GET",q[u].filename);g.addRunDependency("datafile_index.data");g.Cf||(g.Cf={});g.Cf["index.data"]={tg:!1};n?(r(n),n=null):h=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,h=null,n=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;n||b(e,f,function(p){h?(h(p),h=null):n=p},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/shaders/grid.frag",
start:0,end:1377,audio:0},{filename:"/shaders/post.frag",start:1377,end:2718,audio:0},{filename:"/shaders/tiles.frag",start:2718,end:3247,audio:0},{filename:"/shaders/post.vert",start:3247,end:3327,audio:0},{filename:"/shaders/texture.frag",start:3327,end:5110,audio:0},{filename:"/shaders/texture.vert",start:5110,end:5190,audio:0},{filename:"/shaders/grid.vert",start:5190,end:5270,audio:0},{filename:"/shaders/tiles.vert",start:5270,end:5350,audio:0},{filename:"/shaders/post2.frag",start:5350,end:7998,
audio:0}],remote_package_size:7998,package_uuid:"a8bd8fc9-7c95-4c43-9c85-84dd23693e76"});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca="./this.program";function da(a,b){throw b;}var ea=!1,fa=!1,ha=!1,ia=!1;ea="object"===typeof window;fa="function"===typeof importScripts;ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ia=!ea&&!ha&&!fa;var l="",ja,ka,la,ma,oa,pa;
if(ha)l=fa?require("path").dirname(l)+"/":__dirname+"/",ja=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return oa.readFileSync(a,b?null:"utf8")},la=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof qa))throw a;}),process.on("unhandledRejection",
t),da=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ia)"undefined"!=typeof read&&(ja=function(a){return read(a)}),la=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?
printErr:print);else if(ea||fa)fa?l=self.location.href:"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.lastIndexOf("/")+1):"",ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);
d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},ma=function(a){document.title=a};var ra=g.print||console.log.bind(console),k=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);function sa(a){ta||(ta={});ta[a]||(ta[a]=1,k(a))}var ta,ua;g.wasmBinary&&(ua=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;
"object"!==typeof WebAssembly&&t("no native wasm support detected");var va,wa=!1,xa;function assert(a,b){a||t("Assertion failed: "+b)}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?za(z,a,b):""}
function Aa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function A(a,b,c){return Aa(a,z,b,c)}
function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ca(a){var b=Ba(a)+1,c=B(b);c&&Aa(a,D,c,b);return c}var Da,D,z,Ea,Fa,E,Ga,F,Ha;
function Ia(){var a=va.buffer;Da=a;g.HEAP8=D=new Int8Array(a);g.HEAP16=Ea=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=z=new Uint8Array(a);g.HEAPU16=Fa=new Uint16Array(a);g.HEAPU32=Ga=new Uint32Array(a);g.HEAPF32=F=new Float32Array(a);g.HEAPF64=Ha=new Float64Array(a)}var G,Ja=[],Ka=[],La=[],Ma=[],Na=[];function Oa(){var a=g.preRun.shift();Ja.unshift(a)}var Pa=0,Qa=null,Ra=null;function Sa(){Pa++;g.monitorRunDependencies&&g.monitorRunDependencies(Pa)}
function Ta(){Pa--;g.monitorRunDependencies&&g.monitorRunDependencies(Pa);if(0==Pa&&(null!==Qa&&(clearInterval(Qa),Qa=null),Ra)){var a=Ra;Ra=null;a()}}g.preloadedImages={};g.preloadedAudios={};function t(a){if(g.onAbort)g.onAbort(a);k(a);wa=!0;xa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ua(a){var b=Va;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}
function Wa(){return Ua("data:application/octet-stream;base64,")}var Va="index.wasm";if(!Wa()){var Xa=Va;Va=g.locateFile?g.locateFile(Xa,l):l+Xa}function Ya(){var a=Va;try{if(a==Va&&ua)return new Uint8Array(ua);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}
function Za(){if(!ua&&(ea||fa)){if("function"===typeof fetch&&!Ua("file://"))return fetch(Va,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Va+"'";return a.arrayBuffer()}).catch(function(){return Ya()});if(ka)return new Promise(function(a,b){ka(Va,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ya()})}
var $a,ab,bb={57228:function(){return window.screen.width},57279:function(){return window.screen.height},57333:function(){return 0},57347:function(a,b,c){g.SDL2||(g.SDL2={});var d=g.SDL2;d.Gf!==g.canvas&&(d.ve=g.createContext(g.canvas,!1,!0),d.Gf=g.canvas);if(d.w!==a||d.Of!==b||d.Qf!==d.ve)d.image=d.ve.createImageData(a,b),d.w=a,d.Of=b,d.Qf=d.ve;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=E[b];a[e]=f&255;a[e+1]=f>>
8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.rg!==a&&(d.Hf=new Int32Array(a.buffer),d.If=new Uint8Array(a.buffer)),a=d.Hf,c=a.length,a.set(E.subarray(b,b+c)),a=d.If,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ve.putImageData(d.image,0,0);return 0},58802:function(a){g.canvas&&(g.canvas.style.cursor=y(a));return 0},58895:function(){g.canvas&&
(g.canvas.style.cursor="none")},58964:function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var n=0,p;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(p=b.length;n<p;){var r=E[e];b[n]=r&255;b[n+1]=r>>8&255;b[n+2]=r>>16&255;b[n+3]=r>>24&255;e++;n+=4}else b=new Int32Array(b.buffer),p=b.length,b.set(E.subarray(e,e+p));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":
"url("+f.toDataURL()+") "+c+" "+d+", auto";d=B(c.length+1);A(c,d,c.length+1);return d},59953:function(a){"undefined"!==typeof ma&&ma(y(a));return 0},60048:function(){return window.innerWidth},60078:function(){return window.innerHeight},60109:function(){return screen.width},60134:function(){return screen.height}};function cb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Nf;"number"===typeof c?void 0===b.Pe?G.get(c)():G.get(c)(b.Pe):c(void 0===b.Pe?null:b.Pe)}}}
function db(a){this.He=a-16;this.fg=function(b){E[this.He+8>>2]=b};this.cg=function(b){E[this.He+0>>2]=b};this.dg=function(){E[this.He+4>>2]=0};this.bg=function(){D[this.He+12>>0]=0};this.eg=function(){D[this.He+13>>0]=0};this.Rf=function(b,c){this.fg(b);this.cg(c);this.dg();this.bg();this.eg()}}var eb=0;function fb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function gb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ib(a){if("/"===a)return"/";a=gb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function jb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){t("randomDevice")}}
function kb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var lb=[];function mb(a,b){lb[a]={input:[],output:[],Ge:b};nb(a,ob)}
var ob={open:function(a){var b=lb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ge.flush(a.tty)},flush:function(a){a.tty.Ge.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ge.qf)throw new H(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Ge.qf(a.tty)}catch(n){throw new H(29);}if(void 0===h&&0===e)throw new H(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ge.bf)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.Ge.bf(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},qb={qf:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.oe?Buffer.oe(256):new Buffer(256),d=0;try{d=oa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=pb(b,!0)}return a.input.shift()},bf:function(a,b){null===b||10===b?(ra(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ra(za(a.output,0)),a.output=[])}},rb={bf:function(a,b){null===b||10===b?(k(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(za(a.output,0)),a.output=[])}},I={ye:null,ze:function(){return I.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.ye||(I.ye={dir:{node:{Be:I.le.Be,re:I.le.re,lookup:I.le.lookup,Re:I.le.Re,rename:I.le.rename,unlink:I.le.unlink,rmdir:I.le.rmdir,readdir:I.le.readdir,symlink:I.le.symlink},stream:{Ce:I.me.Ce}},file:{node:{Be:I.le.Be,re:I.le.re},stream:{Ce:I.me.Ce,read:I.me.read,write:I.me.write,gf:I.me.gf,wf:I.me.wf,yf:I.me.yf}},link:{node:{Be:I.le.Be,re:I.le.re,readlink:I.le.readlink},stream:{}},lf:{node:{Be:I.le.Be,
re:I.le.re},stream:sb}});c=tb(a,b,c,d);16384===(c.mode&61440)?(c.le=I.ye.dir.node,c.me=I.ye.dir.stream,c.ke={}):32768===(c.mode&61440)?(c.le=I.ye.file.node,c.me=I.ye.file.stream,c.ne=0,c.ke=null):40960===(c.mode&61440)?(c.le=I.ye.link.node,c.me=I.ye.link.stream):8192===(c.mode&61440)&&(c.le=I.ye.lf.node,c.me=I.ye.lf.stream);c.timestamp=Date.now();a&&(a.ke[b]=c,a.timestamp=c.timestamp);return c},ug:function(a){return a.ke?a.ke.subarray?a.ke.subarray(0,a.ne):new Uint8Array(a.ke):new Uint8Array(0)},
mf:function(a,b){var c=a.ke?a.ke.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ke,a.ke=new Uint8Array(b),0<a.ne&&a.ke.set(c.subarray(0,a.ne),0))},$f:function(a,b){if(a.ne!=b)if(0==b)a.ke=null,a.ne=0;else{var c=a.ke;a.ke=new Uint8Array(b);c&&a.ke.set(c.subarray(0,Math.min(b,a.ne)));a.ne=b}},le:{Be:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.ne:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ff=4096;b.blocks=Math.ceil(b.size/b.Ff);return b},re:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.$f(a,b.size)},lookup:function(){throw ub[44];},Re:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=vb(b,
c)}catch(f){}if(d)for(var e in d.ke)throw new H(55);}delete a.parent.ke[a.name];a.parent.timestamp=Date.now();a.name=c;b.ke[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.ke[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=vb(a,b),d;for(d in c.ke)throw new H(55);delete a.ke[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.ke)a.ke.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},me:{read:function(a,b,c,d,e){var f=a.node.ke;if(e>=a.node.ne)return 0;a=Math.min(a.node.ne-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===D.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ke||a.ke.subarray)){if(f)return a.ke=b.subarray(c,c+d),a.ne=d;if(0===a.ne&&0===e)return a.ke=b.slice(c,c+d),a.ne=
d;if(e+d<=a.ne)return a.ke.set(b.subarray(c,c+d),e),d}I.mf(a,e+d);if(a.ke.subarray&&b.subarray)a.ke.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ke[e+f]=b[c+f];a.ne=Math.max(a.ne,e+d);return d},Ce:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ne);if(0>b)throw new H(28);return b},gf:function(a,b,c){I.mf(a.node,b+c);a.node.ne=Math.max(a.node.ne,b+c)},wf:function(a,b,c,d,e,f){if(0!==b)throw new H(28);if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.ke;if(f&
2||a.buffer!==Da){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=B(f);c<f;)D[b+c++]=0;c=b;if(!c)throw new H(48);D.set(a,c)}else d=!1,c=a.byteOffset;return{He:c,og:d}},yf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.me.write(a,b,0,d,c,!1);return 0}}},wb=null,xb={},yb=[],zb=1,Ab=null,Bb=!0,Cb={},H=null,ub={};
function Db(a,b){a=kb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={nf:!0,cf:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.cf)throw new H(32);a=fb(a.split("/").filter(function(h){return!!h}),!1);var e=wb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=vb(e,a[d]);c=gb(c+"/"+a[d]);e.Ne&&(!f||f&&b.nf)&&(e=e.Ne.root);if(!f||b.Ye)for(f=0;40960===(e.mode&61440);)if(e=Eb(c),c=kb(hb(c),e),e=Db(c,{cf:b.cf}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function Fb(a){for(var b;;){if(a===a.parent)return a=a.ze.xf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ab.length}function vb(a,b){var c;if(c=(c=Hb(a,"x"))?c:a.le.lookup?0:2)throw new H(c,a);for(c=Ab[Gb(a.id,b)];c;c=c.Fe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.le.lookup(a,b)}
function tb(a,b,c,d){a=new Ib(a,b,c,d);b=Gb(a.parent.id,a.name);a.Fe=Ab[b];return Ab[b]=a}var Jb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Kb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hb(a,b){if(Bb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Lb(a,b){try{return vb(a,b),20}catch(c){}return Hb(a,"wx")}
function Mb(a){var b=4096;for(a=a||0;a<=b;a++)if(!yb[a])return a;throw new H(33);}function Nb(a,b){Ob||(Ob=function(){},Ob.prototype={});var c=new Ob,d;for(d in a)c[d]=a[d];a=c;b=Mb(b);a.fd=b;return yb[b]=a}var sb={open:function(a){a.me=xb[a.node.rdev].me;a.me.open&&a.me.open(a)},Ce:function(){throw new H(70);}};function nb(a,b){xb[a]={me:b}}
function Pb(a,b){var c="/"===b,d=!b;if(c&&wb)throw new H(10);if(!c&&!d){var e=Db(b,{nf:!1});b=e.path;e=e.node;if(e.Ne)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,Ag:{},xf:b,Xf:[]};a=a.ze(b);a.ze=b;b.root=a;c?wb=a:e&&(e.Ne=b,e.ze&&e.ze.Xf.push(b))}function Qb(a,b,c){var d=Db(a,{parent:!0}).node;a=ib(a);if(!a||"."===a||".."===a)throw new H(28);var e=Lb(d,a);if(e)throw new H(e);if(!d.le.Re)throw new H(63);return d.le.Re(d,a,b,c)}function J(a){return Qb(a,16895,0)}
function Rb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Qb(a,b|8192,c)}function Sb(a,b){if(!kb(a))throw new H(44);var c=Db(b,{parent:!0}).node;if(!c)throw new H(44);b=ib(b);var d=Lb(c,b);if(d)throw new H(d);if(!c.le.symlink)throw new H(63);c.le.symlink(c,b,a)}
function Tb(a){var b=Db(a,{parent:!0}).node,c=ib(a),d=vb(b,c);a:{try{var e=vb(b,c)}catch(h){e=h.we;break a}var f=Hb(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new H(e);if(!b.le.unlink)throw new H(63);if(d.Ne)throw new H(10);try{Cb.willDeletePath&&Cb.willDeletePath(a)}catch(h){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.le.unlink(b,c);b=Gb(d.parent.id,d.name);if(Ab[b]===d)Ab[b]=d.Fe;else for(b=Ab[b];b;){if(b.Fe===d){b.Fe=d.Fe;break}b=b.Fe}try{if(Cb.onDeletePath)Cb.onDeletePath(a)}catch(h){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Eb(a){a=Db(a).node;if(!a)throw new H(44);if(!a.le.readlink)throw new H(28);return kb(Fb(a.parent),a.le.readlink(a))}function Ub(a,b){a="string"===typeof a?Db(a,{Ye:!0}).node:a;if(!a.le.re)throw new H(63);a.le.re(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Vb(a,b,c,d){if(""===a)throw new H(44);if("string"===typeof b){var e=Jb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=gb(a);try{f=Db(a,{Ye:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new H(20);}else f=Qb(a,c,0),e=!0;if(!f)throw new H(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new H(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Kb(b)||b&512)?31:Hb(f,Kb(b)):44))throw new H(c);if(b&512){c=f;c="string"===typeof c?Db(c,{Ye:!0}).node:c;if(!c.le.re)throw new H(63);if(16384===(c.mode&61440))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(e=Hb(c,"w"))throw new H(e);c.le.re(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Nb({node:f,path:Fb(f),flags:b,seekable:!0,position:0,me:f.me,lg:[],error:!1},d);d.me.open&&d.me.open(d);!g.logReadFiles||b&1||(Wb||(Wb={}),a in Wb||(Wb[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{Cb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Cb.onOpenFile(a,f))}catch(h){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function Xb(a){if(null===a.fd)throw new H(8);a.Ze&&(a.Ze=null);try{a.me.close&&a.me.close(a)}catch(b){throw b;}finally{yb[a.fd]=null}a.fd=null}
function Yb(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.me.Ce)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.me.Ce(a,b,c);a.lg=[]}
function Zb(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(16384===(a.node.mode&61440))throw new H(31);if(!a.me.write)throw new H(28);a.seekable&&a.flags&1024&&Yb(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H(70);b=a.me.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&Cb.onWriteToFile)Cb.onWriteToFile(a.path)}catch(n){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
n.message)}return b}function $b(){H||(H=function(a,b){this.node=b;this.ag=function(c){this.we=c};this.ag(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){ub[a]=new H(a);ub[a].stack="<generic error, no stack>"}))}var ac;function bc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function cc(a,b){a="string"===typeof a?a:Fb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=gb(a+"/"+c);try{J(d)}catch(e){}a=d}}return d}
function dc(a,b,c,d){a=gb(("string"===typeof a?a:Fb(a))+"/"+b);c=bc(c,d);return Qb(a,(void 0!==c?c:438)&4095|32768,0)}function ec(a,b,c,d,e,f){a=b?gb(("string"===typeof a?a:Fb(a))+"/"+b):a;d=bc(d,e);e=Qb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Ub(e,d|146);a=Vb(e,577);Zb(a,c,0,c.length,0,f);Xb(a);Ub(e,d)}return e}
function K(a,b,c,d){a=gb(("string"===typeof a?a:Fb(a))+"/"+b);b=bc(!!c,!!d);K.tf||(K.tf=64);var e=K.tf++<<8|0;nb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,n,p){for(var r=0,q=0;q<p;q++){try{var u=c()}catch(w){throw new H(29);}if(void 0===u&&0===r)throw new H(6);if(null===u||void 0===u)break;r++;h[n+q]=u}r&&(f.node.timestamp=Date.now());return r},write:function(f,h,n,p){for(var r=0;r<p;r++)try{d(h[n+r])}catch(q){throw new H(29);}p&&(f.node.timestamp=
Date.now());return r}});return Rb(a,b,e)}function fc(a){if(!(a.Vf||a.Wf||a.link||a.ke)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.ke=pb(ja(a.url),!0),a.ne=a.ke.length}catch(b){throw new H(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function hc(a,b,c,d,e){function f(){this.$e=!1;this.oe=[]}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var u=q%this.chunkSize;return this.rf(q/this.chunkSize|0)[u]}};f.prototype.Ke=function(q){this.rf=q};f.prototype.jf=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var u=Number(q.getResponseHeader("Content-length")),w,m=(w=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;q=(w=q.getResponseHeader("Content-Encoding"))&&"gzip"===w;var v=1048576;m||(v=u);var x=this;x.Ke(function(C){var X=C*v,na=(C+1)*v-1;na=Math.min(na,u-1);if("undefined"===typeof x.oe[C]){var pc=x.oe;if(X>na)throw Error("invalid range ("+X+", "+na+") or no bytes requested!");if(na>u-1)throw Error("only "+u+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);u!==v&&L.setRequestHeader("Range","bytes="+X+"-"+na);"undefined"!=typeof Uint8Array&&(L.responseType=
"arraybuffer");L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);if(!(200<=L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);X=void 0!==L.response?new Uint8Array(L.response||[]):pb(L.responseText||"",!0);pc[C]=X}if("undefined"===typeof x.oe[C])throw Error("doXHR failed!");return x.oe[C]});if(q||!u)v=u=1,v=u=this.rf(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ef=
u;this.Df=v;this.$e=!0};if("undefined"!==typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.$e||this.jf();return this.Ef}},chunkSize:{get:function(){this.$e||this.jf();return this.Df}}});var n=void 0}else n=c,h=void 0;var p=dc(a,b,d,e);h?p.ke=h:n&&(p.ke=null,p.url=n);Object.defineProperties(p,{ne:{get:function(){return this.ke.length}}});
var r={};Object.keys(p.me).forEach(function(q){var u=p.me[q];r[q]=function(){fc(p);return u.apply(null,arguments)}});r.read=function(q,u,w,m,v){fc(p);q=q.node.ke;if(v>=q.length)return 0;m=Math.min(q.length-v,m);if(q.slice)for(var x=0;x<m;x++)u[w+x]=q[v+x];else for(x=0;x<m;x++)u[w+x]=q.get(v+x);return m};p.me=r;return p}
function ic(a,b,c,d,e,f,h,n,p,r){function q(m){function v(C){r&&r();n||ec(a,b,C,d,e,p);f&&f();Ta(w)}var x=!1;g.preloadPlugins.forEach(function(C){!x&&C.canHandle(u)&&(C.handle(m,u,v,function(){h&&h();Ta(w)}),x=!0)});x||v(m)}jc();var u=b?kb(gb(a+"/"+b)):a,w="cp "+u;Sa(w);"string"==typeof c?kc(c,function(m){q(m)},h):q(c)}var lc={},Ob,Wb,mc=void 0;function nc(){mc+=4;return E[mc-4>>2]}function oc(a){a=yb[a];if(!a)throw new H(8);return a}var qc;
ha?qc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?qc=dateNow:qc=function(){return performance.now()};
function rc(a,b){sc=a;tc=b;if(uc)if(vc||(vc=!0),0==a)wc=function(){var d=Math.max(0,xc+b-qc())|0;setTimeout(yc,d)};else if(1==a)wc=function(){zc(yc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);fa?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}wc=function(){setImmediate(yc)}}}
function Ac(a,b,c,d,e){function f(){if(h<Bc){if(!noExitRuntime)try{Cc(xa)}catch(n){if(!(n instanceof qa))throw n;}return!1}return!0}assert(!uc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");uc=a;Dc=d;var h=Bc;vc=!1;yc=function(){if(!wa)if(0<Ec.length){var n=Date.now(),p=Ec.shift();p.Nf(p.Pe);if(Fc){var r=Fc,q=0==r%1?r-1:Math.floor(r);Fc=p.qg?q:(8*r+(q+.5))/
9}console.log('main loop blocker "'+p.name+'" took '+(Date.now()-n)+" ms");g.setStatus&&(n=g.statusMessage||"Please wait...",p=Fc,r=Gc.sg,p?p<r?g.setStatus(n+" ("+(r-p)+"/"+r+")"):g.setStatus(n):g.setStatus(""));f()&&setTimeout(yc,0)}else f()&&(Hc=Hc+1|0,1==sc&&1<tc&&0!=Hc%tc?wc():(0==sc&&(xc=qc()),wa||g.preMainLoop&&!1===g.preMainLoop()||(Ic(a),g.postMainLoop&&g.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Zf&&SDL.audio.Zf(),wc())))};e||(b&&0<b?rc(0,1E3/b):rc(1,1),wc());if(c)throw"unwind";
}function Ic(a){try{a()}catch(b){if(!(b instanceof qa)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&k("exception thrown: "+[b,b.stack]),b;}}var vc=!1,wc=null,Bc=0,uc=null,Dc=0,sc=0,tc=0,Hc=0,Ec=[],Gc={},xc,yc,Fc,Jc=!1,Kc=!1,Lc=[];
function jc(){function a(){Kc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Mc){Mc=!0;try{Nc=!0}catch(c){Nc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Oc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Nc?null:console.log("warning: no BlobBuilder");
Pc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Af||"undefined"!==typeof Pc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Af=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Af&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(Nc)try{h=new Blob([c],{type:Qc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Qc(d)}))}catch(r){sa("Blob constructor present but fails: "+
r+"; falling back to blob builder")}h||(h=new Oc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var n=Pc.createObjectURL(h),p=new Image;p.onload=function(){assert(p.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=p.width;r.height=p.height;r.getContext("2d").drawImage(p,0,0);g.preloadedImages[d]=r;Pc.revokeObjectURL(n);e&&e(c)};p.onerror=function(){console.log("Image "+n+" could not be decoded");f&&f()};p.src=n}});g.preloadPlugins.push({canHandle:function(c){return!g.zg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(u){p||(p=!0,g.preloadedAudios[d]=u,e&&e(c))}function n(){p||(p=!0,g.preloadedAudios[d]=new Audio,f&&f())}var p=!1;if(Nc){try{var r=new Blob([c],{type:Qc(d)})}catch(u){return n()}r=Pc.createObjectURL(r);var q=new Audio;q.addEventListener("canplaythrough",function(){h(q)},!1);q.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,m=0,
v=0;v<c.length;v++)for(w=w<<8|c[v],m+=8;6<=m;){var x=w>>m-6&63;m-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==m?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==m&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");q.src="data:audio/x-"+d.substr(-3)+";base64,"+u;h(q)}};q.src=r;Rc(function(){h(q)})}else return n()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!Kc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Sc(a,b,c,d){if(b&&g.ve&&a==g.canvas)return g.ve;var e;if(b){var f={antialias:!1,alpha:!1,uf:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof Tc&&(e=Uc(a,f)))var n=M[e].Ae}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof N,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.ve=n,b&&Vc(e),g.mg=b,Lc.forEach(function(p){p()}),jc());return n}var Wc=!1,Xc=void 0,Yc=void 0;
function Zc(a,b){function c(){Jc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=$c,Xc&&d.requestPointerLock(),Jc=!0,Yc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=Ga[SDL.screen>>2]|8388608),ad(g.canvas),bd()):ad(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Yc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=Ga[SDL.screen>>2]&
-8388609),ad(g.canvas),bd()):ad(d));if(g.onFullScreen)g.onFullScreen(Jc);if(g.onFullscreen)g.onFullscreen(Jc)}Xc=a;Yc=b;"undefined"===typeof Xc&&(Xc=!0);"undefined"===typeof Yc&&(Yc=!1);var d=g.canvas;Wc||(Wc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function $c(){if(!Jc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var cd=0;function zc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===cd)cd=b+1E3/60;else for(;b+2>=cd;)cd+=1E3/60;setTimeout(a,Math.max(cd-b,0))}}function Rc(a){setTimeout(function(){Ic(a)},1E4)}
function Qc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function kc(a,b,c){var d="al "+a;ka(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ta(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Sa(d)}var dd=[];function bd(){var a=g.canvas;dd.forEach(function(b){b(a.width,a.height)})}
function ad(a,b,c){b&&c?(a.ng=b,a.Pf=c):(b=a.ng,c=a.Pf);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Yc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Mc,Nc,Oc,Pc,O=12288,ed=!1,fd=0,gd=0,hd=0,P={alpha:!1,depth:!1,stencil:!1,antialias:!1},id={},jd;function kd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function ld(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function md(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var nd=1,od=[],Q=[],pd=[],qd=[],rd=[],R=[],S=[],sd=[],M=[],T=[],td={},ud={},vd=4;
function U(a){wd||(wd=a)}function xd(a){for(var b=nd++,c=a.length;c<b;c++)a[c]=null;return b}function yd(a,b,c){for(var d="",e=0;e<a;++e){var f=c?E[c+4*e>>2]:-1;d+=y(E[b+4*e>>2],0>f?void 0:f)}return d}function Uc(a,b){a.pf||(a.pf=a.getContext,a.getContext=function(d,e){e=a.pf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?zd(c,b):0}
function zd(a,b){var c=xd(M),d={vg:c,attributes:b,version:b.uf,Ae:a};a.canvas&&(a.canvas.Je=d);M[c]=d;("undefined"===typeof b.Kf||b.Kf)&&Ad(d);return c}function Vc(a){Bd=M[a];g.ve=N=Bd&&Bd.Ae}function Ad(a){a||(a=Bd);if(!a.Sf){a.Sf=!0;var b=a.Ae;kd(b);ld(b);md(b);b.se=b.getExtension("EXT_disjoint_timer_query");b.yg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}
function Cd(a){var b=Q[a];a=td[a]={ff:{},af:0,Le:-1,Me:-1};for(var c=a.ff,d=N.getProgramParameter(b,35718),e=0;e<d;++e){var f=N.getActiveUniform(b,e),h=f.name;a.af=Math.max(a.af,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var n=N.getUniformLocation(b,h);if(n){var p=xd(R);c[h]=[f.size,p];R[p]=n;for(var r=1;r<f.size;++r)n=N.getUniformLocation(b,h+"["+r+"]"),p=xd(R),R[p]=n}}}var Tc={},wd,Bd,Dd=0;function Ed(){for(var a=V.length-1;0<=a;--a)Fd(a);V=[];W=[]}var W=[];
function Gd(a,b,c){function d(h,n){if(h.length!=n.length)return!1;for(var p in h)if(h[p]!=n[p])return!1;return!0}for(var e in W){var f=W[e];if(f.ef==a&&d(f.hf,c))return}W.push({ef:a,Bf:b,hf:c});W.sort(function(h,n){return h.Bf<n.Bf})}function Hd(a){for(var b=0;b<W.length;++b)W[b].ef==a&&(W.splice(b,1),--b)}function Id(){if(Dd&&Jd.De)for(var a=0;a<W.length;++a){var b=W[a];W.splice(a,1);--a;b.ef.apply(null,b.hf)}}var V=[];
function Fd(a){var b=V[a];b.target.removeEventListener(b.pe,b.Lf,b.te);V.splice(a,1)}function Kd(a){function b(d){++Dd;Jd=a;Id();a.xe(d);Id();--Dd}if(a.ue)a.Lf=b,a.target.addEventListener(a.pe,b,a.te),V.push(a),Ld||(Ma.push(Ed),Ld=!0);else for(var c=0;c<V.length;++c)V[c].target==a.target&&V[c].pe==a.pe&&Fd(c--)}function Md(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Nd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Od={},Ld,Jd,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd={},$d=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Y(a){a=2<a?y(a):a;return $d[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function ae(a){var b=be(),c=ce(8),d=c+4,e=ce(a.id.length+1);A(a.id,e,a.id.length+1);if(a=Y(e))E[c>>2]=a.width,E[d>>2]=a.height;c=[E[c>>2],E[d>>2]];de(b);return c}function ee(a,b,c){a=Y(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function fe(a,b,c){if(a.pg){var d=be(),e=ce(a.id.length+1);A(a.id,e,a.id.length+1);ee(e,b,c);de(d)}else a.width=b,a.height=c}
function ge(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),fe(a,d,e),a.style.width=f,a.style.height=h,a.style.backgroundColor=n,p||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=p,a.style.paddingLeft=r,a.style.paddingRight=q,a.style.paddingTop=u,a.style.paddingBottom=w,a.style.marginLeft=m,a.style.marginRight=
v,a.style.marginTop=x,a.style.marginBottom=C,document.body.style.margin=X,document.documentElement.style.overflow=na,document.body.scroll=pc,a.style.sf=L,a.Je&&a.Je.Ae.viewport(0,0,d,e),Zd.Qe&&G.get(Zd.Qe)(37,0,Zd.kf))}var c=ae(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,n=a.style.backgroundColor,p=document.body.style.backgroundColor,r=a.style.paddingLeft,q=a.style.paddingRight,u=a.style.paddingTop,w=a.style.paddingBottom,m=a.style.marginLeft,v=a.style.marginRight,x=a.style.marginTop,C=a.style.marginBottom,
X=document.body.style.margin,na=document.documentElement.style.overflow,pc=document.body.scroll,L=a.style.sf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function he(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function ie(a){return 0>$d.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function je(a,b){if(0!=b.df||0!=b.We){ge(a);var c=b.gg?innerWidth:screen.width,d=b.gg?innerHeight:screen.height,e=ie(a),f=e.width;e=e.height;var h=ae(a),n=h[0];h=h[1];3==b.df?(he(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.df&&(c*h<n*d?(f=h*c/n,he(a,(d-f)/2,0),d=f):(f=n*d/h,he(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Mf&&(a.style.sf="pixelated");
f=2==b.We?devicePixelRatio:1;0!=b.We&&(c=c*f|0,d=d*f|0,fe(a,c,d),a.Je&&a.Je.Ae.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Nd()?-3:-1;Zd=b;b.Qe&&G.get(b.Qe)(37,0,b.kf);return 0}function ke(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Se)a.Se();else return document.body.requestPointerLock||document.body.Se?-3:-1;return 0}var le=[];
function me(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),h=f&&xd(d);f?(f.name=h,d[h]=f):U(1282);E[b+4*e>>2]=h}}function ne(a,b,c,d,e,f,h,n){b=Q[b];if(a=N[a](b,c))d=n&&A(a.name,n,d),e&&(E[e>>2]=d),f&&(E[f>>2]=a.size),h&&(E[h>>2]=a.type)}function oe(a,b){Ga[a>>2]=b;Ga[a+4>>2]=(b-Ga[a>>2])/4294967296}
function pe(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:E[b+4*a>>2]=e[a];break;case 2:F[b+4*a>>2]=e[a];break;case 4:D[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:oe(b,
d);break;case 0:E[b>>2]=d;break;case 2:F[b>>2]=d;break;case 4:D[b>>0]=d?1:0}}else U(1281)}function qe(a){var b=Ba(a)+1,c=B(b);A(a,c,b);return c}function re(a,b,c,d){if(c)if(a=N.getUniform(Q[a],R[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:E[c>>2]=a;break;case 2:F[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:E[c+4*b>>2]=a[b];break;case 2:F[c+4*b>>2]=a[b]}else U(1281)}
function se(a,b,c,d){if(c)if(a=N.getVertexAttrib(a,b),34975==b)E[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:E[c>>2]=a;break;case 2:F[c>>2]=a;break;case 5:E[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:E[c+4*b>>2]=a[b];break;case 2:F[c+4*b>>2]=a[b];break;case 5:E[c+4*b>>2]=Math.fround(a[b])}else U(1281)}
function te(a,b,c,d,e){a-=5120;a=1==a?z:4==a?E:6==a?F:5==a||28922==a?Ga:Fa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=vd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var ue=[],ve=[];function we(a,b){if(!Nd())return-1;a=Y(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Dd&&Jd.De?je(a,b):b.Jf?(Gd(je,1,[a,b]),1):-2:-3:-4}
function xe(a,b){var c={target:Y(2),pe:"beforeunload",ue:b,xe:function(d){d=d||event;var e=G.get(b)(28,0,a);e&&(e=y(e));if(e)return d.preventDefault(),d.returnValue=e},te:!0};Kd(c)}function ye(a,b,c,d,e,f){Pd||(Pd=B(256));a={target:Y(a),pe:f,ue:d,xe:function(h){h=h||event;var n=h.target.id?h.target.id:"",p=Pd;A(Md(h.target),p+0,128);A(n,p+128,128);G.get(d)(e,p,b)&&h.preventDefault()},te:c};Kd(a)}
function ze(a,b,c,d,e){Rd||(Rd=B(280));Kd({target:a,pe:e,ue:d,xe:function(f){f=f||event;var h=Rd,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!n;E[h>>2]=p;E[h+4>>2]=Nd();var r=p?n:Qd,q=r&&r.id?r.id:"";A(Md(r),h+8,128);A(q,h+136,128);E[h+264>>2]=r?r.clientWidth:0;E[h+268>>2]=r?r.clientHeight:0;E[h+272>>2]=screen.width;E[h+276>>2]=screen.height;p&&(Qd=n);G.get(d)(19,h,b)&&f.preventDefault()},te:c})}
function Ae(a,b,c,d,e,f){Sd||(Sd=B(164));a={target:Y(a),De:!0,pe:f,ue:d,xe:function(h){var n=Sd,p=n>>2;E[p]=h.location;E[p+1]=h.ctrlKey;E[p+2]=h.shiftKey;E[p+3]=h.altKey;E[p+4]=h.metaKey;E[p+5]=h.repeat;E[p+6]=h.charCode;E[p+7]=h.keyCode;E[p+8]=h.which;A(h.key||"",n+36,32);A(h.code||"",n+68,32);A(h.char||"",n+100,32);A(h.locale||"",n+132,32);G.get(d)(e,n,b)&&h.preventDefault()},te:c};Kd(a)}
function Be(a,b,c){a>>=2;E[a]=b.screenX;E[a+1]=b.screenY;E[a+2]=b.clientX;E[a+3]=b.clientY;E[a+4]=b.ctrlKey;E[a+5]=b.shiftKey;E[a+6]=b.altKey;E[a+7]=b.metaKey;Ea[2*a+16]=b.button;Ea[2*a+17]=b.buttons;E[a+9]=b.movementX;E[a+10]=b.movementY;c=ie(c);E[a+11]=b.clientX-c.left;E[a+12]=b.clientY-c.top}function Ce(a,b,c,d,e,f){Td||(Td=B(64));a=Y(a);Kd({target:a,De:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,pe:f,ue:d,xe:function(h){h=h||event;Be(Td,h,a);G.get(d)(e,Td,b)&&h.preventDefault()},te:c})}
function De(a,b,c,d,e){Ud||(Ud=B(260));Kd({target:a,pe:e,ue:d,xe:function(f){f=f||event;var h=Ud,n=document.pointerLockElement||document.Ke||document.zf||document.vf;E[h>>2]=!!n;var p=n&&n.id?n.id:"";A(Md(n),h+4,128);A(p,h+132,128);G.get(d)(20,h,b)&&f.preventDefault()},te:c})}
function Ee(a,b,c,d){Vd||(Vd=B(36));a=Y(a);Kd({target:a,pe:"resize",ue:d,xe:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var h=Vd;E[h>>2]=e.detail;E[h+4>>2]=f.clientWidth;E[h+8>>2]=f.clientHeight;E[h+12>>2]=innerWidth;E[h+16>>2]=innerHeight;E[h+20>>2]=outerWidth;E[h+24>>2]=outerHeight;E[h+28>>2]=pageXOffset;E[h+32>>2]=pageYOffset;G.get(d)(10,h,b)&&e.preventDefault()}}},te:c})}
function Fe(a,b,c,d,e,f){Wd||(Wd=B(1684));a=Y(a);Kd({target:a,De:"touchstart"==f||"touchend"==f,pe:f,ue:d,xe:function(h){for(var n={},p=h.touches,r=0;r<p.length;++r){var q=p[r];n[q.identifier]=q}p=h.changedTouches;for(r=0;r<p.length;++r)q=p[r],q.Uf=1,n[q.identifier]=q;p=h.targetTouches;for(r=0;r<p.length;++r)n[p[r].identifier].Yf=1;p=Wd;q=p>>2;E[q+1]=h.ctrlKey;E[q+2]=h.shiftKey;E[q+3]=h.altKey;E[q+4]=h.metaKey;q+=5;var u=ie(a),w=0;for(r in n){var m=n[r];E[q]=m.identifier;E[q+1]=m.screenX;E[q+2]=m.screenY;
E[q+3]=m.clientX;E[q+4]=m.clientY;E[q+5]=m.pageX;E[q+6]=m.pageY;E[q+7]=m.Uf;E[q+8]=m.Yf;E[q+9]=m.clientX-u.left;E[q+10]=m.clientY-u.top;q+=13;if(31<++w)break}E[p>>2]=w;G.get(d)(e,p,b)&&h.preventDefault()},te:c})}function Ge(a,b,c){var d=$d[1];Xd||(Xd=B(8));Kd({target:d,pe:"visibilitychange",ue:c,xe:function(e){e=e||event;var f=Xd,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);E[f>>2]=document.hidden;E[f+4>>2]=h;G.get(c)(21,f,a)&&e.preventDefault()},te:b})}
function He(a,b,c,d){Yd||(Yd=B(96));Kd({target:a,De:!0,pe:"wheel",ue:d,xe:function(e){e=e||event;var f=Yd;Be(f,e,a);Ha[f+64>>3]=e.deltaX;Ha[f+72>>3]=e.deltaY;Ha[f+80>>3]=e.deltaZ;E[f+88>>2]=e.deltaMode;G.get(d)(9,f,b)&&e.preventDefault()},te:c})}var Ie={};
function Je(){if(!Ke){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Ie)a[b]=Ie[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ke=c}return Ke}var Ke;function Le(a){return 0===a%4&&(0!==a%100||0===a%400)}function Me(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Ne=[31,29,31,30,31,30,31,31,30,31,30,31],Oe=[31,28,31,30,31,30,31,31,30,31,30,31];function Pe(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Le(a.getFullYear())?Ne:Oe)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Qe(a,b,c,d){function e(m,v,x){for(m="number"===typeof m?m.toString():m||"";m.length<v;)m=x[0]+m;return m}function f(m,v){return e(m,v,"0")}function h(m,v){function x(X){return 0>X?-1:0<X?1:0}var C;0===(C=x(m.getFullYear()-v.getFullYear()))&&0===(C=x(m.getMonth()-v.getMonth()))&&(C=x(m.getDate()-v.getDate()));return C}function n(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function p(m){m=Pe(new Date(m.qe+1900,0,1),m.Ve);var v=new Date(m.getFullYear()+1,0,4),x=n(new Date(m.getFullYear(),0,4));v=n(v);return 0>=h(x,m)?0>=h(v,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var r=E[d+40>>2];d={jg:E[d>>2],ig:E[d+4>>2],Te:E[d+8>>2],Oe:E[d+12>>2],Ie:E[d+16>>2],qe:E[d+20>>2],Ue:E[d+24>>2],Ve:E[d+28>>2],Bg:E[d+32>>2],hg:E[d+
36>>2],kg:r?y(r):""};c=y(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in r)c=c.replace(new RegExp(q,"g"),r[q]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");r={"%a":function(m){return u[m.Ue].substring(0,3)},"%A":function(m){return u[m.Ue]},"%b":function(m){return w[m.Ie].substring(0,3)},"%B":function(m){return w[m.Ie]},"%C":function(m){return f((m.qe+1900)/100|0,2)},"%d":function(m){return f(m.Oe,2)},"%e":function(m){return e(m.Oe,2," ")},"%g":function(m){return p(m).toString().substring(2)},"%G":function(m){return p(m)},"%H":function(m){return f(m.Te,
2)},"%I":function(m){m=m.Te;0==m?m=12:12<m&&(m-=12);return f(m,2)},"%j":function(m){return f(m.Oe+Me(Le(m.qe+1900)?Ne:Oe,m.Ie-1),3)},"%m":function(m){return f(m.Ie+1,2)},"%M":function(m){return f(m.ig,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.Te&&12>m.Te?"AM":"PM"},"%S":function(m){return f(m.jg,2)},"%t":function(){return"\t"},"%u":function(m){return m.Ue||7},"%U":function(m){var v=new Date(m.qe+1900,0,1),x=0===v.getDay()?v:Pe(v,7-v.getDay());m=new Date(m.qe+1900,m.Ie,m.Oe);return 0>
h(x,m)?f(Math.ceil((31-x.getDate()+(Me(Le(m.getFullYear())?Ne:Oe,m.getMonth()-1)-31)+m.getDate())/7),2):0===h(x,v)?"01":"00"},"%V":function(m){var v=new Date(m.qe+1901,0,4),x=n(new Date(m.qe+1900,0,4));v=n(v);var C=Pe(new Date(m.qe+1900,0,1),m.Ve);return 0>h(C,x)?"53":0>=h(v,C)?"01":f(Math.ceil((x.getFullYear()<m.qe+1900?m.Ve+32-x.getDate():m.Ve+1-x.getDate())/7),2)},"%w":function(m){return m.Ue},"%W":function(m){var v=new Date(m.qe,0,1),x=1===v.getDay()?v:Pe(v,0===v.getDay()?1:7-v.getDay()+1);m=
new Date(m.qe+1900,m.Ie,m.Oe);return 0>h(x,m)?f(Math.ceil((31-x.getDate()+(Me(Le(m.getFullYear())?Ne:Oe,m.getMonth()-1)-31)+m.getDate())/7),2):0===h(x,v)?"01":"00"},"%y":function(m){return(m.qe+1900).toString().substring(2)},"%Y":function(m){return m.qe+1900},"%z":function(m){m=m.hg;var v=0<=m;m=Math.abs(m)/60;return(v?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.kg},"%%":function(){return"%"}};for(q in r)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),r[q](d)));q=
pb(c,!1);if(q.length>b)return 0;D.set(q,a);return q.length-1}var Re=[];function Ib(a,b,c,d){a||(a=this);this.parent=a;this.ze=a.ze;this.Ne=null;this.id=zb++;this.name=b;this.mode=c;this.le={};this.me={};this.rdev=d}
Object.defineProperties(Ib.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Wf:{get:function(){return 16384===(this.mode&61440)}},Vf:{get:function(){return 8192===(this.mode&61440)}}});$b();Ab=Array(4096);Pb(I,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");nb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Rb("/dev/null",259);mb(1280,qb);mb(1536,rb);Rb("/dev/tty",1280);Rb("/dev/tty1",1536);var a=jb();K("/dev","random",a);K("/dev","urandom",a);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Pb({ze:function(){var b=tb(a,"fd",16895,73);b.le={lookup:function(c,d){var e=yb[+d];if(!e)throw new H(8);c={parent:null,ze:{xf:"fake"},le:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=cc;g.FS_createDataFile=ec;g.FS_createPreloadedFile=ic;g.FS_createLazyFile=hc;g.FS_createDevice=K;g.FS_unlink=Tb;g.requestFullscreen=function(a,b){Zc(a,b)};g.requestAnimationFrame=function(a){zc(a)};
g.setCanvasSize=function(a,b,c){ad(g.canvas,a,b);c||bd()};g.pauseMainLoop=function(){wc=null;Bc++};g.resumeMainLoop=function(){Bc++;var a=sc,b=tc,c=uc;uc=null;Ac(c,0,!1,Dc,!0);rc(a,b);wc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Sc(a,b,c,d)};for(var N,Z=0;32>Z;++Z)le.push(Array(Z));var Se=new Float32Array(288);
for(Z=0;288>Z;++Z)ue[Z]=Se.subarray(0,Z+1);var Te=new Int32Array(288);for(Z=0;288>Z;++Z)ve[Z]=Te.subarray(0,Z+1);function pb(a,b){var c=Array(Ba(a)+1);a=Aa(a,c,0,c.length);b&&(c.length=a);return c}
var Ve={aa:function(a){return B(a+16)+16},$:function(a,b,c){(new db(a)).Rf(b,c);eb++;throw a;},U:function(a,b,c){mc=c;try{var d=oc(a);switch(b){case 0:var e=nc();return 0>e?-28:Vb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=nc(),d.flags|=e,0;case 12:return e=nc(),Ea[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return E[Ue()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof lc&&f instanceof H||t(f),-f.we}},Ya:function(a,
b,c){mc=c;try{var d=oc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=nc();return E[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=nc();if(!d.me.Tf)throw new H(59);return d.me.Tf(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:t("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof lc&&f instanceof H||t(f),-f.we}},Za:function(a,
b,c){mc=c;try{var d=y(a),e=c?nc():0;return Vb(d,b,e).fd}catch(f){return"undefined"!==typeof lc&&f instanceof H||t(f),-f.we}},T:function(){t()},d:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=qc();else return E[Ue()>>2]=28,-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0},s:function(){t("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},wa:function(a){if(12448==a)return O=12288,1;O=12300;return 0},Ia:function(a,
b,c,d,e){if(62E3!=a)O=12296,c=0;else{if(b)for(;;){a=E[b>>2];if(12321==a)P.alpha=0<E[b+4>>2];else if(12325==a)P.depth=0<E[b+4>>2];else if(12326==a)P.stencil=0<E[b+4>>2];else if(12337==a)a=E[b+4>>2],P.antialias=0<a;else if(12338==a)a=E[b+4>>2],P.antialias=1==a;else if(12544==a)P.wg=12547!=E[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(E[e>>2]=1),c&&0<d&&(E[c>>2]=62002),O=12288,c=1):(O=12300,c=0)}return c},Ga:function(a,b,c,d){if(62E3!=a)return O=12296,0;for(a=1;;){b=E[d>>2];if(12440==b)a=E[d+4>>
2];else if(12344==b)break;else return O=12292,0;d+=8}if(2!=a)return O=12293,0;P.uf=a-1;P.xg=0;jd=Uc(g.canvas,P);if(0!=jd)return O=12288,Vc(jd),g.mg=!0,Lc.forEach(function(e){e()}),Vc(null),62004;O=12297;return 0},Ea:function(a,b){if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;O=12288;return 62006},Fa:function(a,b){if(62E3!=a)return O=12296,0;if(62004!=b)return O=12294,0;a=jd;Bd===M[a]&&(Bd=null);if("object"===typeof Od)for(var c=M[a].Ae.canvas,d=0;d<V.length;++d)V[d].target!=c||Fd(d--);
M[a]&&M[a].Ae.canvas&&(M[a].Ae.canvas.Je=void 0);M[a]=null;O=12288;fd==b&&(fd=0);return 1},Da:function(a,b){if(62E3!=a)return O=12296,0;if(62006!=b)return O=12301,1;gd==b&&(gd=0);hd==b&&(hd=0);O=12288;return 1},Ha:function(a,b,c,d){if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;if(!d)return O=12300,0;O=12288;switch(c){case 12320:return E[d>>2]=P.alpha?32:24,1;case 12321:return E[d>>2]=P.alpha?8:0,1;case 12322:return E[d>>2]=8,1;case 12323:return E[d>>2]=8,1;case 12324:return E[d>>2]=8,1;
case 12325:return E[d>>2]=P.depth?24:0,1;case 12326:return E[d>>2]=P.stencil?8:0,1;case 12327:return E[d>>2]=12344,1;case 12328:return E[d>>2]=62002,1;case 12329:return E[d>>2]=0,1;case 12330:return E[d>>2]=4096,1;case 12331:return E[d>>2]=16777216,1;case 12332:return E[d>>2]=4096,1;case 12333:return E[d>>2]=0,1;case 12334:return E[d>>2]=0,1;case 12335:return E[d>>2]=12344,1;case 12337:return E[d>>2]=P.antialias?4:0,1;case 12338:return E[d>>2]=P.antialias?1:0,1;case 12339:return E[d>>2]=4,1;case 12340:return E[d>>
2]=12344,1;case 12341:case 12342:case 12343:return E[d>>2]=-1,1;case 12345:case 12346:return E[d>>2]=0,1;case 12347:return E[d>>2]=0,1;case 12348:return E[d>>2]=1;case 12349:case 12350:return E[d>>2]=0,1;case 12351:return E[d>>2]=12430,1;case 12352:return E[d>>2]=4,1;case 12354:return E[d>>2]=0,1;default:return O=12292,0}},P:function(){O=12288;return 62E3},ua:function(){return O},Ka:function(a,b,c){if(62E3==a)return b&&(E[b>>2]=1),c&&(E[c>>2]=4),ed=!0,O=12288,1;O=12296;return 0},Ca:function(a,b,c,
d){if(62E3!=a)return O=12296,0;if(0!=d&&62004!=d)return O=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return O=12301,0;Vc(d?jd:null);fd=d;hd=b;gd=c;O=12288;return 1},va:function(a,b){if(62E3!=a)return O=12296,0;O=12288;if(id[b])return id[b];switch(b){case 12371:a=Ca("Emscripten");break;case 12372:a=Ca("1.4 Emscripten EGL");break;case 12373:a=Ca("");break;case 12429:a=Ca("OpenGL_ES");break;default:return O=12300,0}return id[b]=a},Ba:function(){if(ed)if(g.ve)if(g.ve.isContextLost())O=12302;else return O=
12288,1;else O=12290;else O=12289;return 0},za:function(a,b){if(62E3!=a)return O=12296,0;0==b?rc(0,0):rc(1,b);O=12288;return 1},Ja:function(a){if(62E3!=a)return O=12296,0;hd=gd=fd=0;ed=!1;O=12288;return 1},xa:function(){O=12288;return 1},ya:function(){O=12288;return 1},a:function(a,b,c){Re.length=0;var d;for(c>>=2;d=z[b++];)(d=105>d)&&c&1&&c++,Re.push(d?Ha[c++>>1]:E[c]),++c;return bb[a].apply(null,Re)},Aa:function(){wc=null;Bc++;uc=null},pa:function(){if(!Nd())return-1;Hd(je);var a=$d[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ta:function(){Hd(ke);if(document.exitPointerLock)document.exitPointerLock();else if(document.oe)document.oe();else return-1;return 0},k:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},f:function(a,b,c){a=Y(a);if(!a)return-4;a=ie(a);Ha[b>>3]=a.width;Ha[c>>3]=a.height;return 0},q:qc,Md:function(a){N.activeTexture(a)},Ld:function(a,b){N.attachShader(Q[a],
S[b])},ka:function(a,b){N.se.beginQueryEXT(a,T[b])},Kd:function(a,b,c){N.bindAttribLocation(Q[a],b,y(c))},Jd:function(a,b){N.bindBuffer(a,od[b])},Id:function(a,b){N.bindFramebuffer(a,pd[b])},Hd:function(a,b){N.bindRenderbuffer(a,qd[b])},Gd:function(a,b){N.bindTexture(a,rd[b])},ca:function(a){N.bindVertexArray(sd[a])},Fd:function(a,b,c,d){N.blendColor(a,b,c,d)},Ed:function(a){N.blendEquation(a)},Dd:function(a,b){N.blendEquationSeparate(a,b)},Cd:function(a,b){N.blendFunc(a,b)},Bd:function(a,b,c,d){N.blendFuncSeparate(a,
b,c,d)},Ad:function(a,b,c,d){N.bufferData(a,c?z.subarray(c,c+b):b,d)},zd:function(a,b,c,d){N.bufferSubData(a,b,z.subarray(d,d+c))},yd:function(a){return N.checkFramebufferStatus(a)},xd:function(a){N.clear(a)},wd:function(a,b,c,d){N.clearColor(a,b,c,d)},vd:function(a){N.clearDepth(a)},ud:function(a){N.clearStencil(a)},td:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},sd:function(a){N.compileShader(S[a])},rd:function(a,b,c,d,e,f,h,n){N.compressedTexImage2D(a,b,c,d,e,f,n?z.subarray(n,n+h):null)},qd:function(a,
b,c,d,e,f,h,n,p){N.compressedTexSubImage2D(a,b,c,d,e,f,h,p?z.subarray(p,p+n):null)},pd:function(a,b,c,d,e,f,h,n){N.copyTexImage2D(a,b,c,d,e,f,h,n)},od:function(a,b,c,d,e,f,h,n){N.copyTexSubImage2D(a,b,c,d,e,f,h,n)},nd:function(){var a=xd(Q),b=N.createProgram();b.name=a;Q[a]=b;return a},md:function(a){var b=xd(S);S[b]=N.createShader(a);return b},ld:function(a){N.cullFace(a)},kd:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=od[d];e&&(N.deleteBuffer(e),e.name=0,od[d]=null)}},jd:function(a,b){for(var c=
0;c<a;++c){var d=E[b+4*c>>2],e=pd[d];e&&(N.deleteFramebuffer(e),e.name=0,pd[d]=null)}},id:function(a){if(a){var b=Q[a];b?(N.deleteProgram(b),b.name=0,Q[a]=null,td[a]=null):U(1281)}},na:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=T[d];e&&(N.se.deleteQueryEXT(e),T[d]=null)}},hd:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=qd[d];e&&(N.deleteRenderbuffer(e),e.name=0,qd[d]=null)}},gd:function(a){if(a){var b=S[a];b?(N.deleteShader(b),S[a]=null):U(1281)}},fd:function(a,b){for(var c=
0;c<a;c++){var d=E[b+4*c>>2],e=rd[d];e&&(N.deleteTexture(e),e.name=0,rd[d]=null)}},ba:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2];N.deleteVertexArray(sd[d]);sd[d]=null}},ed:function(a){N.depthFunc(a)},dd:function(a){N.depthMask(!!a)},cd:function(a,b){N.depthRange(a,b)},bd:function(a,b){N.detachShader(Q[a],S[b])},ad:function(a){N.disable(a)},$c:function(a){N.disableVertexAttribArray(a)},_c:function(a,b,c){N.drawArrays(a,b,c)},Pd:function(a,b,c,d){N.drawArraysInstanced(a,b,c,d)},Qd:function(a,
b){for(var c=le[a],d=0;d<a;d++)c[d]=E[b+4*d>>2];N.drawBuffers(c)},Zc:function(a,b,c,d){N.drawElements(a,b,c,d)},Od:function(a,b,c,d,e){N.drawElementsInstanced(a,b,c,d,e)},Yc:function(a){N.enable(a)},Xc:function(a){N.enableVertexAttribArray(a)},ja:function(a){N.se.endQueryEXT(a)},Wc:function(){N.finish()},Vc:function(){N.flush()},Uc:function(a,b,c,d){N.framebufferRenderbuffer(a,b,c,qd[d])},Tc:function(a,b,c,d,e){N.framebufferTexture2D(a,b,c,rd[d],e)},Sc:function(a){N.frontFace(a)},Rc:function(a,b){me(a,
b,"createBuffer",od)},Pc:function(a,b){me(a,b,"createFramebuffer",pd)},oa:function(a,b){for(var c=0;c<a;c++){var d=N.se.createQueryEXT();if(!d){for(U(1282);c<a;)E[b+4*c++>>2]=0;break}var e=xd(T);d.name=e;T[e]=d;E[b+4*c>>2]=e}},Oc:function(a,b){me(a,b,"createRenderbuffer",qd)},Nc:function(a,b){me(a,b,"createTexture",rd)},Sd:function(a,b){me(a,b,"createVertexArray",sd)},Qc:function(a){N.generateMipmap(a)},Lc:function(a,b,c,d,e,f,h){ne("getActiveAttrib",a,b,c,d,e,f,h)},Kc:function(a,b,c,d,e,f,h){ne("getActiveUniform",
a,b,c,d,e,f,h)},Jc:function(a,b,c,d){a=N.getAttachedShaders(Q[a]);var e=a.length;e>b&&(e=b);E[c>>2]=e;for(b=0;b<e;++b)E[d+4*b>>2]=S.indexOf(a[b])},Ic:function(a,b){return N.getAttribLocation(Q[a],y(b))},Hc:function(a,b){pe(a,b,4)},Gc:function(a,b,c){c?E[c>>2]=N.getBufferParameter(a,b):U(1281)},Fc:function(){var a=N.getError()||wd;wd=0;return a},Ec:function(a,b){pe(a,b,2)},Dc:function(a,b,c,d){a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=
a.name|0;E[d>>2]=a},Cc:function(a,b){pe(a,b,0)},zc:function(a,b,c,d){a=N.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(E[c>>2]=b)},Ac:function(a,b,c){if(c)if(a>=nd)U(1281);else{var d=td[a];if(d)if(35716==b)a=N.getProgramInfoLog(Q[a]),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b)E[c>>2]=d.af;else if(35722==b){if(-1==d.Le){a=Q[a];var e=N.getProgramParameter(a,35721);for(b=d.Le=0;b<e;++b)d.Le=Math.max(d.Le,N.getActiveAttrib(a,b).name.length+1)}E[c>>
2]=d.Le}else if(35381==b){if(-1==d.Me)for(a=Q[a],e=N.getProgramParameter(a,35382),b=d.Me=0;b<e;++b)d.Me=Math.max(d.Me,N.getActiveUniformBlockName(a,b).length+1);E[c>>2]=d.Me}else E[c>>2]=N.getProgramParameter(Q[a],b);else U(1282)}else U(1281)},ea:function(a,b,c){if(c){a=N.se.getQueryObjectEXT(T[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;oe(c,d)}else U(1281)},ga:function(a,b,c){if(c){a=N.se.getQueryObjectEXT(T[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;E[c>>2]=d}else U(1281)},da:function(a,b,c){if(c){a=
N.se.getQueryObjectEXT(T[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;oe(c,d)}else U(1281)},fa:function(a,b,c){if(c){a=N.se.getQueryObjectEXT(T[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;E[c>>2]=d}else U(1281)},ha:function(a,b,c){c?E[c>>2]=N.se.getQueryEXT(a,b):U(1281)},yc:function(a,b,c){c?E[c>>2]=N.getRenderbufferParameter(a,b):U(1281)},wc:function(a,b,c,d){a=N.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(E[c>>2]=b)},vc:function(a,b,c,d){a=N.getShaderPrecisionFormat(a,
b);E[c>>2]=a.rangeMin;E[c+4>>2]=a.rangeMax;E[d>>2]=a.precision},uc:function(a,b,c,d){if(a=N.getShaderSource(S[a]))b=0<b&&d?A(a,d,b):0,c&&(E[c>>2]=b)},xc:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(S[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=N.getShaderParameter(S[a],b):U(1281)},tc:function(a){if(ud[a])return ud[a];switch(a){case 7939:var b=N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+
d}));b=qe(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||U(1280);b=qe(b);break;case 7938:b=qe("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=qe(b);break;default:return U(1280),0}return ud[a]=b},sc:function(a,b,c){c?F[c>>2]=N.getTexParameter(a,b):U(1281)},rc:function(a,b,c){c?E[c>>2]=
N.getTexParameter(a,b):U(1281)},nc:function(a,b){b=y(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=td[a]&&td[a].ff[b])&&0<=c&&c<a[0]?a[1]+c:-1},pc:function(a,b,c){re(a,b,c,2)},oc:function(a,b,c){re(a,b,c,0)},kc:function(a,b,c){c?E[c>>2]=N.getVertexAttribOffset(a,b):U(1281)},mc:function(a,b,c){se(a,b,c,2)},lc:function(a,b,c){se(a,b,c,5)},jc:function(a,b){N.hint(a,b)},ic:function(a){return(a=od[a])?N.isBuffer(a):0},hc:function(a){return N.isEnabled(a)},
gc:function(a){return(a=pd[a])?N.isFramebuffer(a):0},ec:function(a){return(a=Q[a])?N.isProgram(a):0},ma:function(a){return(a=T[a])?N.se.isQueryEXT(a):0},dc:function(a){return(a=qd[a])?N.isRenderbuffer(a):0},cc:function(a){return(a=S[a])?N.isShader(a):0},bc:function(a){return(a=rd[a])?N.isTexture(a):0},Rd:function(a){return(a=sd[a])?N.isVertexArray(a):0},ac:function(a){N.lineWidth(a)},$b:function(a){N.linkProgram(Q[a]);Cd(a)},_b:function(a,b){3317==a&&(vd=b);N.pixelStorei(a,b)},Zb:function(a,b){N.polygonOffset(a,
b)},ia:function(a,b){N.se.queryCounterEXT(T[a],b)},Yb:function(a,b,c,d,e,f,h){(h=te(f,e,c,d,h))?N.readPixels(a,b,c,d,e,f,h):U(1280)},Xb:function(){},Wb:function(a,b,c,d){N.renderbufferStorage(a,b,c,d)},Vb:function(a,b){N.sampleCoverage(a,!!b)},Ub:function(a,b,c,d){N.scissor(a,b,c,d)},Tb:function(){U(1280)},Sb:function(a,b,c,d){b=yd(b,c,d);N.shaderSource(S[a],b)},Rb:function(a,b,c){N.stencilFunc(a,b,c)},Qb:function(a,b,c,d){N.stencilFuncSeparate(a,b,c,d)},Pb:function(a){N.stencilMask(a)},Ob:function(a,
b){N.stencilMaskSeparate(a,b)},Nb:function(a,b,c){N.stencilOp(a,b,c)},Mb:function(a,b,c,d){N.stencilOpSeparate(a,b,c,d)},Lb:function(a,b,c,d,e,f,h,n,p){N.texImage2D(a,b,c,d,e,f,h,n,p?te(n,h,d,e,p):null)},Kb:function(a,b,c){N.texParameterf(a,b,c)},Jb:function(a,b,c){N.texParameterf(a,b,F[c>>2])},Ib:function(a,b,c){N.texParameteri(a,b,c)},Hb:function(a,b,c){N.texParameteri(a,b,E[c>>2])},Gb:function(a,b,c,d,e,f,h,n,p){var r=null;p&&(r=te(n,h,e,f,p));N.texSubImage2D(a,b,c,d,e,f,h,n,r)},Fb:function(a,
b){N.uniform1f(R[a],b)},Eb:function(a,b,c){if(288>=b)for(var d=ue[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);N.uniform1fv(R[a],d)},Db:function(a,b){N.uniform1i(R[a],b)},Cb:function(a,b,c){if(288>=b)for(var d=ve[b-1],e=0;e<b;++e)d[e]=E[c+4*e>>2];else d=E.subarray(c>>2,c+4*b>>2);N.uniform1iv(R[a],d)},Bb:function(a,b,c){N.uniform2f(R[a],b,c)},Ab:function(a,b,c){if(144>=b)for(var d=ue[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);
N.uniform2fv(R[a],d)},zb:function(a,b,c){N.uniform2i(R[a],b,c)},yb:function(a,b,c){if(144>=b)for(var d=ve[2*b-1],e=0;e<2*b;e+=2)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2];else d=E.subarray(c>>2,c+8*b>>2);N.uniform2iv(R[a],d)},xb:function(a,b,c,d){N.uniform3f(R[a],b,c,d)},wb:function(a,b,c){if(96>=b)for(var d=ue[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);N.uniform3fv(R[a],d)},vb:function(a,b,c,d){N.uniform3i(R[a],b,c,d)},ub:function(a,
b,c){if(96>=b)for(var d=ve[3*b-1],e=0;e<3*b;e+=3)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2];else d=E.subarray(c>>2,c+12*b>>2);N.uniform3iv(R[a],d)},tb:function(a,b,c,d,e){N.uniform4f(R[a],b,c,d,e)},rb:function(a,b,c){if(72>=b){var d=ue[4*b-1],e=F;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=F.subarray(c>>2,c+16*b>>2);N.uniform4fv(R[a],d)},qb:function(a,b,c,d,e){N.uniform4i(R[a],b,c,d,e)},pb:function(a,b,c){if(72>=b)for(var d=
ve[4*b-1],e=0;e<4*b;e+=4)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2],d[e+3]=E[c+(4*e+12)>>2];else d=E.subarray(c>>2,c+16*b>>2);N.uniform4iv(R[a],d)},ob:function(a,b,c,d){if(72>=b)for(var e=ue[4*b-1],f=0;f<4*b;f+=4)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2];else e=F.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(R[a],!!c,e)},nb:function(a,b,c,d){if(32>=b)for(var e=ue[9*b-1],f=0;f<9*b;f+=9)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+
(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2];else e=F.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(R[a],!!c,e)},mb:function(a,b,c,d){if(18>=b){var e=ue[16*b-1],f=F;d>>=2;for(var h=0;h<16*b;h+=16){var n=d+h;e[h]=f[n];e[h+1]=f[n+1];e[h+2]=f[n+2];e[h+3]=f[n+3];e[h+4]=f[n+4];e[h+5]=f[n+5];e[h+6]=f[n+6];e[h+7]=f[n+7];e[h+8]=f[n+8];e[h+9]=f[n+9];e[h+10]=f[n+10];e[h+11]=f[n+11];e[h+12]=f[n+12];e[h+
13]=f[n+13];e[h+14]=f[n+14];e[h+15]=f[n+15]}}else e=F.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(R[a],!!c,e)},lb:function(a){N.useProgram(Q[a])},kb:function(a){N.validateProgram(Q[a])},jb:function(a,b){N.vertexAttrib1f(a,b)},ib:function(a,b){N.vertexAttrib1f(a,F[b>>2])},hb:function(a,b,c){N.vertexAttrib2f(a,b,c)},gb:function(a,b){N.vertexAttrib2f(a,F[b>>2],F[b+4>>2])},fb:function(a,b,c,d){N.vertexAttrib3f(a,b,c,d)},eb:function(a,b){N.vertexAttrib3f(a,F[b>>2],F[b+4>>2],F[b+8>>2])},db:function(a,b,
c,d,e){N.vertexAttrib4f(a,b,c,d,e)},cb:function(a,b){N.vertexAttrib4f(a,F[b>>2],F[b+4>>2],F[b+8>>2],F[b+12>>2])},Nd:function(a,b){N.vertexAttribDivisor(a,b)},bb:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},ab:function(a,b,c,d){N.viewport(a,b,c,d)},p:function(){return 0},Ra:function(a,b,c){z.copyWithin(a,b,b+c)},qa:function(a,b,c){return we(a,{df:E[c>>2],We:E[c+4>>2],Mf:E[c+8>>2],Jf:b,Qe:E[c+12>>2],kf:E[c+16>>2]})},O:function(a,b){a=Y(a);return a?a.requestPointerLock||a.Se?Dd&&Jd.De?
ke(a):b?(Gd(ke,2,[a]),1):-2:-1:-4},g:function(a){var b=z.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{va.grow(Math.min(2147483648,d)-Da.byteLength+65535>>>16);Ia();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},t:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;xe(a,b);return 0},F:function(a,b,c,d){ye(a,b,c,d,12,"blur");return 0},j:ee,n:function(a,
b,c){a=Y(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},G:function(a,b,c,d){ye(a,b,c,d,13,"focus");return 0},w:function(a,b,c,d){if(!Nd())return-1;a=Y(a);if(!a)return-4;ze(a,b,c,d,"fullscreenchange");ze(a,b,c,d,"webkitfullscreenchange");return 0},z:function(a,b,c,d){Ae(a,b,c,d,2,"keydown");return 0},x:function(a,b,c,d){Ae(a,b,c,d,1,"keypress");return 0},y:function(a,b,c,d){Ae(a,b,c,d,3,"keyup");return 0},Td:function(a,b,c){a=G.get(a);Ac(a,b,c)},L:function(a,b,c,d){Ce(a,b,c,
d,5,"mousedown");return 0},J:function(a,b,c,d){Ce(a,b,c,d,33,"mouseenter");return 0},I:function(a,b,c,d){Ce(a,b,c,d,34,"mouseleave");return 0},M:function(a,b,c,d){Ce(a,b,c,d,8,"mousemove");return 0},K:function(a,b,c,d){Ce(a,b,c,d,6,"mouseup");return 0},A:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.oe||document.body.Ke||document.body.Se))return-1;a=Y(a);if(!a)return-4;De(a,b,c,d,"pointerlockchange");De(a,b,c,d,"mozpointerlockchange");De(a,b,c,d,
"webkitpointerlockchange");De(a,b,c,d,"mspointerlockchange");return 0},v:function(a,b,c,d){Ee(a,b,c,d);return 0},B:function(a,b,c,d){Fe(a,b,c,d,25,"touchcancel");return 0},D:function(a,b,c,d){Fe(a,b,c,d,23,"touchend");return 0},C:function(a,b,c,d){Fe(a,b,c,d,24,"touchmove");return 0},E:function(a,b,c,d){Fe(a,b,c,d,22,"touchstart");return 0},u:function(a,b,c){if(!$d[1])return-4;Ge(a,b,c);return 0},H:function(a,b,c,d){a=Y(a);return"undefined"!==typeof a.onwheel?(He(a,b,c,d),0):-1},o:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},Wa:function(a){for(var b=qc();qc()-b<a;);},Ua:function(a,b){try{var c=0;Je().forEach(function(d,e){var f=b+c;e=E[a+4*e>>2]=f;for(f=0;f<d.length;++f)D[e++>>0]=d.charCodeAt(f);D[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof lc&&d instanceof H||t(d),d.we}},Va:function(a,b){try{var c=Je();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0}catch(e){return"undefined"!==typeof lc&&e instanceof H||t(e),e.we}},V:function(a){try{var b=oc(a);Xb(b);return 0}catch(c){return"undefined"!==
typeof lc&&c instanceof H||t(c),c.we}},Xa:function(a,b,c,d){try{a:{for(var e=oc(a),f=a=0;f<c;f++){var h=E[b+(8*f+4)>>2],n=e,p=E[b+8*f>>2],r=h,q=void 0,u=D;if(0>r||0>q)throw new H(28);if(null===n.fd)throw new H(8);if(1===(n.flags&2097155))throw new H(8);if(16384===(n.node.mode&61440))throw new H(31);if(!n.me.read)throw new H(28);var w="undefined"!==typeof q;if(!w)q=n.position;else if(!n.seekable)throw new H(70);var m=n.me.read(n,u,p,r,q);w||(n.position+=m);var v=m;if(0>v){var x=-1;break a}a+=v;if(v<
h)break}x=a}E[d>>2]=x;return 0}catch(C){return"undefined"!==typeof lc&&C instanceof H||t(C),C.we}},Qa:function(a,b,c,d,e){try{var f=oc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Yb(f,a,d);ab=[f.position>>>0,($a=f.position,1<=+Math.abs($a)?0<$a?(Math.min(+Math.floor($a/4294967296),4294967295)|0)>>>0:~~+Math.ceil(($a-+(~~$a>>>0))/4294967296)>>>0:0)];E[e>>2]=ab[0];E[e+4>>2]=ab[1];f.Ze&&0===a&&0===d&&(f.Ze=null);return 0}catch(h){return"undefined"!==typeof lc&&h instanceof
H||t(h),h.we}},$a:function(a,b,c,d){try{a:{for(var e=oc(a),f=a=0;f<c;f++){var h=Zb(e,D,E[b+8*f>>2],E[b+(8*f+4)>>2],void 0);if(0>h){var n=-1;break a}a+=h}n=a}E[d>>2]=n;return 0}catch(p){return"undefined"!==typeof lc&&p instanceof H||t(p),p.we}},c:function(a){var b=Date.now();E[a>>2]=b/1E3|0;E[a+4>>2]=b%1E3*1E3|0;return 0},Na:function(a){N.activeTexture(a)},W:function(a,b){N.attachShader(Q[a],S[b])},fc:function(a,b){N.bindBuffer(a,od[b])},Ma:function(a,b){N.bindTexture(a,rd[b])},Pa:function(a,b){N.blendFunc(a,
b)},N:function(a,b,c,d){N.bufferData(a,c?z.subarray(c,c+b):b,d)},ra:function(a){N.clear(a)},sa:function(a,b,c,d){N.clearColor(a,b,c,d)},X:function(a){N.compileShader(S[a])},sb:function(){var a=xd(Q),b=N.createProgram();b.name=a;Q[a]=b;return a},Z:function(a){var b=xd(S);S[b]=N.createShader(a);return b},_:function(a,b,c){N.drawArrays(a,b,c)},Sa:function(a){N.enable(a)},R:function(a){N.enableVertexAttribArray(a)},qc:function(a,b){me(a,b,"createBuffer",od)},la:function(a,b){me(a,b,"createFramebuffer",
pd)},Oa:function(a,b){me(a,b,"createTexture",rd)},S:function(a,b){return N.getAttribLocation(Q[a],y(b))},b:function(a,b){b=y(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=td[a]&&td[a].ff[b])&&0<=c&&c<a[0]?a[1]+c:-1},_a:function(a){N.linkProgram(Q[a]);Cd(a)},Y:function(a,b,c,d){b=yd(b,c,d);N.shaderSource(S[a],b)},Mc:function(a,b,c,d,e,f,h,n,p){N.texImage2D(a,b,c,d,e,f,h,n,p?te(n,h,d,e,p):null)},l:function(a,b,c){N.texParameteri(a,
b,c)},r:function(a,b){N.uniform1f(R[a],b)},Bc:function(a,b){N.uniform1i(R[a],b)},h:function(a,b,c){N.uniform2f(R[a],b,c)},m:function(a){N.useProgram(Q[a])},Q:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},e:function(){return 0},La:function(){return 0},Ta:function(a,b,c,d){return Qe(a,b,c,d)},i:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b}};
(function(){function a(e){g.asm=e.exports;va=g.asm.Ud;Ia();G=g.asm.je;Ka.unshift(g.asm.Vd);Ta("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Za().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+f);t(f)})}var d={a:Ve};Sa("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ua||"function"!==
typeof WebAssembly.instantiateStreaming||Wa()||Ua("file://")||"function"!==typeof fetch?c(b):fetch(Va,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Vd).apply(null,arguments)};g._setFade=function(){return(g._setFade=g.asm.Wd).apply(null,arguments)};
g._changePause=function(){return(g._changePause=g.asm.Xd).apply(null,arguments)};g._setSpeed=function(){return(g._setSpeed=g.asm.Yd).apply(null,arguments)};g._reverseA=function(){return(g._reverseA=g.asm.Zd).apply(null,arguments)};g._nextFrame=function(){return(g._nextFrame=g.asm._d).apply(null,arguments)};g._getAvgResistance=function(){return(g._getAvgResistance=g.asm.$d).apply(null,arguments)};g._getAvgSize=function(){return(g._getAvgSize=g.asm.ae).apply(null,arguments)};
g._getCount=function(){return(g._getCount=g.asm.be).apply(null,arguments)};g._restart=function(){return(g._restart=g.asm.ce).apply(null,arguments)};g._main=function(){return(g._main=g.asm.de).apply(null,arguments)};
var B=g._malloc=function(){return(B=g._malloc=g.asm.ee).apply(null,arguments)},Ue=g.___errno_location=function(){return(Ue=g.___errno_location=g.asm.fe).apply(null,arguments)},be=g.stackSave=function(){return(be=g.stackSave=g.asm.ge).apply(null,arguments)},de=g.stackRestore=function(){return(de=g.stackRestore=g.asm.he).apply(null,arguments)},ce=g.stackAlloc=function(){return(ce=g.stackAlloc=g.asm.ie).apply(null,arguments)};g.addRunDependency=Sa;g.removeRunDependency=Ta;g.FS_createPath=cc;
g.FS_createDataFile=ec;g.FS_createPreloadedFile=ic;g.FS_createLazyFile=hc;g.FS_createDevice=K;g.FS_unlink=Tb;var We;function qa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ra=function Xe(){We||Ye();We||(Ra=Xe)};
function Ye(){function a(){if(!We&&(We=!0,g.calledRun=!0,!wa)){g.noFSInit||ac||(ac=!0,$b(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?K("/dev","stdin",g.stdin):Sb("/dev/tty","/dev/stdin"),g.stdout?K("/dev","stdout",null,g.stdout):Sb("/dev/tty","/dev/stdout"),g.stderr?K("/dev","stderr",null,g.stderr):Sb("/dev/tty1","/dev/stderr"),Vb("/dev/stdin",0),Vb("/dev/stdout",1),Vb("/dev/stderr",1));cb(Ka);Bb=!1;cb(La);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ze){var b=g._main;try{var c=
b(0,0);Cc(c,!0)}catch(d){d instanceof qa||"unwind"==d||((b=d)&&"object"===typeof d&&d.stack&&(b=[d,d.stack]),k("exception thrown: "+b),da(1,d))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)b=g.postRun.shift(),Na.unshift(b);cb(Na)}}if(!(0<Pa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Oa();cb(Ja);0<Pa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);
a()},1)):a())}}g.run=Ye;function Cc(a,b){xa=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);wa=!0}da(a,new qa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ze=!0;g.noInitialRun&&(Ze=!1);Ye();
