
var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.mf||(h.mf=0);h.mf++;
(function(a){function b(p,r,q){var u=new XMLHttpRequest;u.open("GET",p,!0);u.responseType="arraybuffer";u.onprogress=function(w){var m=r;w.total&&(m=w.total);if(w.loaded){u.ye?h.Pe[p].loaded=w.loaded:(u.ye=!0,h.Pe||(h.Pe={}),h.Pe[p]={loaded:w.loaded,total:m});var v=m=w=0,x;for(x in h.Pe){var C=h.Pe[x];w+=C.total;m+=C.loaded;v++}w=Math.ceil(w*h.mf/v);h.setStatus&&h.setStatus("Downloading data... ("+m+"/"+w+")")}else!h.Pe&&h.setStatus&&h.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
p);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)q(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(p){console.error("package error:",p)}function d(){function p(w,m,v){this.start=w;this.$e=m;this.audio=v}function r(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);p.prototype.Sf=w;w=a.files;for(var m=0;m<
w.length;++m)p.prototype.ye[w[m].filename].onload();h.removeRunDependency("datafile_index.data")}h.FS_createPath("/","shaders",!0,!0);p.prototype={ye:{},open:function(w,m){this.name=m;this.ye[m]=this;h.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Rf(this.Sf.subarray(this.start,this.$e))},Rf:function(w){h.FS_createDataFile(this.name,null,w,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.ye[this.name]=null}};for(var q=a.files,u=0;u<q.length;++u)(new p(q[u].start,
q[u].end,q[u].audio)).open("GET",q[u].filename);h.addRunDependency("datafile_index.data");h.Qf||(h.Qf={});h.Qf["index.data"]={Jg:!1};n?(r(n),n=null):g=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("index.data",""):"index.data",f=a.remote_package_size,g=null,n=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;n||b(e,f,function(p){g?(g(p),g=null):n=p},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({files:[{filename:"/shaders/grid.frag",
start:0,end:1377,audio:0},{filename:"/shaders/post.frag",start:1377,end:2718,audio:0},{filename:"/shaders/tiles.frag",start:2718,end:3247,audio:0},{filename:"/shaders/post.vert",start:3247,end:3327,audio:0},{filename:"/shaders/texture.frag",start:3327,end:4925,audio:0},{filename:"/shaders/texture.vert",start:4925,end:5005,audio:0},{filename:"/shaders/grid.vert",start:5005,end:5085,audio:0},{filename:"/shaders/tiles.vert",start:5085,end:5165,audio:0},{filename:"/shaders/post2.frag",start:5165,end:7813,
audio:0}],remote_package_size:7813,package_uuid:"ff95902c-456d-48b5-a415-e3cc0a0b7d11"});var ba={},ca;for(ca in h)h.hasOwnProperty(ca)&&(ba[ca]=h[ca]);var da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var l="",ka,la,ma,na,pa,qa;
if(ia)l=ha?require("path").dirname(l)+"/":__dirname+"/",ka=function(a,b){pa||(pa=require("fs"));qa||(qa=require("path"));a=qa.normalize(a);return pa.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof ra))throw a;}),process.on("unhandledRejection",
t),ea=function(a){process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?
printErr:print);else if(fa||ha)ha?l=self.location.href:"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);
d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},na=function(a){document.title=a};var sa=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);for(ca in ba)ba.hasOwnProperty(ca)&&(h[ca]=ba[ca]);ba=null;h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);function ta(a){ua||(ua={});ua[a]||(ua[a]=1,k(a))}var ua,va;h.wasmBinary&&(va=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;
"object"!==typeof WebAssembly&&t("no native wasm support detected");
function wa(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":y[a>>0]=b;break;case "i8":y[a>>0]=b;break;case "i16":xa[a>>1]=b;break;case "i32":z[a>>2]=b;break;case "i64":ya=[b>>>0,(A=b,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];z[a>>2]=ya[0];z[a+4>>2]=ya[1];break;case "float":B[a>>2]=b;break;case "double":D[a>>3]=b;break;default:t("invalid type for setValue: "+c)}}var za,Aa=!1,Ba;
function assert(a,b){a||t("Assertion failed: "+b)}var Ca="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function E(a,b){return a?Da(F,a,b):""}
function Ea(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function G(a,b,c){return Ea(a,F,b,c)}
function Fa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ga(a){var b=Fa(a)+1,c=H(b);c&&Ea(a,y,c,b);return c}var Ha,y,F,xa,Ia,z,Ja,B,D,I,Ka=[],La=[],Ma=[],Na=[],Oa=[];function Pa(){var a=h.preRun.shift();Ka.unshift(a)}var Qa=0,Ra=null,Sa=null;function Ta(){Qa++;h.monitorRunDependencies&&h.monitorRunDependencies(Qa)}
function Ua(){Qa--;h.monitorRunDependencies&&h.monitorRunDependencies(Qa);if(0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}h.preloadedImages={};h.preloadedAudios={};function t(a){if(h.onAbort)h.onAbort(a);k(a);Aa=!0;Ba=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Va(a){var b=Wa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}
function Xa(){return Va("data:application/octet-stream;base64,")}var Wa="index.wasm";if(!Xa()){var Ya=Wa;Wa=h.locateFile?h.locateFile(Ya,l):l+Ya}function Za(){var a=Wa;try{if(a==Wa&&va)return new Uint8Array(va);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}
function $a(){if(!va&&(fa||ha)){if("function"===typeof fetch&&!Va("file://"))return fetch(Wa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Wa+"'";return a.arrayBuffer()}).catch(function(){return Za()});if(la)return new Promise(function(a,b){la(Wa,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Za()})}
var A,ya,bb={63184:function(){return window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth},63302:function(){return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight},63425:function(){return 0},63439:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.Wf!==h.canvas&&(d.He=h.createContext(h.canvas,!1,!0),d.Wf=h.canvas);if(d.w!==a||d.dg!==b||d.fg!==d.He)d.image=d.He.createImageData(a,b),d.w=a,d.dg=b,d.fg=d.He;a=d.image.data;b=c>>2;var e=
0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=z[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Hg!==a&&(d.Xf=new Int32Array(a.buffer),d.Yf=new Uint8Array(a.buffer)),a=d.Xf,c=a.length,a.set(z.subarray(b,b+c)),a=d.Yf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.He.putImageData(d.image,
0,0);return 0},64894:function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var n=0,p;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(p=b.length;n<p;){var r=z[e];b[n]=r&255;b[n+1]=r>>8&255;b[n+2]=r>>16&255;b[n+3]=r>>24&255;e++;n+=4}else b=new Int32Array(b.buffer),p=b.length,b.set(z.subarray(e,e+p));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+
") "+c+" "+d+", auto";d=H(c.length+1);G(c,d,c.length+1);return d},65883:function(a){h.canvas&&(h.canvas.style.cursor=E(a));return 0},65976:function(){h.canvas&&(h.canvas.style.cursor="none")},66045:function(){return screen.width},66070:function(){return screen.height},66096:function(){return window.innerWidth},66126:function(){return window.innerHeight},66157:function(a){"undefined"!==typeof na&&na(E(a));return 0},66252:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?
1:0},66389:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},66613:function(a){"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.xe||("undefined"!==typeof AudioContext?b.xe=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.xe=new webkitAudioContext),b.xe&&ab(b.xe));return void 0===b.xe?-1:0},67106:function(){return h.SDL2.xe.sampleRate},
67174:function(a,b,c,d){function e(){}function f(n){void 0!==g.capture.Ye&&(clearTimeout(g.capture.Ye),g.capture.Ye=void 0);g.capture.cf=g.xe.createMediaStreamSource(n);g.capture.Ae=g.xe.createScriptProcessor(b,a,1);g.capture.Ae.onaudioprocess=function(p){void 0!==g&&void 0!==g.capture&&(p.outputBuffer.getChannelData(0).fill(0),g.capture.lf=p.inputBuffer,p=[d],I.get(c).apply(null,p))};g.capture.cf.connect(g.capture.Ae);g.capture.Ae.connect(g.xe.destination);g.capture.stream=n}var g=h.SDL2;g.capture.ff=
g.xe.createBuffer(a,b,g.xe.sampleRate);g.capture.ff.getChannelData(0).fill(0);g.capture.Ye=setTimeout(function(){g.capture.lf=g.capture.ff;var n=[d];I.get(c).apply(null,n)},b/g.xe.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},68826:function(a,b,c,d){var e=h.SDL2;e.audio.Ae=e.xe.createScriptProcessor(b,
0,a);e.audio.Ae.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Cf=f.outputBuffer,f=[d],I.get(c).apply(null,f))};e.audio.Ae.connect(e.xe.destination)},69236:function(a,b){for(var c=h.SDL2,d=c.capture.lf.numberOfChannels,e=0;e<d;++e){var f=c.capture.lf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)wa(a+4*g,f[g]);else for(g=0;g<b;++g)wa(a+4*(g*d+e),f[g])}},
69841:function(a,b){for(var c=h.SDL2,d=c.audio.Cf.numberOfChannels,e=0;e<d;++e){var f=c.audio.Cf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=B[a+(g*d+e<<2)>>2]}},70321:function(a){var b=h.SDL2;if(a){void 0!==b.capture.Ye&&clearTimeout(b.capture.Ye);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.Ae&&(b.capture.Ae.onaudioprocess=function(){},b.capture.Ae.disconnect(),b.capture.Ae=void 0);void 0!==b.capture.cf&&(b.capture.cf.disconnect(),b.capture.cf=void 0);void 0!==b.capture.ff&&(b.capture.ff=void 0);b.capture=void 0}else void 0!=b.audio.Ae&&(b.audio.Ae.disconnect(),b.audio.Ae=void 0),b.audio=void 0;void 0!==b.xe&&void 0===b.audio&&void 0===b.capture&&(b.xe.close(),b.xe=void 0)}};function cb(a,b,c){a.addEventListener(b,c,{once:!0})}
function ab(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&cb(d,c,function(){"suspended"===a.state&&a.resume()})})})}function db(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.cg;"number"===typeof c?void 0===b.af?I.get(c)():I.get(c)(b.af):c(void 0===b.af?null:b.af)}}}
function eb(a){this.Se=a-16;this.vg=function(b){z[this.Se+8>>2]=b};this.sg=function(b){z[this.Se+0>>2]=b};this.tg=function(){z[this.Se+4>>2]=0};this.rg=function(){y[this.Se+12>>0]=0};this.ug=function(){y[this.Se+13>>0]=0};this.gg=function(b,c){this.vg(b);this.sg(c);this.tg();this.rg();this.ug()}}var fb=0;function gb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function hb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function ib(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function jb(a){if("/"===a)return"/";a=hb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function kb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){t("randomDevice")}}
function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var mb=[];function nb(a,b){mb[a]={input:[],output:[],Re:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Re.flush(a.tty)},flush:function(a){a.tty.Re.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Re.Gf)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Re.Gf(a.tty)}catch(n){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Re.sf)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.Re.sf(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},rb={Gf:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.ye?Buffer.ye(256):new Buffer(256),d=0;try{d=pa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=qb(b,!0)}return a.input.shift()},sf:function(a,b){null===b||10===b?(sa(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(sa(Da(a.output,0)),a.output=[])}},sb={sf:function(a,b){null===b||10===b?(k(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Da(a.output,0)),a.output=[])}},K={Je:null,Ke:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.Je||(K.Je={dir:{node:{Me:K.ue.Me,Ce:K.ue.Ce,lookup:K.ue.lookup,df:K.ue.df,rename:K.ue.rename,unlink:K.ue.unlink,rmdir:K.ue.rmdir,readdir:K.ue.readdir,symlink:K.ue.symlink},stream:{Oe:K.ve.Oe}},file:{node:{Me:K.ue.Me,Ce:K.ue.Ce},stream:{Oe:K.ve.Oe,read:K.ve.read,write:K.ve.write,xf:K.ve.xf,Lf:K.ve.Lf,Nf:K.ve.Nf}},link:{node:{Me:K.ue.Me,Ce:K.ue.Ce,readlink:K.ue.readlink},stream:{}},Bf:{node:{Me:K.ue.Me,
Ce:K.ue.Ce},stream:tb}});c=ub(a,b,c,d);16384===(c.mode&61440)?(c.ue=K.Je.dir.node,c.ve=K.Je.dir.stream,c.te={}):32768===(c.mode&61440)?(c.ue=K.Je.file.node,c.ve=K.Je.file.stream,c.we=0,c.te=null):40960===(c.mode&61440)?(c.ue=K.Je.link.node,c.ve=K.Je.link.stream):8192===(c.mode&61440)&&(c.ue=K.Je.Bf.node,c.ve=K.Je.Bf.stream);c.timestamp=Date.now();a&&(a.te[b]=c,a.timestamp=c.timestamp);return c},Kg:function(a){return a.te?a.te.subarray?a.te.subarray(0,a.we):new Uint8Array(a.te):new Uint8Array(0)},
Df:function(a,b){var c=a.te?a.te.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.te,a.te=new Uint8Array(b),0<a.we&&a.te.set(c.subarray(0,a.we),0))},pg:function(a,b){if(a.we!=b)if(0==b)a.te=null,a.we=0;else{var c=a.te;a.te=new Uint8Array(b);c&&a.te.set(c.subarray(0,Math.min(b,a.we)));a.we=b}},ue:{Me:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.we:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Vf=4096;b.blocks=Math.ceil(b.size/b.Vf);return b},Ce:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.pg(a,b.size)},lookup:function(){throw vb[44];},df:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=wb(b,
c)}catch(f){}if(d)for(var e in d.te)throw new J(55);}delete a.parent.te[a.name];a.parent.timestamp=Date.now();a.name=c;b.te[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.te[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=wb(a,b),d;for(d in c.te)throw new J(55);delete a.te[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.te)a.te.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},ve:{read:function(a,b,c,d,e){var f=a.node.te;if(e>=a.node.we)return 0;a=Math.min(a.node.we-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.te||a.te.subarray)){if(f)return a.te=b.subarray(c,c+d),a.we=d;if(0===a.we&&0===e)return a.te=b.slice(c,c+d),a.we=d;if(e+d<=a.we)return a.te.set(b.subarray(c,
c+d),e),d}K.Df(a,e+d);if(a.te.subarray&&b.subarray)a.te.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.te[e+f]=b[c+f];a.we=Math.max(a.we,e+d);return d},Oe:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.we);if(0>b)throw new J(28);return b},xf:function(a,b,c){K.Df(a.node,b+c);a.node.we=Math.max(a.node.we,b+c)},Lf:function(a,b,c,d,e,f){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.te;if(f&2||a.buffer!==Ha){if(0<d||d+c<a.length)a.subarray?
a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=H(f);c<f;)y[b+c++]=0;c=b;if(!c)throw new J(48);y.set(a,c)}else d=!1,c=a.byteOffset;return{Se:c,Eg:d}},Nf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.ve.write(a,b,0,d,c,!1);return 0}}},xb=null,yb={},zb=[],Ab=1,Bb=null,Cb=!0,Db={},J=null,vb={};
function Eb(a,b){a=lb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ef:!0,tf:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.tf)throw new J(32);a=gb(a.split("/").filter(function(g){return!!g}),!1);var e=xb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=wb(e,a[d]);c=hb(c+"/"+a[d]);e.Xe&&(!f||f&&b.Ef)&&(e=e.Xe.root);if(!f||b.nf)for(f=0;40960===(e.mode&61440);)if(e=Fb(c),c=lb(ib(c),e),e=Eb(c,{tf:b.tf}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function Gb(a){for(var b;;){if(a===a.parent)return a=a.Ke.Mf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Hb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Bb.length}function wb(a,b){var c;if(c=(c=Ib(a,"x"))?c:a.ue.lookup?0:2)throw new J(c,a);for(c=Bb[Hb(a.id,b)];c;c=c.Qe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ue.lookup(a,b)}
function ub(a,b,c,d){a=new Jb(a,b,c,d);b=Hb(a.parent.id,a.name);a.Qe=Bb[b];return Bb[b]=a}var Kb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Lb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ib(a,b){if(Cb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Mb(a,b){try{return wb(a,b),20}catch(c){}return Ib(a,"wx")}
function Nb(a){var b=4096;for(a=a||0;a<=b;a++)if(!zb[a])return a;throw new J(33);}function Ob(a,b){Pb||(Pb=function(){},Pb.prototype={});var c=new Pb,d;for(d in a)c[d]=a[d];a=c;b=Nb(b);a.fd=b;return zb[b]=a}var tb={open:function(a){a.ve=yb[a.node.rdev].ve;a.ve.open&&a.ve.open(a)},Oe:function(){throw new J(70);}};function ob(a,b){yb[a]={ve:b}}
function Qb(a,b){var c="/"===b,d=!b;if(c&&xb)throw new J(10);if(!c&&!d){var e=Eb(b,{Ef:!1});b=e.path;e=e.node;if(e.Xe)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,Qg:{},Mf:b,mg:[]};a=a.Ke(b);a.Ke=b;b.root=a;c?xb=a:e&&(e.Xe=b,e.Ke&&e.Ke.mg.push(b))}function Rb(a,b,c){var d=Eb(a,{parent:!0}).node;a=jb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Mb(d,a);if(e)throw new J(e);if(!d.ue.df)throw new J(63);return d.ue.df(d,a,b,c)}function L(a){return Rb(a,16895,0)}
function Sb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Rb(a,b|8192,c)}function Tb(a,b){if(!lb(a))throw new J(44);var c=Eb(b,{parent:!0}).node;if(!c)throw new J(44);b=jb(b);var d=Mb(c,b);if(d)throw new J(d);if(!c.ue.symlink)throw new J(63);c.ue.symlink(c,b,a)}
function Ub(a){var b=Eb(a,{parent:!0}).node,c=jb(a),d=wb(b,c);a:{try{var e=wb(b,c)}catch(g){e=g.Ie;break a}var f=Ib(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new J(e);if(!b.ue.unlink)throw new J(63);if(d.Xe)throw new J(10);try{Db.willDeletePath&&Db.willDeletePath(a)}catch(g){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.ue.unlink(b,c);b=Hb(d.parent.id,d.name);if(Bb[b]===d)Bb[b]=d.Qe;else for(b=Bb[b];b;){if(b.Qe===d){b.Qe=d.Qe;break}b=b.Qe}try{if(Db.onDeletePath)Db.onDeletePath(a)}catch(g){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+g.message)}}function Fb(a){a=Eb(a).node;if(!a)throw new J(44);if(!a.ue.readlink)throw new J(28);return lb(Gb(a.parent),a.ue.readlink(a))}function Vb(a,b){a="string"===typeof a?Eb(a,{nf:!0}).node:a;if(!a.ue.Ce)throw new J(63);a.ue.Ce(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Wb(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Kb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=hb(a);try{f=Eb(a,{nf:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Rb(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Lb(b)||b&512)?31:Ib(f,Lb(b)):44))throw new J(c);if(b&512){c=f;c="string"===typeof c?Eb(c,{nf:!0}).node:c;if(!c.ue.Ce)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=Ib(c,"w"))throw new J(e);c.ue.Ce(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Ob({node:f,path:Gb(f),flags:b,seekable:!0,position:0,ve:f.ve,Bg:[],error:!1},d);d.ve.open&&d.ve.open(d);!h.logReadFiles||b&1||(Xb||(Xb={}),a in Xb||(Xb[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{Db.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Db.onOpenFile(a,f))}catch(g){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+g.message)}return d}function Yb(a){if(null===a.fd)throw new J(8);a.pf&&(a.pf=null);try{a.ve.close&&a.ve.close(a)}catch(b){throw b;}finally{zb[a.fd]=null}a.fd=null}
function Zb(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.ve.Oe)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.ve.Oe(a,b,c);a.Bg=[]}
function $b(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(16384===(a.node.mode&61440))throw new J(31);if(!a.ve.write)throw new J(28);a.seekable&&a.flags&1024&&Zb(a,0,2);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.ve.write(a,b,c,d,e,f);g||(a.position+=b);try{if(a.path&&Db.onWriteToFile)Db.onWriteToFile(a.path)}catch(n){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
n.message)}return b}function ac(){J||(J=function(a,b){this.node=b;this.qg=function(c){this.Ie=c};this.qg(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){vb[a]=new J(a);vb[a].stack="<generic error, no stack>"}))}var bc;function cc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function dc(a,b){a="string"===typeof a?a:Gb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=hb(a+"/"+c);try{L(d)}catch(e){}a=d}}return d}
function ec(a,b,c,d){a=hb(("string"===typeof a?a:Gb(a))+"/"+b);c=cc(c,d);return Rb(a,(void 0!==c?c:438)&4095|32768,0)}function fc(a,b,c,d,e,f){a=b?hb(("string"===typeof a?a:Gb(a))+"/"+b):a;d=cc(d,e);e=Rb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var g=c.length;b<g;++b)a[b]=c.charCodeAt(b);c=a}Vb(e,d|146);a=Wb(e,577);$b(a,c,0,c.length,0,f);Yb(a);Vb(e,d)}return e}
function M(a,b,c,d){a=hb(("string"===typeof a?a:Gb(a))+"/"+b);b=cc(!!c,!!d);M.Jf||(M.Jf=64);var e=M.Jf++<<8|0;ob(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,g,n,p){for(var r=0,q=0;q<p;q++){try{var u=c()}catch(w){throw new J(29);}if(void 0===u&&0===r)throw new J(6);if(null===u||void 0===u)break;r++;g[n+q]=u}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,n,p){for(var r=0;r<p;r++)try{d(g[n+r])}catch(q){throw new J(29);}p&&(f.node.timestamp=
Date.now());return r}});return Sb(a,b,e)}function hc(a){if(!(a.kg||a.lg||a.link||a.te)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.te=qb(ka(a.url),!0),a.we=a.te.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ic(a,b,c,d,e){function f(){this.qf=!1;this.ye=[]}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var u=q%this.chunkSize;return this.Hf(q/this.chunkSize|0)[u]}};f.prototype.$e=function(q){this.Hf=q};f.prototype.zf=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var u=Number(q.getResponseHeader("Content-length")),w,m=(w=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;q=(w=q.getResponseHeader("Content-Encoding"))&&"gzip"===w;var v=1048576;m||(v=u);var x=this;x.$e(function(C){var aa=C*v,oa=(C+1)*v-1;oa=Math.min(oa,u-1);if("undefined"===typeof x.ye[C]){var oc=x.ye;if(aa>oa)throw Error("invalid range ("+aa+", "+oa+") or no bytes requested!");if(oa>u-1)throw Error("only "+u+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);u!==v&&N.setRequestHeader("Range","bytes="+aa+"-"+oa);"undefined"!=typeof Uint8Array&&(N.responseType=
"arraybuffer");N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);if(!(200<=N.status&&300>N.status||304===N.status))throw Error("Couldn't load "+c+". Status: "+N.status);aa=void 0!==N.response?new Uint8Array(N.response||[]):qb(N.responseText||"",!0);oc[C]=aa}if("undefined"===typeof x.ye[C])throw Error("doXHR failed!");return x.ye[C]});if(q||!u)v=u=1,v=u=this.Hf(0).length,sa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Uf=
u;this.Tf=v;this.qf=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;Object.defineProperties(g,{length:{get:function(){this.qf||this.zf();return this.Uf}},chunkSize:{get:function(){this.qf||this.zf();return this.Tf}}});var n=void 0}else n=c,g=void 0;var p=ec(a,b,d,e);g?p.te=g:n&&(p.te=null,p.url=n);Object.defineProperties(p,{we:{get:function(){return this.te.length}}});
var r={};Object.keys(p.ve).forEach(function(q){var u=p.ve[q];r[q]=function(){hc(p);return u.apply(null,arguments)}});r.read=function(q,u,w,m,v){hc(p);q=q.node.te;if(v>=q.length)return 0;m=Math.min(q.length-v,m);if(q.slice)for(var x=0;x<m;x++)u[w+x]=q[v+x];else for(x=0;x<m;x++)u[w+x]=q.get(v+x);return m};p.ve=r;return p}
function jc(a,b,c,d,e,f,g,n,p,r){function q(m){function v(C){r&&r();n||fc(a,b,C,d,e,p);f&&f();Ua(w)}var x=!1;h.preloadPlugins.forEach(function(C){!x&&C.canHandle(u)&&(C.handle(m,u,v,function(){g&&g();Ua(w)}),x=!0)});x||v(m)}kc();var u=b?lb(hb(a+"/"+b)):a,w="cp "+u;Ta(w);"string"==typeof c?lc(c,function(m){q(m)},g):q(c)}var mc={},Pb,Xb,nc=void 0;function pc(){nc+=4;return z[nc-4>>2]}function qc(a){a=zb[a];if(!a)throw new J(8);return a}var rc;
ia?rc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?rc=dateNow:rc=function(){return performance.now()};
function sc(a,b){tc=a;uc=b;if(vc)if(wc||(wc=!0),0==a)xc=function(){var d=Math.max(0,yc+b-rc())|0;setTimeout(zc,d)};else if(1==a)xc=function(){Ac(zc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}xc=function(){setImmediate(zc)}}}
function Bc(a,b,c,d,e){function f(){if(g<Cc){if(!noExitRuntime)try{Dc(Ba)}catch(n){if(!(n instanceof ra))throw n;}return!1}return!0}assert(!vc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");vc=a;Ec=d;var g=Cc;wc=!1;zc=function(){if(!Aa)if(0<Fc.length){var n=Date.now(),p=Fc.shift();p.cg(p.af);if(Gc){var r=Gc,q=0==r%1?r-1:Math.floor(r);Gc=p.Gg?q:(8*r+(q+.5))/
9}console.log('main loop blocker "'+p.name+'" took '+(Date.now()-n)+" ms");h.setStatus&&(n=h.statusMessage||"Please wait...",p=Gc,r=Hc.Ig,p?p<r?h.setStatus(n+" ("+(r-p)+"/"+r+")"):h.setStatus(n):h.setStatus(""));f()&&setTimeout(zc,0)}else f()&&(Ic=Ic+1|0,1==tc&&1<uc&&0!=Ic%uc?xc():(0==tc&&(yc=rc()),Aa||h.preMainLoop&&!1===h.preMainLoop()||(Jc(a),h.postMainLoop&&h.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.og&&SDL.audio.og(),xc())))};e||(b&&0<b?sc(0,1E3/b):sc(1,1),xc());if(c)throw"unwind";
}function Jc(a){try{a()}catch(b){if(!(b instanceof ra)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&k("exception thrown: "+[b,b.stack]),b;}}var wc=!1,xc=null,Cc=0,vc=null,Ec=0,tc=0,uc=0,Ic=0,Fc=[],Hc={},yc,zc,Gc,Kc=!1,Lc=!1,Mc=[];
function kc(){function a(){Lc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!Nc){Nc=!0;try{Oc=!0}catch(c){Oc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Pc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Oc?null:console.log("warning: no BlobBuilder");
Qc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Of||"undefined"!==typeof Qc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Of=!0);h.preloadPlugins.push({canHandle:function(c){return!h.Of&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(Oc)try{g=new Blob([c],{type:Rc(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Rc(d)}))}catch(r){ta("Blob constructor present but fails: "+
r+"; falling back to blob builder")}g||(g=new Pc,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var n=Qc.createObjectURL(g),p=new Image;p.onload=function(){assert(p.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=p.width;r.height=p.height;r.getContext("2d").drawImage(p,0,0);h.preloadedImages[d]=r;Qc.revokeObjectURL(n);e&&e(c)};p.onerror=function(){console.log("Image "+n+" could not be decoded");f&&f()};p.src=n}});h.preloadPlugins.push({canHandle:function(c){return!h.Pg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(u){p||(p=!0,h.preloadedAudios[d]=u,e&&e(c))}function n(){p||(p=!0,h.preloadedAudios[d]=new Audio,f&&f())}var p=!1;if(Oc){try{var r=new Blob([c],{type:Rc(d)})}catch(u){return n()}r=Qc.createObjectURL(r);var q=new Audio;q.addEventListener("canplaythrough",function(){g(q)},!1);q.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,m=0,
v=0;v<c.length;v++)for(w=w<<8|c[v],m+=8;6<=m;){var x=w>>m-6&63;m-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==m?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==m&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");q.src="data:audio/x-"+d.substr(-3)+";base64,"+u;g(q)}};q.src=r;Sc(function(){g(q)})}else return n()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&
b.addEventListener("click",function(c){!Lc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Tc(a,b,c,d){if(b&&h.He&&a==h.canvas)return h.He;var e;if(b){var f={antialias:!1,alpha:!1,Kf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof Uc&&(e=Vc(a,f)))var n=Wc[e].Le}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof O,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.He=n,b&&Xc(e),h.Cg=b,Mc.forEach(function(p){p()}),kc());return n}var Yc=!1,Zc=void 0,$c=void 0;
function ad(a,b){function c(){Kc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=bd,Zc&&d.requestPointerLock(),Kc=!0,$c?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=Ja[SDL.screen>>2]|8388608),cd(h.canvas),dd()):cd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),$c?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=Ja[SDL.screen>>2]&
-8388609),cd(h.canvas),dd()):cd(d));if(h.onFullScreen)h.onFullScreen(Kc);if(h.onFullscreen)h.onFullscreen(Kc)}Zc=a;$c=b;"undefined"===typeof Zc&&(Zc=!0);"undefined"===typeof $c&&($c=!1);var d=h.canvas;Yc||(Yc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function bd(){if(!Kc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var ed=0;function Ac(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ed)ed=b+1E3/60;else for(;b+2>=ed;)ed+=1E3/60;setTimeout(a,Math.max(ed-b,0))}}function Sc(a){setTimeout(function(){Jc(a)},1E4)}
function Rc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function lc(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ua(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ta(d)}var fd=[];function dd(){var a=h.canvas;fd.forEach(function(b){b(a.width,a.height)})}
function cd(a,b,c){b&&c?(a.Dg=b,a.eg=c):(b=a.Dg,c=a.eg);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}$c?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Nc,Oc,Pc,Qc,P=12288,gd=!1,hd=0,id=0,jd=0,Q={alpha:!1,depth:!1,stencil:!1,antialias:!1},kd={},ld;function md(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function nd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function od(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var pd=1,qd=[],R=[],rd=[],sd=[],td=[],S=[],T=[],ud=[],Wc=[],U=[],vd={},wd={},xd=4;
function V(a){yd||(yd=a)}function zd(a){for(var b=pd++,c=a.length;c<b;c++)a[c]=null;return b}function Ad(a,b,c){for(var d="",e=0;e<a;++e){var f=c?z[c+4*e>>2]:-1;d+=E(z[b+4*e>>2],0>f?void 0:f)}return d}function Vc(a,b){a.Ff||(a.Ff=a.getContext,a.getContext=function(d,e){e=a.Ff(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Bd(c,b):0}
function Bd(a,b){var c=zd(Wc),d={Lg:c,attributes:b,version:b.Kf,Le:a};a.canvas&&(a.canvas.Ue=d);Wc[c]=d;("undefined"===typeof b.$f||b.$f)&&Cd(d);return c}function Xc(a){Dd=Wc[a];h.He=O=Dd&&Dd.Le}function Cd(a){a||(a=Dd);if(!a.hg){a.hg=!0;var b=a.Le;md(b);nd(b);od(b);b.Fe=b.getExtension("EXT_disjoint_timer_query");b.Og=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}
function Ed(a){var b=R[a];a=vd[a]={wf:{},rf:0,Ve:-1,We:-1};for(var c=a.wf,d=O.getProgramParameter(b,35718),e=0;e<d;++e){var f=O.getActiveUniform(b,e),g=f.name;a.rf=Math.max(a.rf,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var n=O.getUniformLocation(b,g);if(n){var p=zd(S);c[g]=[f.size,p];S[p]=n;for(var r=1;r<f.size;++r)n=O.getUniformLocation(b,g+"["+r+"]"),p=zd(S),S[p]=n}}}var Uc={},yd,Dd,Fd=0;function Gd(){for(var a=Hd.length-1;0<=a;--a)Id(a);Hd=[];W=[]}var W=[];
function Jd(a,b,c){function d(g,n){if(g.length!=n.length)return!1;for(var p in g)if(g[p]!=n[p])return!1;return!0}for(var e in W){var f=W[e];if(f.vf==a&&d(f.yf,c))return}W.push({vf:a,Pf:b,yf:c});W.sort(function(g,n){return g.Pf<n.Pf})}function Kd(a){for(var b=0;b<W.length;++b)W[b].vf==a&&(W.splice(b,1),--b)}function Ld(){if(Fd&&Md.Ne)for(var a=0;a<W.length;++a){var b=W[a];W.splice(a,1);--a;b.vf.apply(null,b.yf)}}var Hd=[];
function Id(a){var b=Hd[a];b.target.removeEventListener(b.ze,b.ag,b.De);Hd.splice(a,1)}function X(a){function b(d){++Fd;Md=a;Ld();a.Ge(d);Ld();--Fd}if(a.Ee)a.ag=b,a.target.addEventListener(a.ze,b,a.De),Hd.push(a),Nd||(Na.push(Gd),Nd=!0);else for(var c=0;c<Hd.length;++c)Hd[c].target==a.target&&Hd[c].ze==a.ze&&Id(c--)}function Od(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Pd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Qd={},Nd,Md,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce={},de=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Y(a){a=2<a?E(a):a;return de[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function ee(a){var b=fe(),c=ge(8),d=c+4,e=ge(a.id.length+1);G(a.id,e,a.id.length+1);if(a=Y(e))z[c>>2]=a.width,z[d>>2]=a.height;c=[z[c>>2],z[d>>2]];he(b);return c}function ie(a,b,c){a=Y(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function je(a,b,c){if(a.Fg){var d=fe(),e=ge(a.id.length+1);G(a.id,e,a.id.length+1);ie(e,b,c);he(d)}else a.width=b,a.height=c}
function ke(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),je(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=n,p||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=p,a.style.paddingLeft=r,a.style.paddingRight=q,a.style.paddingTop=u,a.style.paddingBottom=w,a.style.marginLeft=m,a.style.marginRight=
v,a.style.marginTop=x,a.style.marginBottom=C,document.body.style.margin=aa,document.documentElement.style.overflow=oa,document.body.scroll=oc,a.style.If=N,a.Ue&&a.Ue.Le.viewport(0,0,d,e),ce.bf&&I.get(ce.bf)(37,0,ce.Af))}var c=ee(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,n=a.style.backgroundColor,p=document.body.style.backgroundColor,r=a.style.paddingLeft,q=a.style.paddingRight,u=a.style.paddingTop,w=a.style.paddingBottom,m=a.style.marginLeft,v=a.style.marginRight,x=a.style.marginTop,C=a.style.marginBottom,
aa=document.body.style.margin,oa=document.documentElement.style.overflow,oc=document.body.scroll,N=a.style.If;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function le(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function me(a){return 0>de.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function ne(a,b){if(0!=b.uf||0!=b.kf){ke(a);var c=b.wg?innerWidth:screen.width,d=b.wg?innerHeight:screen.height,e=me(a),f=e.width;e=e.height;var g=ee(a),n=g[0];g=g[1];3==b.uf?(le(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.uf&&(c*g<n*d?(f=g*c/n,le(a,(d-f)/2,0),d=f):(f=n*d/g,le(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.bg&&(a.style.If="pixelated");
f=2==b.kf?devicePixelRatio:1;0!=b.kf&&(c=c*f|0,d=d*f|0,je(a,c,d),a.Ue&&a.Ue.Le.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Pd()?-3:-1;ce=b;b.bf&&I.get(b.bf)(37,0,b.Af);return 0}function oe(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.ef)a.ef();else return document.body.requestPointerLock||document.body.ef?-3:-1;return 0}
function pe(a,b){D[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)D[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)D[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)z[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];z[a+1296>>2]=b.connected;z[a+1300>>2]=b.index;z[a+8>>2]=b.axes.length;z[a+12>>2]=b.buttons.length;G(b.id,a+1304,64);G(b.mapping,a+1368,64)}var qe=[];
function re(a,b,c,d){for(var e=0;e<a;e++){var f=O[c](),g=f&&zd(d);f?(f.name=g,d[g]=f):V(1282);z[b+4*e>>2]=g}}function se(a,b,c,d,e,f,g,n){b=R[b];if(a=O[a](b,c))d=n&&G(a.name,n,d),e&&(z[e>>2]=d),f&&(z[f>>2]=a.size),g&&(z[g>>2]=a.type)}function te(a,b){Ja[a>>2]=b;Ja[a+4>>2]=(b-Ja[a>>2])/4294967296}
function ue(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V(1280);return;case 36345:d=0;break;case 34466:var e=O.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=O.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z[b+4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:y[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){V(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:te(b,
d);break;case 0:z[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:y[b>>0]=d?1:0}}else V(1281)}function ve(a){var b=Fa(a)+1,c=H(b);G(a,c,b);return c}function we(a,b,c,d){if(c)if(a=O.getUniform(R[a],S[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:z[c>>2]=a;break;case 2:B[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:z[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b]}else V(1281)}
function xe(a,b,c,d){if(c)if(a=O.getVertexAttrib(a,b),34975==b)z[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:z[c>>2]=a;break;case 2:B[c>>2]=a;break;case 5:z[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:z[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;case 5:z[c+4*b>>2]=Math.fround(a[b])}else V(1281)}
function ye(a,b,c,d,e){a-=5120;a=1==a?F:4==a?z:6==a?B:5==a||28922==a?Ja:Ia;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=xd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var ze=[],Ae=[];function Be(a,b){if(!Pd())return-1;a=Y(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Fd&&Md.Ne?ne(a,b):b.Zf?(Jd(ne,1,[a,b]),1):-2:-3:-4}
function Ce(a,b){var c={target:Y(2),ze:"beforeunload",Ee:b,Ge:function(d){d=d||event;var e=I.get(b)(28,0,a);e&&(e=E(e));if(e)return d.preventDefault(),d.returnValue=e},De:!0};X(c)}function De(a,b,c,d,e,f){Sd||(Sd=H(256));a={target:Y(a),ze:f,Ee:d,Ge:function(g){g=g||event;var n=g.target.id?g.target.id:"",p=Sd;G(Od(g.target),p+0,128);G(n,p+128,128);I.get(d)(e,p,b)&&g.preventDefault()},De:c};X(a)}
function Ee(a,b,c,d,e){Ud||(Ud=H(280));X({target:a,ze:e,Ee:d,Ge:function(f){f=f||event;var g=Ud,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!n;z[g>>2]=p;z[g+4>>2]=Pd();var r=p?n:Td,q=r&&r.id?r.id:"";G(Od(r),g+8,128);G(q,g+136,128);z[g+264>>2]=r?r.clientWidth:0;z[g+268>>2]=r?r.clientHeight:0;z[g+272>>2]=screen.width;z[g+276>>2]=screen.height;p&&(Td=n);I.get(d)(19,g,b)&&f.preventDefault()},De:c})}
function Fe(a,b,c,d,e){Vd||(Vd=H(1432));b={target:Y(2),Ne:!0,ze:e,Ee:c,Ge:function(f){f=f||event;var g=Vd;pe(g,f.gamepad);I.get(c)(d,g,a)&&f.preventDefault()},De:b};X(b)}
function Ge(a,b,c,d,e,f){Wd||(Wd=H(164));a={target:Y(a),Ne:!0,ze:f,Ee:d,Ge:function(g){var n=Wd,p=n>>2;z[p]=g.location;z[p+1]=g.ctrlKey;z[p+2]=g.shiftKey;z[p+3]=g.altKey;z[p+4]=g.metaKey;z[p+5]=g.repeat;z[p+6]=g.charCode;z[p+7]=g.keyCode;z[p+8]=g.which;G(g.key||"",n+36,32);G(g.code||"",n+68,32);G(g.char||"",n+100,32);G(g.locale||"",n+132,32);I.get(d)(e,n,b)&&g.preventDefault()},De:c};X(a)}
function He(a,b,c){a>>=2;z[a]=b.screenX;z[a+1]=b.screenY;z[a+2]=b.clientX;z[a+3]=b.clientY;z[a+4]=b.ctrlKey;z[a+5]=b.shiftKey;z[a+6]=b.altKey;z[a+7]=b.metaKey;xa[2*a+16]=b.button;xa[2*a+17]=b.buttons;z[a+9]=b.movementX;z[a+10]=b.movementY;c=me(c);z[a+11]=b.clientX-c.left;z[a+12]=b.clientY-c.top}function Ie(a,b,c,d,e,f){Xd||(Xd=H(64));a=Y(a);X({target:a,Ne:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ze:f,Ee:d,Ge:function(g){g=g||event;He(Xd,g,a);I.get(d)(e,Xd,b)&&g.preventDefault()},De:c})}
function Je(a,b,c,d,e){Yd||(Yd=H(260));X({target:a,ze:e,Ee:d,Ge:function(f){f=f||event;var g=Yd,n=document.pointerLockElement||document.$e||document.Sf||document.Rf;z[g>>2]=!!n;var p=n&&n.id?n.id:"";G(Od(n),g+4,128);G(p,g+132,128);I.get(d)(20,g,b)&&f.preventDefault()},De:c})}
function Ke(a,b,c,d){Zd||(Zd=H(36));a=Y(a);X({target:a,ze:"resize",Ee:d,Ge:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=Zd;z[g>>2]=e.detail;z[g+4>>2]=f.clientWidth;z[g+8>>2]=f.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset;z[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&e.preventDefault()}}},De:c})}
function Le(a,b,c,d,e,f){$d||($d=H(1684));a=Y(a);X({target:a,Ne:"touchstart"==f||"touchend"==f,ze:f,Ee:d,Ge:function(g){for(var n={},p=g.touches,r=0;r<p.length;++r){var q=p[r];n[q.identifier]=q}p=g.changedTouches;for(r=0;r<p.length;++r)q=p[r],q.jg=1,n[q.identifier]=q;p=g.targetTouches;for(r=0;r<p.length;++r)n[p[r].identifier].ng=1;p=$d;q=p>>2;z[q+1]=g.ctrlKey;z[q+2]=g.shiftKey;z[q+3]=g.altKey;z[q+4]=g.metaKey;q+=5;var u=me(a),w=0;for(r in n){var m=n[r];z[q]=m.identifier;z[q+1]=m.screenX;z[q+2]=m.screenY;
z[q+3]=m.clientX;z[q+4]=m.clientY;z[q+5]=m.pageX;z[q+6]=m.pageY;z[q+7]=m.jg;z[q+8]=m.ng;z[q+9]=m.clientX-u.left;z[q+10]=m.clientY-u.top;q+=13;if(31<++w)break}z[p>>2]=w;I.get(d)(e,p,b)&&g.preventDefault()},De:c})}function Me(a,b,c){var d=de[1];ae||(ae=H(8));X({target:d,ze:"visibilitychange",Ee:c,Ge:function(e){e=e||event;var f=ae,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);z[f>>2]=document.hidden;z[f+4>>2]=g;I.get(c)(21,f,a)&&e.preventDefault()},De:b})}
function Ne(a,b,c,d){be||(be=H(96));X({target:a,Ne:!0,ze:"wheel",Ee:d,Ge:function(e){e=e||event;var f=be;He(f,e,a);D[f+64>>3]=e.deltaX;D[f+72>>3]=e.deltaY;D[f+80>>3]=e.deltaZ;z[f+88>>2]=e.deltaMode;I.get(d)(9,f,b)&&e.preventDefault()},De:c})}var Oe={};
function Pe(){if(!Qe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Oe)a[b]=Oe[b];var c=[];for(b in a)c.push(b+"="+a[b]);Qe=c}return Qe}var Qe;function Re(a){return 0===a%4&&(0!==a%100||0===a%400)}function Se(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Te=[31,29,31,30,31,30,31,31,30,31,30,31],Ue=[31,28,31,30,31,30,31,31,30,31,30,31];function Ve(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Re(a.getFullYear())?Te:Ue)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function We(a,b,c,d){function e(m,v,x){for(m="number"===typeof m?m.toString():m||"";m.length<v;)m=x[0]+m;return m}function f(m,v){return e(m,v,"0")}function g(m,v){function x(aa){return 0>aa?-1:0<aa?1:0}var C;0===(C=x(m.getFullYear()-v.getFullYear()))&&0===(C=x(m.getMonth()-v.getMonth()))&&(C=x(m.getDate()-v.getDate()));return C}function n(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function p(m){m=Ve(new Date(m.Be+1900,0,1),m.jf);var v=new Date(m.getFullYear()+1,0,4),x=n(new Date(m.getFullYear(),0,4));v=n(v);return 0>=g(x,m)?0>=g(v,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var r=z[d+40>>2];d={zg:z[d>>2],yg:z[d+4>>2],gf:z[d+8>>2],Ze:z[d+12>>2],Te:z[d+16>>2],Be:z[d+20>>2],hf:z[d+24>>2],jf:z[d+28>>2],Rg:z[d+32>>2],xg:z[d+
36>>2],Ag:r?E(r):""};c=E(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in r)c=c.replace(new RegExp(q,"g"),r[q]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");r={"%a":function(m){return u[m.hf].substring(0,3)},"%A":function(m){return u[m.hf]},"%b":function(m){return w[m.Te].substring(0,3)},"%B":function(m){return w[m.Te]},"%C":function(m){return f((m.Be+1900)/100|0,2)},"%d":function(m){return f(m.Ze,2)},"%e":function(m){return e(m.Ze,2," ")},"%g":function(m){return p(m).toString().substring(2)},"%G":function(m){return p(m)},"%H":function(m){return f(m.gf,
2)},"%I":function(m){m=m.gf;0==m?m=12:12<m&&(m-=12);return f(m,2)},"%j":function(m){return f(m.Ze+Se(Re(m.Be+1900)?Te:Ue,m.Te-1),3)},"%m":function(m){return f(m.Te+1,2)},"%M":function(m){return f(m.yg,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.gf&&12>m.gf?"AM":"PM"},"%S":function(m){return f(m.zg,2)},"%t":function(){return"\t"},"%u":function(m){return m.hf||7},"%U":function(m){var v=new Date(m.Be+1900,0,1),x=0===v.getDay()?v:Ve(v,7-v.getDay());m=new Date(m.Be+1900,m.Te,m.Ze);return 0>
g(x,m)?f(Math.ceil((31-x.getDate()+(Se(Re(m.getFullYear())?Te:Ue,m.getMonth()-1)-31)+m.getDate())/7),2):0===g(x,v)?"01":"00"},"%V":function(m){var v=new Date(m.Be+1901,0,4),x=n(new Date(m.Be+1900,0,4));v=n(v);var C=Ve(new Date(m.Be+1900,0,1),m.jf);return 0>g(C,x)?"53":0>=g(v,C)?"01":f(Math.ceil((x.getFullYear()<m.Be+1900?m.jf+32-x.getDate():m.jf+1-x.getDate())/7),2)},"%w":function(m){return m.hf},"%W":function(m){var v=new Date(m.Be,0,1),x=1===v.getDay()?v:Ve(v,0===v.getDay()?1:7-v.getDay()+1);m=
new Date(m.Be+1900,m.Te,m.Ze);return 0>g(x,m)?f(Math.ceil((31-x.getDate()+(Se(Re(m.getFullYear())?Te:Ue,m.getMonth()-1)-31)+m.getDate())/7),2):0===g(x,v)?"01":"00"},"%y":function(m){return(m.Be+1900).toString().substring(2)},"%Y":function(m){return m.Be+1900},"%z":function(m){m=m.xg;var v=0<=m;m=Math.abs(m)/60;return(v?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.Ag},"%%":function(){return"%"}};for(q in r)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),r[q](d)));q=
qb(c,!1);if(q.length>b)return 0;y.set(q,a);return q.length-1}var Xe=[];function Jb(a,b,c,d){a||(a=this);this.parent=a;this.Ke=a.Ke;this.Xe=null;this.id=Ab++;this.name=b;this.mode=c;this.ue={};this.ve={};this.rdev=d}
Object.defineProperties(Jb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},lg:{get:function(){return 16384===(this.mode&61440)}},kg:{get:function(){return 8192===(this.mode&61440)}}});ac();Bb=Array(4096);Qb(K,"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");ob(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Sb("/dev/null",259);nb(1280,rb);nb(1536,sb);Sb("/dev/tty",1280);Sb("/dev/tty1",1536);var a=kb();M("/dev","random",a);M("/dev","urandom",a);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Qb({Ke:function(){var b=ub(a,"fd",16895,73);b.ue={lookup:function(c,d){var e=zb[+d];if(!e)throw new J(8);c={parent:null,Ke:{Mf:"fake"},ue:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=dc;h.FS_createDataFile=fc;h.FS_createPreloadedFile=jc;h.FS_createLazyFile=ic;h.FS_createDevice=M;h.FS_unlink=Ub;h.requestFullscreen=function(a,b){ad(a,b)};h.requestAnimationFrame=function(a){Ac(a)};
h.setCanvasSize=function(a,b,c){cd(h.canvas,a,b);c||dd()};h.pauseMainLoop=function(){xc=null;Cc++};h.resumeMainLoop=function(){Cc++;var a=tc,b=uc,c=vc;vc=null;Bc(c,0,!1,Ec,!0);sc(a,b);xc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return Tc(a,b,c,d)};for(var O,Z=0;32>Z;++Z)qe.push(Array(Z));var Ye=new Float32Array(288);
for(Z=0;288>Z;++Z)ze[Z]=Ye.subarray(0,Z+1);var Ze=new Int32Array(288);for(Z=0;288>Z;++Z)Ae[Z]=Ze.subarray(0,Z+1);function qb(a,b){var c=Array(Fa(a)+1);a=Ea(a,c,0,c.length);b&&(c.length=a);return c}
var af={_:function(a){return H(a+16)+16},R:function(a,b,c){(new eb(a)).gg(b,c);fb++;throw a;},W:function(a,b,c){nc=c;try{var d=qc(a);switch(b){case 0:var e=pc();return 0>e?-28:Wb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=pc(),d.flags|=e,0;case 12:return e=pc(),xa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return z[$e()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof mc&&f instanceof J||t(f),-f.Ie}},Za:function(a,
b,c){nc=c;try{var d=qc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=pc();return z[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=pc();if(!d.ve.ig)throw new J(59);return d.ve.ig(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:t("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof mc&&f instanceof J||t(f),-f.Ie}},_a:function(a,
b,c){nc=c;try{var d=E(a),e=c?pc():0;return Wb(d,b,e).fd}catch(f){return"undefined"!==typeof mc&&f instanceof J||t(f),-f.Ie}},T:function(){t()},g:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=rc();else return z[$e()>>2]=28,-1;z[b>>2]=a/1E3|0;z[b+4>>2]=a%1E3*1E6|0;return 0},pa:function(){t("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Ea:function(a){if(12448==a)return P=12288,1;P=12300;return 0},Ha:function(a,
b,c,d,e){if(62E3!=a)P=12296,c=0;else{if(b)for(;;){a=z[b>>2];if(12321==a)Q.alpha=0<z[b+4>>2];else if(12325==a)Q.depth=0<z[b+4>>2];else if(12326==a)Q.stencil=0<z[b+4>>2];else if(12337==a)a=z[b+4>>2],Q.antialias=0<a;else if(12338==a)a=z[b+4>>2],Q.antialias=1==a;else if(12544==a)Q.Mg=12547!=z[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(z[e>>2]=1),c&&0<d&&(z[c>>2]=62002),P=12288,c=1):(P=12300,c=0)}return c},va:function(a,b,c,d){if(62E3!=a)return P=12296,0;for(a=1;;){b=z[d>>2];if(12440==b)a=z[d+4>>
2];else if(12344==b)break;else return P=12292,0;d+=8}if(2!=a)return P=12293,0;Q.Kf=a-1;Q.Ng=0;ld=Vc(h.canvas,Q);if(0!=ld)return P=12288,Xc(ld),h.Cg=!0,Mc.forEach(function(e){e()}),Xc(null),62004;P=12297;return 0},xa:function(a,b){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;P=12288;return 62006},wa:function(a,b){if(62E3!=a)return P=12296,0;if(62004!=b)return P=12294,0;a=ld;Dd===Wc[a]&&(Dd=null);if("object"===typeof Qd)for(var c=Wc[a].Le.canvas,d=0;d<Hd.length;++d)Hd[d].target!=c||Id(d--);
Wc[a]&&Wc[a].Le.canvas&&(Wc[a].Le.canvas.Ue=void 0);Wc[a]=null;P=12288;hd==b&&(hd=0);return 1},ya:function(a,b){if(62E3!=a)return P=12296,0;if(62006!=b)return P=12301,1;id==b&&(id=0);jd==b&&(jd=0);P=12288;return 1},Ia:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;if(!d)return P=12300,0;P=12288;switch(c){case 12320:return z[d>>2]=Q.alpha?32:24,1;case 12321:return z[d>>2]=Q.alpha?8:0,1;case 12322:return z[d>>2]=8,1;case 12323:return z[d>>2]=8,1;case 12324:return z[d>>2]=
8,1;case 12325:return z[d>>2]=Q.depth?24:0,1;case 12326:return z[d>>2]=Q.stencil?8:0,1;case 12327:return z[d>>2]=12344,1;case 12328:return z[d>>2]=62002,1;case 12329:return z[d>>2]=0,1;case 12330:return z[d>>2]=4096,1;case 12331:return z[d>>2]=16777216,1;case 12332:return z[d>>2]=4096,1;case 12333:return z[d>>2]=0,1;case 12334:return z[d>>2]=0,1;case 12335:return z[d>>2]=12344,1;case 12337:return z[d>>2]=Q.antialias?4:0,1;case 12338:return z[d>>2]=Q.antialias?1:0,1;case 12339:return z[d>>2]=4,1;case 12340:return z[d>>
2]=12344,1;case 12341:case 12342:case 12343:return z[d>>2]=-1,1;case 12345:case 12346:return z[d>>2]=0,1;case 12347:return z[d>>2]=0,1;case 12348:return z[d>>2]=1;case 12349:case 12350:return z[d>>2]=0,1;case 12351:return z[d>>2]=12430,1;case 12352:return z[d>>2]=4,1;case 12354:return z[d>>2]=0,1;default:return P=12292,0}},Q:function(){P=12288;return 62E3},ua:function(){return P},Fa:function(a,b,c){if(62E3==a)return b&&(z[b>>2]=1),c&&(z[c>>2]=4),gd=!0,P=12288,1;P=12296;return 0},za:function(a,b,c,
d){if(62E3!=a)return P=12296,0;if(0!=d&&62004!=d)return P=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return P=12301,0;Xc(d?ld:null);hd=d;jd=b;id=c;P=12288;return 1},ta:function(a,b){if(62E3!=a)return P=12296,0;P=12288;if(kd[b])return kd[b];switch(b){case 12371:a=Ga("Emscripten");break;case 12372:a=Ga("1.4 Emscripten EGL");break;case 12373:a=Ga("");break;case 12429:a=Ga("OpenGL_ES");break;default:return P=12300,0}return kd[b]=a},Aa:function(){if(gd)if(h.He)if(h.He.isContextLost())P=12302;else return P=
12288,1;else P=12290;else P=12289;return 0},Ba:function(a,b){if(62E3!=a)return P=12296,0;0==b?sc(0,0):sc(1,b);P=12288;return 1},Ga:function(a){if(62E3!=a)return P=12296,0;jd=id=hd=0;gd=!1;P=12288;return 1},Da:function(){P=12288;return 1},Ca:function(){P=12288;return 1},a:function(a,b,c){Xe.length=0;var d;for(c>>=2;d=F[b++];)(d=105>d)&&c&1&&c++,Xe.push(d?D[c++>>1]:z[c]),++c;return bb[a].apply(null,Xe)},Oa:function(){xc=null;Cc++;vc=null},qa:function(){if(!Pd())return-1;Kd(ne);var a=de[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},sa:function(){Kd(oe);if(document.exitPointerLock)document.exitPointerLock();else if(document.ye)document.ye();else return-1;return 0},j:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},e:function(a,b,c){a=Y(a);if(!a)return-4;a=me(a);D[b>>3]=a.width;D[c>>3]=a.height;return 0},s:function(a,b){if(0>a||a>=Rd.length)return-5;if(!Rd[a])return-7;pe(b,Rd[a]);
return 0},oa:function(){return Rd.length},Md:function(a){O.activeTexture(a)},Ld:function(a,b){O.attachShader(R[a],T[b])},ja:function(a,b){O.Fe.beginQueryEXT(a,U[b])},Kd:function(a,b,c){O.bindAttribLocation(R[a],b,E(c))},Jd:function(a,b){O.bindBuffer(a,qd[b])},Id:function(a,b){O.bindFramebuffer(a,rd[b])},Hd:function(a,b){O.bindRenderbuffer(a,sd[b])},Gd:function(a,b){O.bindTexture(a,td[b])},Vd:function(a){O.bindVertexArray(ud[a])},Fd:function(a,b,c,d){O.blendColor(a,b,c,d)},Ed:function(a){O.blendEquation(a)},
Dd:function(a,b){O.blendEquationSeparate(a,b)},Bd:function(a,b){O.blendFunc(a,b)},Ad:function(a,b,c,d){O.blendFuncSeparate(a,b,c,d)},zd:function(a,b,c,d){O.bufferData(a,c?F.subarray(c,c+b):b,d)},yd:function(a,b,c,d){O.bufferSubData(a,b,F.subarray(d,d+c))},xd:function(a){return O.checkFramebufferStatus(a)},wd:function(a){O.clear(a)},vd:function(a,b,c,d){O.clearColor(a,b,c,d)},ud:function(a){O.clearDepth(a)},td:function(a){O.clearStencil(a)},sd:function(a,b,c,d){O.colorMask(!!a,!!b,!!c,!!d)},rd:function(a){O.compileShader(T[a])},
qd:function(a,b,c,d,e,f,g,n){O.compressedTexImage2D(a,b,c,d,e,f,n?F.subarray(n,n+g):null)},pd:function(a,b,c,d,e,f,g,n,p){O.compressedTexSubImage2D(a,b,c,d,e,f,g,p?F.subarray(p,p+n):null)},od:function(a,b,c,d,e,f,g,n){O.copyTexImage2D(a,b,c,d,e,f,g,n)},nd:function(a,b,c,d,e,f,g,n){O.copyTexSubImage2D(a,b,c,d,e,f,g,n)},md:function(){var a=zd(R),b=O.createProgram();b.name=a;R[a]=b;return a},ld:function(a){var b=zd(T);T[b]=O.createShader(a);return b},kd:function(a){O.cullFace(a)},jd:function(a,b){for(var c=
0;c<a;c++){var d=z[b+4*c>>2],e=qd[d];e&&(O.deleteBuffer(e),e.name=0,qd[d]=null)}},id:function(a,b){for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=rd[d];e&&(O.deleteFramebuffer(e),e.name=0,rd[d]=null)}},hd:function(a){if(a){var b=R[a];b?(O.deleteProgram(b),b.name=0,R[a]=null,vd[a]=null):V(1281)}},la:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=U[d];e&&(O.Fe.deleteQueryEXT(e),U[d]=null)}},gd:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=sd[d];e&&(O.deleteRenderbuffer(e),e.name=0,sd[d]=
null)}},fd:function(a){if(a){var b=T[a];b?(O.deleteShader(b),T[a]=null):V(1281)}},ed:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=td[d];e&&(O.deleteTexture(e),e.name=0,td[d]=null)}},Ud:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];O.deleteVertexArray(ud[d]);ud[d]=null}},dd:function(a){O.depthFunc(a)},cd:function(a){O.depthMask(!!a)},bd:function(a,b){O.depthRange(a,b)},ad:function(a,b){O.detachShader(R[a],T[b])},$c:function(a){O.disable(a)},_c:function(a){O.disableVertexAttribArray(a)},
Zc:function(a,b,c){O.drawArrays(a,b,c)},Qd:function(a,b,c,d){O.drawArraysInstanced(a,b,c,d)},Rd:function(a,b){for(var c=qe[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];O.drawBuffers(c)},Yc:function(a,b,c,d){O.drawElements(a,b,c,d)},Pd:function(a,b,c,d,e){O.drawElementsInstanced(a,b,c,d,e)},Xc:function(a){O.enable(a)},Wc:function(a){O.enableVertexAttribArray(a)},ia:function(a){O.Fe.endQueryEXT(a)},Vc:function(){O.finish()},Uc:function(){O.flush()},Tc:function(a,b,c,d){O.framebufferRenderbuffer(a,b,c,sd[d])},Sc:function(a,
b,c,d,e){O.framebufferTexture2D(a,b,c,td[d],e)},Rc:function(a){O.frontFace(a)},Qc:function(a,b){re(a,b,"createBuffer",qd)},Oc:function(a,b){re(a,b,"createFramebuffer",rd)},ma:function(a,b){for(var c=0;c<a;c++){var d=O.Fe.createQueryEXT();if(!d){for(V(1282);c<a;)z[b+4*c++>>2]=0;break}var e=zd(U);d.name=e;U[e]=d;z[b+4*c>>2]=e}},Nc:function(a,b){re(a,b,"createRenderbuffer",sd)},Mc:function(a,b){re(a,b,"createTexture",td)},Td:function(a,b){re(a,b,"createVertexArray",ud)},Pc:function(a){O.generateMipmap(a)},
Lc:function(a,b,c,d,e,f,g){se("getActiveAttrib",a,b,c,d,e,f,g)},Kc:function(a,b,c,d,e,f,g){se("getActiveUniform",a,b,c,d,e,f,g)},Jc:function(a,b,c,d){a=O.getAttachedShaders(R[a]);var e=a.length;e>b&&(e=b);z[c>>2]=e;for(b=0;b<e;++b)z[d+4*b>>2]=T.indexOf(a[b])},Ic:function(a,b){return O.getAttribLocation(R[a],E(b))},Hc:function(a,b){ue(a,b,4)},Gc:function(a,b,c){c?z[c>>2]=O.getBufferParameter(a,b):V(1281)},Ec:function(){var a=O.getError()||yd;yd=0;return a},Dc:function(a,b){ue(a,b,2)},Cc:function(a,
b,c,d){a=O.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;z[d>>2]=a},Bc:function(a,b){ue(a,b,0)},zc:function(a,b,c,d){a=O.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(z[c>>2]=b)},Ac:function(a,b,c){if(c)if(a>=pd)V(1281);else{var d=vd[a];if(d)if(35716==b)a=O.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b)z[c>>2]=d.rf;else if(35722==b){if(-1==d.Ve){a=R[a];
var e=O.getProgramParameter(a,35721);for(b=d.Ve=0;b<e;++b)d.Ve=Math.max(d.Ve,O.getActiveAttrib(a,b).name.length+1)}z[c>>2]=d.Ve}else if(35381==b){if(-1==d.We)for(a=R[a],e=O.getProgramParameter(a,35382),b=d.We=0;b<e;++b)d.We=Math.max(d.We,O.getActiveUniformBlockName(a,b).length+1);z[c>>2]=d.We}else z[c>>2]=O.getProgramParameter(R[a],b);else V(1282)}else V(1281)},Xd:function(a,b,c){if(c){a=O.Fe.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;te(c,d)}else V(1281)},fa:function(a,b,c){if(c){a=
O.Fe.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z[c>>2]=d}else V(1281)},Wd:function(a,b,c){if(c){a=O.Fe.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;te(c,d)}else V(1281)},ea:function(a,b,c){if(c){a=O.Fe.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z[c>>2]=d}else V(1281)},ga:function(a,b,c){c?z[c>>2]=O.Fe.getQueryEXT(a,b):V(1281)},yc:function(a,b,c){c?z[c>>2]=O.getRenderbufferParameter(a,b):V(1281)},wc:function(a,b,c,d){a=O.getShaderInfoLog(T[a]);
null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(z[c>>2]=b)},vc:function(a,b,c,d){a=O.getShaderPrecisionFormat(a,b);z[c>>2]=a.rangeMin;z[c+4>>2]=a.rangeMax;z[d>>2]=a.precision},uc:function(a,b,c,d){if(a=O.getShaderSource(T[a]))b=0<b&&d?G(a,d,b):0,c&&(z[c>>2]=b)},xc:function(a,b,c){c?35716==b?(a=O.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),z[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(T[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=O.getShaderParameter(T[a],b):V(1281)},tc:function(a){if(wd[a])return wd[a];
switch(a){case 7939:var b=O.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ve(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=O.getParameter(a))||V(1280);b=ve(b);break;case 7938:b=ve("OpenGL ES 2.0 ("+O.getParameter(7938)+")");break;case 35724:b=O.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ve(b);break;default:return V(1280),0}return wd[a]=
b},sc:function(a,b,c){c?B[c>>2]=O.getTexParameter(a,b):V(1281)},rc:function(a,b,c){c?z[c>>2]=O.getTexParameter(a,b):V(1281)},oc:function(a,b){b=E(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=vd[a]&&vd[a].wf[b])&&0<=c&&c<a[0]?a[1]+c:-1},qc:function(a,b,c){we(a,b,c,2)},pc:function(a,b,c){we(a,b,c,0)},lc:function(a,b,c){c?z[c>>2]=O.getVertexAttribOffset(a,b):V(1281)},nc:function(a,b,c){xe(a,b,c,2)},mc:function(a,b,c){xe(a,b,
c,5)},jc:function(a,b){O.hint(a,b)},ic:function(a){return(a=qd[a])?O.isBuffer(a):0},hc:function(a){return O.isEnabled(a)},gc:function(a){return(a=rd[a])?O.isFramebuffer(a):0},fc:function(a){return(a=R[a])?O.isProgram(a):0},ka:function(a){return(a=U[a])?O.Fe.isQueryEXT(a):0},ec:function(a){return(a=sd[a])?O.isRenderbuffer(a):0},dc:function(a){return(a=T[a])?O.isShader(a):0},cc:function(a){return(a=td[a])?O.isTexture(a):0},Sd:function(a){return(a=ud[a])?O.isVertexArray(a):0},bc:function(a){O.lineWidth(a)},
ac:function(a){O.linkProgram(R[a]);Ed(a)},_b:function(a,b){3317==a&&(xd=b);O.pixelStorei(a,b)},Zb:function(a,b){O.polygonOffset(a,b)},ha:function(a,b){O.Fe.queryCounterEXT(U[a],b)},Yb:function(a,b,c,d,e,f,g){(g=ye(f,e,c,d,g))?O.readPixels(a,b,c,d,e,f,g):V(1280)},Xb:function(){},Wb:function(a,b,c,d){O.renderbufferStorage(a,b,c,d)},Vb:function(a,b){O.sampleCoverage(a,!!b)},Ub:function(a,b,c,d){O.scissor(a,b,c,d)},Tb:function(){V(1280)},Sb:function(a,b,c,d){b=Ad(b,c,d);O.shaderSource(T[a],b)},Rb:function(a,
b,c){O.stencilFunc(a,b,c)},Pb:function(a,b,c,d){O.stencilFuncSeparate(a,b,c,d)},Ob:function(a){O.stencilMask(a)},Nb:function(a,b){O.stencilMaskSeparate(a,b)},Mb:function(a,b,c){O.stencilOp(a,b,c)},Lb:function(a,b,c,d){O.stencilOpSeparate(a,b,c,d)},Kb:function(a,b,c,d,e,f,g,n,p){O.texImage2D(a,b,c,d,e,f,g,n,p?ye(n,g,d,e,p):null)},Jb:function(a,b,c){O.texParameterf(a,b,c)},Ib:function(a,b,c){O.texParameterf(a,b,B[c>>2])},Hb:function(a,b,c){O.texParameteri(a,b,c)},Gb:function(a,b,c){O.texParameteri(a,
b,z[c>>2])},Fb:function(a,b,c,d,e,f,g,n,p){var r=null;p&&(r=ye(n,g,e,f,p));O.texSubImage2D(a,b,c,d,e,f,g,n,r)},Eb:function(a,b){O.uniform1f(S[a],b)},Db:function(a,b,c){if(288>=b)for(var d=ze[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);O.uniform1fv(S[a],d)},Cb:function(a,b){O.uniform1i(S[a],b)},Bb:function(a,b,c){if(288>=b)for(var d=Ae[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);O.uniform1iv(S[a],d)},Ab:function(a,b,c){O.uniform2f(S[a],b,c)},zb:function(a,
b,c){if(144>=b)for(var d=ze[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);O.uniform2fv(S[a],d)},yb:function(a,b,c){O.uniform2i(S[a],b,c)},xb:function(a,b,c){if(144>=b)for(var d=Ae[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);O.uniform2iv(S[a],d)},wb:function(a,b,c,d){O.uniform3f(S[a],b,c,d)},vb:function(a,b,c){if(96>=b)for(var d=ze[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=
B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);O.uniform3fv(S[a],d)},ub:function(a,b,c,d){O.uniform3i(S[a],b,c,d)},tb:function(a,b,c){if(96>=b)for(var d=Ae[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);O.uniform3iv(S[a],d)},sb:function(a,b,c,d,e){O.uniform4f(S[a],b,c,d,e)},rb:function(a,b,c){if(72>=b){var d=ze[4*b-1],e=B;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=B.subarray(c>>
2,c+16*b>>2);O.uniform4fv(S[a],d)},qb:function(a,b,c,d,e){O.uniform4i(S[a],b,c,d,e)},pb:function(a,b,c){if(72>=b)for(var d=Ae[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);O.uniform4iv(S[a],d)},ob:function(a,b,c,d){if(72>=b)for(var e=ze[4*b-1],f=0;f<4*b;f+=4)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2];else e=B.subarray(d>>2,d+16*b>>2);O.uniformMatrix2fv(S[a],
!!c,e)},nb:function(a,b,c,d){if(32>=b)for(var e=ze[9*b-1],f=0;f<9*b;f+=9)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2],e[f+4]=B[d+(4*f+16)>>2],e[f+5]=B[d+(4*f+20)>>2],e[f+6]=B[d+(4*f+24)>>2],e[f+7]=B[d+(4*f+28)>>2],e[f+8]=B[d+(4*f+32)>>2];else e=B.subarray(d>>2,d+36*b>>2);O.uniformMatrix3fv(S[a],!!c,e)},mb:function(a,b,c,d){if(18>=b){var e=ze[16*b-1],f=B;d>>=2;for(var g=0;g<16*b;g+=16){var n=d+g;e[g]=f[n];e[g+1]=f[n+1];e[g+2]=f[n+2];e[g+3]=f[n+3];e[g+4]=f[n+
4];e[g+5]=f[n+5];e[g+6]=f[n+6];e[g+7]=f[n+7];e[g+8]=f[n+8];e[g+9]=f[n+9];e[g+10]=f[n+10];e[g+11]=f[n+11];e[g+12]=f[n+12];e[g+13]=f[n+13];e[g+14]=f[n+14];e[g+15]=f[n+15]}}else e=B.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(S[a],!!c,e)},lb:function(a){O.useProgram(R[a])},kb:function(a){O.validateProgram(R[a])},jb:function(a,b){O.vertexAttrib1f(a,b)},ib:function(a,b){O.vertexAttrib1f(a,B[b>>2])},hb:function(a,b,c){O.vertexAttrib2f(a,b,c)},gb:function(a,b){O.vertexAttrib2f(a,B[b>>2],B[b+4>>2])},fb:function(a,
b,c,d){O.vertexAttrib3f(a,b,c,d)},eb:function(a,b){O.vertexAttrib3f(a,B[b>>2],B[b+4>>2],B[b+8>>2])},db:function(a,b,c,d,e){O.vertexAttrib4f(a,b,c,d,e)},cb:function(a,b){O.vertexAttrib4f(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},Od:function(a,b){O.vertexAttribDivisor(a,b)},ab:function(a,b,c,d,e,f){O.vertexAttribPointer(a,b,c,!!d,e,f)},$a:function(a,b,c,d){O.viewport(a,b,c,d)},p:function(){return 0},Ra:function(a,b,c){F.copyWithin(a,b,b+c)},ra:function(a,b,c){return Be(a,{uf:z[c>>2],kf:z[c+4>>2],bg:z[c+
8>>2],Zf:b,bf:z[c+12>>2],Af:z[c+16>>2]})},P:function(a,b){a=Y(a);return a?a.requestPointerLock||a.ef?Fd&&Md.Ne?oe(a):b?(Jd(oe,2,[a]),1):-2:-1:-4},Sa:function(){t("OOM")},t:function(){return(Rd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},u:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;Ce(a,b);return 0},H:function(a,b,c,d){De(a,b,c,d,12,"blur");return 0},i:ie,n:function(a,b,c){a=Y(a);if(!a)return-4;
a.style.width=b+"px";a.style.height=c+"px";return 0},I:function(a,b,c,d){De(a,b,c,d,13,"focus");return 0},y:function(a,b,c,d){if(!Pd())return-1;a=Y(a);if(!a)return-4;Ee(a,b,c,d,"fullscreenchange");Ee(a,b,c,d,"webkitfullscreenchange");return 0},r:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Fe(a,b,c,26,"gamepadconnected");return 0},q:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Fe(a,b,c,27,"gamepaddisconnected");return 0},B:function(a,
b,c,d){Ge(a,b,c,d,2,"keydown");return 0},z:function(a,b,c,d){Ge(a,b,c,d,1,"keypress");return 0},A:function(a,b,c,d){Ge(a,b,c,d,3,"keyup");return 0},Na:function(a,b,c){a=I.get(a);Bc(a,b,c)},N:function(a,b,c,d){Ie(a,b,c,d,5,"mousedown");return 0},L:function(a,b,c,d){Ie(a,b,c,d,33,"mouseenter");return 0},K:function(a,b,c,d){Ie(a,b,c,d,34,"mouseleave");return 0},O:function(a,b,c,d){Ie(a,b,c,d,8,"mousemove");return 0},M:function(a,b,c,d){Ie(a,b,c,d,6,"mouseup");return 0},C:function(a,b,c,d){if(!document||
!document.body||!(document.body.requestPointerLock||document.body.ye||document.body.$e||document.body.ef))return-1;a=Y(a);if(!a)return-4;Je(a,b,c,d,"pointerlockchange");Je(a,b,c,d,"mozpointerlockchange");Je(a,b,c,d,"webkitpointerlockchange");Je(a,b,c,d,"mspointerlockchange");return 0},x:function(a,b,c,d){Ke(a,b,c,d);return 0},D:function(a,b,c,d){Le(a,b,c,d,25,"touchcancel");return 0},F:function(a,b,c,d){Le(a,b,c,d,23,"touchend");return 0},E:function(a,b,c,d){Le(a,b,c,d,24,"touchmove");return 0},G:function(a,
b,c,d){Le(a,b,c,d,22,"touchstart");return 0},w:function(a,b,c){if(!de[1])return-4;Me(a,b,c);return 0},J:function(a,b,c,d){a=Y(a);return"undefined"!==typeof a.onwheel?(Ne(a,b,c,d),0):-1},o:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Xa:function(a){for(var b=rc();rc()-b<a;);},Ua:function(a,b){try{var c=0;Pe().forEach(function(d,e){var f=b+c;e=z[a+4*e>>2]=f;for(f=0;f<d.length;++f)y[e++>>0]=d.charCodeAt(f);y[e>>0]=0;
c+=d.length+1});return 0}catch(d){return"undefined"!==typeof mc&&d instanceof J||t(d),d.Ie}},Wa:function(a,b){try{var c=Pe();z[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});z[b>>2]=d;return 0}catch(e){return"undefined"!==typeof mc&&e instanceof J||t(e),e.Ie}},V:function(a){try{var b=qc(a);Yb(b);return 0}catch(c){return"undefined"!==typeof mc&&c instanceof J||t(c),c.Ie}},Ya:function(a,b,c,d){try{a:{for(var e=qc(a),f=a=0;f<c;f++){var g=z[b+(8*f+4)>>2],n=e,p=z[b+8*f>>2],r=g,q=void 0,u=
y;if(0>r||0>q)throw new J(28);if(null===n.fd)throw new J(8);if(1===(n.flags&2097155))throw new J(8);if(16384===(n.node.mode&61440))throw new J(31);if(!n.ve.read)throw new J(28);var w="undefined"!==typeof q;if(!w)q=n.position;else if(!n.seekable)throw new J(70);var m=n.ve.read(n,u,p,r,q);w||(n.position+=m);var v=m;if(0>v){var x=-1;break a}a+=v;if(v<g)break}x=a}z[d>>2]=x;return 0}catch(C){return"undefined"!==typeof mc&&C instanceof J||t(C),C.Ie}},Qa:function(a,b,c,d,e){try{var f=qc(a);a=4294967296*
c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Zb(f,a,d);ya=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];z[e>>2]=ya[0];z[e+4>>2]=ya[1];f.pf&&0===a&&0===d&&(f.pf=null);return 0}catch(g){return"undefined"!==typeof mc&&g instanceof J||t(g),g.Ie}},U:function(a,b,c,d){try{a:{for(var e=qc(a),f=a=0;f<c;f++){var g=$b(e,y,z[b+8*f>>2],z[b+(8*f+4)>>2],void 0);if(0>g){var n=-1;break a}a+=
g}n=a}z[d>>2]=n;return 0}catch(p){return"undefined"!==typeof mc&&p instanceof J||t(p),p.Ie}},f:function(a){var b=Date.now();z[a>>2]=b/1E3|0;z[a+4>>2]=b%1E3*1E3|0;return 0},Va:function(a){O.activeTexture(a)},$:function(a,b){O.attachShader(R[a],T[b])},Cd:function(a,b){O.bindBuffer(a,qd[b])},Pa:function(a,b){O.bindTexture(a,td[b])},Qb:function(a,b){O.blendFunc(a,b)},da:function(a,b,c,d){O.bufferData(a,c?F.subarray(c,c+b):b,d)},La:function(a){O.clear(a)},Ma:function(a,b,c,d){O.clearColor(a,b,c,d)},aa:function(a){O.compileShader(T[a])},
Fc:function(){var a=zd(R),b=O.createProgram();b.name=a;R[a]=b;return a},ca:function(a){var b=zd(T);T[b]=O.createShader(a);return b},v:function(a,b,c){O.drawArrays(a,b,c)},$b:function(a){O.enable(a)},Y:function(a){O.enableVertexAttribArray(a)},Nd:function(a,b){re(a,b,"createBuffer",qd)},Ka:function(a,b){re(a,b,"createFramebuffer",rd)},bb:function(a,b){re(a,b,"createTexture",td)},Z:function(a,b){return O.getAttribLocation(R[a],E(b))},b:function(a,b){b=E(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");
c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=vd[a]&&vd[a].wf[b])&&0<=c&&c<a[0]?a[1]+c:-1},kc:function(a){O.linkProgram(R[a]);Ed(a)},ba:function(a,b,c,d){b=Ad(b,c,d);O.shaderSource(T[a],b)},na:function(a,b,c,d,e,f,g,n,p){O.texImage2D(a,b,c,d,e,f,g,n,p?ye(n,g,d,e,p):null)},l:function(a,b,c){O.texParameteri(a,b,c)},m:function(a,b){O.uniform1f(S[a],b)},Yd:function(a,b){O.uniform1i(S[a],b)},d:function(a,b,c){O.uniform2f(S[a],b,c)},k:function(a){O.useProgram(R[a])},X:function(a,b,c,d,
e,f){O.vertexAttribPointer(a,b,c,!!d,e,f)},S:function(){},c:function(){return 0},Ja:function(){return 0},Ta:function(a,b,c,d){return We(a,b,c,d)},h:function(a){var b=Date.now()/1E3|0;a&&(z[a>>2]=b);return b}};
(function(){function a(e){h.asm=e.exports;za=h.asm.Zd;Ha=e=za.buffer;h.HEAP8=y=new Int8Array(e);h.HEAP16=xa=new Int16Array(e);h.HEAP32=z=new Int32Array(e);h.HEAPU8=F=new Uint8Array(e);h.HEAPU16=Ia=new Uint16Array(e);h.HEAPU32=Ja=new Uint32Array(e);h.HEAPF32=B=new Float32Array(e);h.HEAPF64=D=new Float64Array(e);I=h.asm.$d;La.unshift(h.asm._d);Ua("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return $a().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+
f);t(f)})}var d={a:af};Ta("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return va||"function"!==typeof WebAssembly.instantiateStreaming||Xa()||Va("file://")||"function"!==typeof fetch?c(b):fetch(Wa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm._d).apply(null,arguments)};h._toggle_background_color=function(){return(h._toggle_background_color=h.asm.ae).apply(null,arguments)};h._setFade=function(){return(h._setFade=h.asm.be).apply(null,arguments)};h._changePause=function(){return(h._changePause=h.asm.ce).apply(null,arguments)};h._setSpeed=function(){return(h._setSpeed=h.asm.de).apply(null,arguments)};
h._reverseA=function(){return(h._reverseA=h.asm.ee).apply(null,arguments)};h._nextFrame=function(){return(h._nextFrame=h.asm.fe).apply(null,arguments)};h._restart=function(){return(h._restart=h.asm.ge).apply(null,arguments)};h._main=function(){return(h._main=h.asm.he).apply(null,arguments)};
var H=h._malloc=function(){return(H=h._malloc=h.asm.ie).apply(null,arguments)},$e=h.___errno_location=function(){return($e=h.___errno_location=h.asm.je).apply(null,arguments)},fe=h.stackSave=function(){return(fe=h.stackSave=h.asm.ke).apply(null,arguments)},he=h.stackRestore=function(){return(he=h.stackRestore=h.asm.le).apply(null,arguments)},ge=h.stackAlloc=function(){return(ge=h.stackAlloc=h.asm.me).apply(null,arguments)};h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.ne).apply(null,arguments)};
h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.oe).apply(null,arguments)};h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.pe).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.qe).apply(null,arguments)};h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.re).apply(null,arguments)};h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.se).apply(null,arguments)};h.addRunDependency=Ta;h.removeRunDependency=Ua;h.FS_createPath=dc;
h.FS_createDataFile=fc;h.FS_createPreloadedFile=jc;h.FS_createLazyFile=ic;h.FS_createDevice=M;h.FS_unlink=Ub;var bf;function ra(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function cf(){bf||df();bf||(Sa=cf)};
function df(){function a(){if(!bf&&(bf=!0,h.calledRun=!0,!Aa)){h.noFSInit||bc||(bc=!0,ac(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?M("/dev","stdin",h.stdin):Tb("/dev/tty","/dev/stdin"),h.stdout?M("/dev","stdout",null,h.stdout):Tb("/dev/tty","/dev/stdout"),h.stderr?M("/dev","stderr",null,h.stderr):Tb("/dev/tty1","/dev/stderr"),Wb("/dev/stdin",0),Wb("/dev/stdout",1),Wb("/dev/stderr",1));db(La);Cb=!1;db(Ma);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(ef){var b=h._main;try{var c=
b(0,0);Dc(c,!0)}catch(d){d instanceof ra||"unwind"==d||((b=d)&&"object"===typeof d&&d.stack&&(b=[d,d.stack]),k("exception thrown: "+b),ea(1,d))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)b=h.postRun.shift(),Oa.unshift(b);db(Oa)}}if(!(0<Qa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Pa();db(Ka);0<Qa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);
a()},1)):a())}}h.run=df;function Dc(a,b){Ba=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(h.onExit)h.onExit(a);Aa=!0}ea(a,new ra(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ef=!0;h.noInitialRun&&(ef=!1);df();
