
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.Ze||(g.Ze=0);g.Ze++;
(function(a){function b(p,r,q){var u=new XMLHttpRequest;u.open("GET",p,!0);u.responseType="arraybuffer";u.onprogress=function(w){var m=r;w.total&&(m=w.total);if(w.loaded){u.qe?g.Ge[p].loaded=w.loaded:(u.qe=!0,g.Ge||(g.Ge={}),g.Ge[p]={loaded:w.loaded,total:m});var v=m=w=0,x;for(x in g.Ge){var C=g.Ge[x];w+=C.total;m+=C.loaded;v++}w=Math.ceil(w*g.Ze/v);g.setStatus&&g.setStatus("Downloading data... ("+m+"/"+w+")")}else!g.Ge&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
p);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)q(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(p){console.error("package error:",p)}function d(){function p(w,m,v){this.start=w;this.Pe=m;this.audio=v}function r(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);p.prototype.Cf=w;w=a.files;for(var m=0;m<
w.length;++m)p.prototype.qe[w[m].filename].onload();g.removeRunDependency("datafile_index.data")}g.FS_createPath("/","shaders",!0,!0);p.prototype={qe:{},open:function(w,m){this.name=m;this.qe[m]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Bf(this.Cf.subarray(this.start,this.Pe))},Bf:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.qe[this.name]=null}};for(var q=a.files,u=0;u<q.length;++u)(new p(q[u].start,
q[u].end,q[u].audio)).open("GET",q[u].filename);g.addRunDependency("datafile_index.data");g.Ef||(g.Ef={});g.Ef["index.data"]={vg:!1};n?(r(n),n=null):h=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,h=null,n=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;n||b(e,f,function(p){h?(h(p),h=null):n=p},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/shaders/grid.frag",
start:0,end:1377,audio:0},{filename:"/shaders/post.frag",start:1377,end:2718,audio:0},{filename:"/shaders/tiles.frag",start:2718,end:3247,audio:0},{filename:"/shaders/post.vert",start:3247,end:3327,audio:0},{filename:"/shaders/texture.frag",start:3327,end:5110,audio:0},{filename:"/shaders/texture.vert",start:5110,end:5190,audio:0},{filename:"/shaders/grid.vert",start:5190,end:5270,audio:0},{filename:"/shaders/tiles.vert",start:5270,end:5350,audio:0},{filename:"/shaders/post2.frag",start:5350,end:7998,
audio:0}],remote_package_size:7998,package_uuid:"0bca1278-1f4a-427a-9177-4bf7915252c4"});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca="./this.program";function da(a,b){throw b;}var ea=!1,fa=!1,ha=!1,ia=!1;ea="object"===typeof window;fa="function"===typeof importScripts;ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ia=!ea&&!ha&&!fa;var l="",ja,ka,la,ma,oa,pa;
if(ha)l=fa?require("path").dirname(l)+"/":__dirname+"/",ja=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return oa.readFileSync(a,b?null:"utf8")},la=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof qa))throw a;}),process.on("unhandledRejection",
t),da=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ia)"undefined"!=typeof read&&(ja=function(a){return read(a)}),la=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?
printErr:print);else if(ea||fa)fa?l=self.location.href:"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.lastIndexOf("/")+1):"",ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);
d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},ma=function(a){document.title=a};var ra=g.print||console.log.bind(console),k=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);function sa(a){ta||(ta={});ta[a]||(ta[a]=1,k(a))}var ta,ua;g.wasmBinary&&(ua=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;
"object"!==typeof WebAssembly&&t("no native wasm support detected");var va,wa=!1,xa;function assert(a,b){a||t("Assertion failed: "+b)}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?za(z,a,b):""}
function Aa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function A(a,b,c){return Aa(a,z,b,c)}
function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ca(a){var b=Ba(a)+1,c=B(b);c&&Aa(a,D,c,b);return c}var Da,D,z,Ea,Fa,E,Ga,F,Ha,G,Ia=[],Ja=[],Ka=[],La=[],Ma=[];function Na(){var a=g.preRun.shift();Ia.unshift(a)}var Oa=0,Pa=null,Qa=null;function Ra(){Oa++;g.monitorRunDependencies&&g.monitorRunDependencies(Oa)}
function Sa(){Oa--;g.monitorRunDependencies&&g.monitorRunDependencies(Oa);if(0==Oa&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa)){var a=Qa;Qa=null;a()}}g.preloadedImages={};g.preloadedAudios={};function t(a){if(g.onAbort)g.onAbort(a);k(a);wa=!0;xa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ta(a){var b=Ua;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}
function Va(){return Ta("data:application/octet-stream;base64,")}var Ua="index.wasm";if(!Va()){var Wa=Ua;Ua=g.locateFile?g.locateFile(Wa,l):l+Wa}function Xa(){var a=Ua;try{if(a==Ua&&ua)return new Uint8Array(ua);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}
function Ya(){if(!ua&&(ea||fa)){if("function"===typeof fetch&&!Ta("file://"))return fetch(Ua,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ua+"'";return a.arrayBuffer()}).catch(function(){return Xa()});if(ka)return new Promise(function(a,b){ka(Ua,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Xa()})}
var Za,$a,ab={57228:function(){return window.screen.width},57279:function(){return window.screen.height},57333:function(){return 0},57347:function(a,b,c){g.SDL2||(g.SDL2={});var d=g.SDL2;d.If!==g.canvas&&(d.xe=g.createContext(g.canvas,!1,!0),d.If=g.canvas);if(d.w!==a||d.Qf!==b||d.Sf!==d.xe)d.image=d.xe.createImageData(a,b),d.w=a,d.Qf=b,d.Sf=d.xe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=E[b];a[e]=f&255;a[e+1]=f>>
8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.tg!==a&&(d.Jf=new Int32Array(a.buffer),d.Kf=new Uint8Array(a.buffer)),a=d.Jf,c=a.length,a.set(E.subarray(b,b+c)),a=d.Kf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.xe.putImageData(d.image,0,0);return 0},58802:function(a){g.canvas&&(g.canvas.style.cursor=y(a));return 0},58895:function(){g.canvas&&
(g.canvas.style.cursor="none")},58964:function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var n=0,p;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(p=b.length;n<p;){var r=E[e];b[n]=r&255;b[n+1]=r>>8&255;b[n+2]=r>>16&255;b[n+3]=r>>24&255;e++;n+=4}else b=new Int32Array(b.buffer),p=b.length,b.set(E.subarray(e,e+p));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":
"url("+f.toDataURL()+") "+c+" "+d+", auto";d=B(c.length+1);A(c,d,c.length+1);return d},59953:function(a){"undefined"!==typeof ma&&ma(y(a));return 0},60048:function(){return window.innerWidth},60078:function(){return window.innerHeight},60109:function(){return screen.width},60134:function(){return screen.height}};function bb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Pf;"number"===typeof c?void 0===b.Re?G.get(c)():G.get(c)(b.Re):c(void 0===b.Re?null:b.Re)}}}
function cb(a){this.Je=a-16;this.hg=function(b){E[this.Je+8>>2]=b};this.eg=function(b){E[this.Je+0>>2]=b};this.fg=function(){E[this.Je+4>>2]=0};this.dg=function(){D[this.Je+12>>0]=0};this.gg=function(){D[this.Je+13>>0]=0};this.Tf=function(b,c){this.hg(b);this.eg(c);this.fg();this.dg();this.gg()}}var db=0;function eb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";a=fb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){t("randomDevice")}}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],output:[],Ie:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ie.flush(a.tty)},flush:function(a){a.tty.Ie.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ie.sf)throw new H(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Ie.sf(a.tty)}catch(n){throw new H(29);}if(void 0===h&&0===e)throw new H(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ie.df)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.Ie.df(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},pb={sf:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.qe?Buffer.qe(256):new Buffer(256),d=0;try{d=oa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ob(b,!0)}return a.input.shift()},df:function(a,b){null===b||10===b?(ra(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ra(za(a.output,0)),a.output=[])}},qb={df:function(a,b){null===b||10===b?(k(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(za(a.output,0)),a.output=[])}},I={Ae:null,Be:function(){return I.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.Ae||(I.Ae={dir:{node:{De:I.ne.De,te:I.ne.te,lookup:I.ne.lookup,Te:I.ne.Te,rename:I.ne.rename,unlink:I.ne.unlink,rmdir:I.ne.rmdir,readdir:I.ne.readdir,symlink:I.ne.symlink},stream:{Ee:I.oe.Ee}},file:{node:{De:I.ne.De,te:I.ne.te},stream:{Ee:I.oe.Ee,read:I.oe.read,write:I.oe.write,jf:I.oe.jf,xf:I.oe.xf,zf:I.oe.zf}},link:{node:{De:I.ne.De,te:I.ne.te,readlink:I.ne.readlink},stream:{}},nf:{node:{De:I.ne.De,
te:I.ne.te},stream:rb}});c=sb(a,b,c,d);16384===(c.mode&61440)?(c.ne=I.Ae.dir.node,c.oe=I.Ae.dir.stream,c.me={}):32768===(c.mode&61440)?(c.ne=I.Ae.file.node,c.oe=I.Ae.file.stream,c.pe=0,c.me=null):40960===(c.mode&61440)?(c.ne=I.Ae.link.node,c.oe=I.Ae.link.stream):8192===(c.mode&61440)&&(c.ne=I.Ae.nf.node,c.oe=I.Ae.nf.stream);c.timestamp=Date.now();a&&(a.me[b]=c,a.timestamp=c.timestamp);return c},wg:function(a){return a.me?a.me.subarray?a.me.subarray(0,a.pe):new Uint8Array(a.me):new Uint8Array(0)},
pf:function(a,b){var c=a.me?a.me.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.me,a.me=new Uint8Array(b),0<a.pe&&a.me.set(c.subarray(0,a.pe),0))},bg:function(a,b){if(a.pe!=b)if(0==b)a.me=null,a.pe=0;else{var c=a.me;a.me=new Uint8Array(b);c&&a.me.set(c.subarray(0,Math.min(b,a.pe)));a.pe=b}},ne:{De:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.pe:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Hf=4096;b.blocks=Math.ceil(b.size/b.Hf);return b},te:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.bg(a,b.size)},lookup:function(){throw tb[44];},Te:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ub(b,
c)}catch(f){}if(d)for(var e in d.me)throw new H(55);}delete a.parent.me[a.name];a.parent.timestamp=Date.now();a.name=c;b.me[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.me[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=ub(a,b),d;for(d in c.me)throw new H(55);delete a.me[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.me)a.me.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},oe:{read:function(a,b,c,d,e){var f=a.node.me;if(e>=a.node.pe)return 0;a=Math.min(a.node.pe-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.me||a.me.subarray)){if(f)return a.me=b.subarray(c,c+d),a.pe=d;if(0===a.pe&&0===e)return a.me=b.slice(c,c+d),a.pe=d;if(e+d<=a.pe)return a.me.set(b.subarray(c,
c+d),e),d}I.pf(a,e+d);if(a.me.subarray&&b.subarray)a.me.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.me[e+f]=b[c+f];a.pe=Math.max(a.pe,e+d);return d},Ee:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.pe);if(0>b)throw new H(28);return b},jf:function(a,b,c){I.pf(a.node,b+c);a.node.pe=Math.max(a.node.pe,b+c)},xf:function(a,b,c,d,e,f){if(0!==b)throw new H(28);if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.me;if(f&2||a.buffer!==Da){if(0<d||d+c<a.length)a.subarray?
a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=B(f);c<f;)D[b+c++]=0;c=b;if(!c)throw new H(48);D.set(a,c)}else d=!1,c=a.byteOffset;return{Je:c,qg:d}},zf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.oe.write(a,b,0,d,c,!1);return 0}}},vb=null,wb={},xb=[],yb=1,zb=null,Ab=!0,Bb={},H=null,tb={};
function Cb(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={qf:!0,ef:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ef)throw new H(32);a=eb(a.split("/").filter(function(h){return!!h}),!1);var e=vb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=ub(e,a[d]);c=fb(c+"/"+a[d]);e.Oe&&(!f||f&&b.qf)&&(e=e.Oe.root);if(!f||b.$e)for(f=0;40960===(e.mode&61440);)if(e=Db(c),c=jb(gb(c),e),e=Cb(c,{ef:b.ef}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function Eb(a){for(var b;;){if(a===a.parent)return a=a.Be.yf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length}function ub(a,b){var c;if(c=(c=Gb(a,"x"))?c:a.ne.lookup?0:2)throw new H(c,a);for(c=zb[Fb(a.id,b)];c;c=c.He){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ne.lookup(a,b)}
function sb(a,b,c,d){a=new Hb(a,b,c,d);b=Fb(a.parent.id,a.name);a.He=zb[b];return zb[b]=a}var Ib={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Gb(a,b){if(Ab)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Kb(a,b){try{return ub(a,b),20}catch(c){}return Gb(a,"wx")}
function Lb(a){var b=4096;for(a=a||0;a<=b;a++)if(!xb[a])return a;throw new H(33);}function Mb(a,b){Nb||(Nb=function(){},Nb.prototype={});var c=new Nb,d;for(d in a)c[d]=a[d];a=c;b=Lb(b);a.fd=b;return xb[b]=a}var rb={open:function(a){a.oe=wb[a.node.rdev].oe;a.oe.open&&a.oe.open(a)},Ee:function(){throw new H(70);}};function mb(a,b){wb[a]={oe:b}}
function Ob(a,b){var c="/"===b,d=!b;if(c&&vb)throw new H(10);if(!c&&!d){var e=Cb(b,{qf:!1});b=e.path;e=e.node;if(e.Oe)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,Cg:{},yf:b,Zf:[]};a=a.Be(b);a.Be=b;b.root=a;c?vb=a:e&&(e.Oe=b,e.Be&&e.Be.Zf.push(b))}function Pb(a,b,c){var d=Cb(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new H(28);var e=Kb(d,a);if(e)throw new H(e);if(!d.ne.Te)throw new H(63);return d.ne.Te(d,a,b,c)}function J(a){return Pb(a,16895,0)}
function Qb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Pb(a,b|8192,c)}function Rb(a,b){if(!jb(a))throw new H(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new H(44);b=hb(b);var d=Kb(c,b);if(d)throw new H(d);if(!c.ne.symlink)throw new H(63);c.ne.symlink(c,b,a)}
function Sb(a){var b=Cb(a,{parent:!0}).node,c=hb(a),d=ub(b,c);a:{try{var e=ub(b,c)}catch(h){e=h.ye;break a}var f=Gb(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new H(e);if(!b.ne.unlink)throw new H(63);if(d.Oe)throw new H(10);try{Bb.willDeletePath&&Bb.willDeletePath(a)}catch(h){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.ne.unlink(b,c);b=Fb(d.parent.id,d.name);if(zb[b]===d)zb[b]=d.He;else for(b=zb[b];b;){if(b.He===d){b.He=d.He;break}b=b.He}try{if(Bb.onDeletePath)Bb.onDeletePath(a)}catch(h){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Db(a){a=Cb(a).node;if(!a)throw new H(44);if(!a.ne.readlink)throw new H(28);return jb(Eb(a.parent),a.ne.readlink(a))}function Tb(a,b){a="string"===typeof a?Cb(a,{$e:!0}).node:a;if(!a.ne.te)throw new H(63);a.ne.te(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ub(a,b,c,d){if(""===a)throw new H(44);if("string"===typeof b){var e=Ib[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=fb(a);try{f=Cb(a,{$e:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new H(20);}else f=Pb(a,c,0),e=!0;if(!f)throw new H(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new H(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Jb(b)||b&512)?31:Gb(f,Jb(b)):44))throw new H(c);if(b&512){c=f;c="string"===typeof c?Cb(c,{$e:!0}).node:c;if(!c.ne.te)throw new H(63);if(16384===(c.mode&61440))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(e=Gb(c,"w"))throw new H(e);c.ne.te(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Mb({node:f,path:Eb(f),flags:b,seekable:!0,position:0,oe:f.oe,ng:[],error:!1},d);d.oe.open&&d.oe.open(d);!g.logReadFiles||b&1||(Vb||(Vb={}),a in Vb||(Vb[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{Bb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Bb.onOpenFile(a,f))}catch(h){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function Wb(a){if(null===a.fd)throw new H(8);a.af&&(a.af=null);try{a.oe.close&&a.oe.close(a)}catch(b){throw b;}finally{xb[a.fd]=null}a.fd=null}
function Xb(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.oe.Ee)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.oe.Ee(a,b,c);a.ng=[]}
function Yb(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(16384===(a.node.mode&61440))throw new H(31);if(!a.oe.write)throw new H(28);a.seekable&&a.flags&1024&&Xb(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H(70);b=a.oe.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&Bb.onWriteToFile)Bb.onWriteToFile(a.path)}catch(n){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
n.message)}return b}function Zb(){H||(H=function(a,b){this.node=b;this.cg=function(c){this.ye=c};this.cg(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){tb[a]=new H(a);tb[a].stack="<generic error, no stack>"}))}var $b;function ac(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function bc(a,b){a="string"===typeof a?a:Eb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=fb(a+"/"+c);try{J(d)}catch(e){}a=d}}return d}
function cc(a,b,c,d){a=fb(("string"===typeof a?a:Eb(a))+"/"+b);c=ac(c,d);return Pb(a,(void 0!==c?c:438)&4095|32768,0)}function dc(a,b,c,d,e,f){a=b?fb(("string"===typeof a?a:Eb(a))+"/"+b):a;d=ac(d,e);e=Pb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Tb(e,d|146);a=Ub(e,577);Yb(a,c,0,c.length,0,f);Wb(a);Tb(e,d)}return e}
function K(a,b,c,d){a=fb(("string"===typeof a?a:Eb(a))+"/"+b);b=ac(!!c,!!d);K.vf||(K.vf=64);var e=K.vf++<<8|0;mb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,n,p){for(var r=0,q=0;q<p;q++){try{var u=c()}catch(w){throw new H(29);}if(void 0===u&&0===r)throw new H(6);if(null===u||void 0===u)break;r++;h[n+q]=u}r&&(f.node.timestamp=Date.now());return r},write:function(f,h,n,p){for(var r=0;r<p;r++)try{d(h[n+r])}catch(q){throw new H(29);}p&&(f.node.timestamp=
Date.now());return r}});return Qb(a,b,e)}function ec(a){if(!(a.Xf||a.Yf||a.link||a.me)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.me=ob(ja(a.url),!0),a.pe=a.me.length}catch(b){throw new H(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function fc(a,b,c,d,e){function f(){this.bf=!1;this.qe=[]}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var u=q%this.chunkSize;return this.tf(q/this.chunkSize|0)[u]}};f.prototype.Pe=function(q){this.tf=q};f.prototype.lf=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var u=Number(q.getResponseHeader("Content-length")),w,m=(w=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;q=(w=q.getResponseHeader("Content-Encoding"))&&"gzip"===w;var v=1048576;m||(v=u);var x=this;x.Pe(function(C){var X=C*v,na=(C+1)*v-1;na=Math.min(na,u-1);if("undefined"===typeof x.qe[C]){var nc=x.qe;if(X>na)throw Error("invalid range ("+X+", "+na+") or no bytes requested!");if(na>u-1)throw Error("only "+u+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);u!==v&&L.setRequestHeader("Range","bytes="+X+"-"+na);"undefined"!=typeof Uint8Array&&(L.responseType=
"arraybuffer");L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);if(!(200<=L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);X=void 0!==L.response?new Uint8Array(L.response||[]):ob(L.responseText||"",!0);nc[C]=X}if("undefined"===typeof x.qe[C])throw Error("doXHR failed!");return x.qe[C]});if(q||!u)v=u=1,v=u=this.tf(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");this.Gf=
u;this.Ff=v;this.bf=!0};if("undefined"!==typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.bf||this.lf();return this.Gf}},chunkSize:{get:function(){this.bf||this.lf();return this.Ff}}});var n=void 0}else n=c,h=void 0;var p=cc(a,b,d,e);h?p.me=h:n&&(p.me=null,p.url=n);Object.defineProperties(p,{pe:{get:function(){return this.me.length}}});
var r={};Object.keys(p.oe).forEach(function(q){var u=p.oe[q];r[q]=function(){ec(p);return u.apply(null,arguments)}});r.read=function(q,u,w,m,v){ec(p);q=q.node.me;if(v>=q.length)return 0;m=Math.min(q.length-v,m);if(q.slice)for(var x=0;x<m;x++)u[w+x]=q[v+x];else for(x=0;x<m;x++)u[w+x]=q.get(v+x);return m};p.oe=r;return p}
function hc(a,b,c,d,e,f,h,n,p,r){function q(m){function v(C){r&&r();n||dc(a,b,C,d,e,p);f&&f();Sa(w)}var x=!1;g.preloadPlugins.forEach(function(C){!x&&C.canHandle(u)&&(C.handle(m,u,v,function(){h&&h();Sa(w)}),x=!0)});x||v(m)}ic();var u=b?jb(fb(a+"/"+b)):a,w="cp "+u;Ra(w);"string"==typeof c?jc(c,function(m){q(m)},h):q(c)}var kc={},Nb,Vb,lc=void 0;function mc(){lc+=4;return E[lc-4>>2]}function oc(a){a=xb[a];if(!a)throw new H(8);return a}var pc;
ha?pc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?pc=dateNow:pc=function(){return performance.now()};
function qc(a,b){rc=a;sc=b;if(tc)if(uc||(uc=!0),0==a)vc=function(){var d=Math.max(0,wc+b-pc())|0;setTimeout(xc,d)};else if(1==a)vc=function(){yc(xc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);fa?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}vc=function(){setImmediate(xc)}}}
function zc(a,b,c,d,e){function f(){if(h<Ac){if(!noExitRuntime)try{Bc(xa)}catch(n){if(!(n instanceof qa))throw n;}return!1}return!0}assert(!tc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");tc=a;Cc=d;var h=Ac;uc=!1;xc=function(){if(!wa)if(0<Dc.length){var n=Date.now(),p=Dc.shift();p.Pf(p.Re);if(Ec){var r=Ec,q=0==r%1?r-1:Math.floor(r);Ec=p.sg?q:(8*r+(q+.5))/
9}console.log('main loop blocker "'+p.name+'" took '+(Date.now()-n)+" ms");g.setStatus&&(n=g.statusMessage||"Please wait...",p=Ec,r=Fc.ug,p?p<r?g.setStatus(n+" ("+(r-p)+"/"+r+")"):g.setStatus(n):g.setStatus(""));f()&&setTimeout(xc,0)}else f()&&(Gc=Gc+1|0,1==rc&&1<sc&&0!=Gc%sc?vc():(0==rc&&(wc=pc()),wa||g.preMainLoop&&!1===g.preMainLoop()||(Hc(a),g.postMainLoop&&g.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.ag&&SDL.audio.ag(),vc())))};e||(b&&0<b?qc(0,1E3/b):qc(1,1),vc());if(c)throw"unwind";
}function Hc(a){try{a()}catch(b){if(!(b instanceof qa)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&k("exception thrown: "+[b,b.stack]),b;}}var uc=!1,vc=null,Ac=0,tc=null,Cc=0,rc=0,sc=0,Gc=0,Dc=[],Fc={},wc,xc,Ec,Ic=!1,Jc=!1,Kc=[];
function ic(){function a(){Jc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Lc){Lc=!0;try{Mc=!0}catch(c){Mc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Nc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Mc?null:console.log("warning: no BlobBuilder");
Oc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Af||"undefined"!==typeof Oc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Af=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Af&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(Mc)try{h=new Blob([c],{type:Pc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Pc(d)}))}catch(r){sa("Blob constructor present but fails: "+
r+"; falling back to blob builder")}h||(h=new Nc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var n=Oc.createObjectURL(h),p=new Image;p.onload=function(){assert(p.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=p.width;r.height=p.height;r.getContext("2d").drawImage(p,0,0);g.preloadedImages[d]=r;Oc.revokeObjectURL(n);e&&e(c)};p.onerror=function(){console.log("Image "+n+" could not be decoded");f&&f()};p.src=n}});g.preloadPlugins.push({canHandle:function(c){return!g.Bg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(u){p||(p=!0,g.preloadedAudios[d]=u,e&&e(c))}function n(){p||(p=!0,g.preloadedAudios[d]=new Audio,f&&f())}var p=!1;if(Mc){try{var r=new Blob([c],{type:Pc(d)})}catch(u){return n()}r=Oc.createObjectURL(r);var q=new Audio;q.addEventListener("canplaythrough",function(){h(q)},!1);q.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,m=0,
v=0;v<c.length;v++)for(w=w<<8|c[v],m+=8;6<=m;){var x=w>>m-6&63;m-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==m?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==m&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");q.src="data:audio/x-"+d.substr(-3)+";base64,"+u;h(q)}};q.src=r;Qc(function(){h(q)})}else return n()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!Jc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Rc(a,b,c,d){if(b&&g.xe&&a==g.canvas)return g.xe;var e;if(b){var f={antialias:!1,alpha:!1,wf:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof Sc&&(e=Tc(a,f)))var n=M[e].Ce}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof N,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.xe=n,b&&Uc(e),g.og=b,Kc.forEach(function(p){p()}),ic());return n}var Vc=!1,Wc=void 0,Xc=void 0;
function Yc(a,b){function c(){Ic=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Zc,Wc&&d.requestPointerLock(),Ic=!0,Xc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=Ga[SDL.screen>>2]|8388608),$c(g.canvas),ad()):$c(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Xc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=Ga[SDL.screen>>2]&
-8388609),$c(g.canvas),ad()):$c(d));if(g.onFullScreen)g.onFullScreen(Ic);if(g.onFullscreen)g.onFullscreen(Ic)}Wc=a;Xc=b;"undefined"===typeof Wc&&(Wc=!0);"undefined"===typeof Xc&&(Xc=!1);var d=g.canvas;Vc||(Vc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Zc(){if(!Ic)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var bd=0;function yc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===bd)bd=b+1E3/60;else for(;b+2>=bd;)bd+=1E3/60;setTimeout(a,Math.max(bd-b,0))}}function Qc(a){setTimeout(function(){Hc(a)},1E4)}
function Pc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function jc(a,b,c){var d="al "+a;ka(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Sa(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ra(d)}var cd=[];function ad(){var a=g.canvas;cd.forEach(function(b){b(a.width,a.height)})}
function $c(a,b,c){b&&c?(a.pg=b,a.Rf=c):(b=a.pg,c=a.Rf);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Xc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Lc,Mc,Nc,Oc,O=12288,dd=!1,ed=0,fd=0,gd=0,P={alpha:!1,depth:!1,stencil:!1,antialias:!1},hd={},id;function jd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function kd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ld(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var md=1,nd=[],Q=[],od=[],pd=[],qd=[],R=[],S=[],rd=[],M=[],T=[],sd={},td={},ud=4;
function U(a){vd||(vd=a)}function wd(a){for(var b=md++,c=a.length;c<b;c++)a[c]=null;return b}function xd(a,b,c){for(var d="",e=0;e<a;++e){var f=c?E[c+4*e>>2]:-1;d+=y(E[b+4*e>>2],0>f?void 0:f)}return d}function Tc(a,b){a.rf||(a.rf=a.getContext,a.getContext=function(d,e){e=a.rf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?yd(c,b):0}
function yd(a,b){var c=wd(M),d={xg:c,attributes:b,version:b.wf,Ce:a};a.canvas&&(a.canvas.Le=d);M[c]=d;("undefined"===typeof b.Mf||b.Mf)&&zd(d);return c}function Uc(a){Ad=M[a];g.xe=N=Ad&&Ad.Ce}function zd(a){a||(a=Ad);if(!a.Uf){a.Uf=!0;var b=a.Ce;jd(b);kd(b);ld(b);b.ue=b.getExtension("EXT_disjoint_timer_query");b.Ag=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}
function Bd(a){var b=Q[a];a=sd[a]={hf:{},cf:0,Me:-1,Ne:-1};for(var c=a.hf,d=N.getProgramParameter(b,35718),e=0;e<d;++e){var f=N.getActiveUniform(b,e),h=f.name;a.cf=Math.max(a.cf,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var n=N.getUniformLocation(b,h);if(n){var p=wd(R);c[h]=[f.size,p];R[p]=n;for(var r=1;r<f.size;++r)n=N.getUniformLocation(b,h+"["+r+"]"),p=wd(R),R[p]=n}}}var Sc={},vd,Ad,Cd=0;function Dd(){for(var a=V.length-1;0<=a;--a)Ed(a);V=[];W=[]}var W=[];
function Fd(a,b,c){function d(h,n){if(h.length!=n.length)return!1;for(var p in h)if(h[p]!=n[p])return!1;return!0}for(var e in W){var f=W[e];if(f.gf==a&&d(f.kf,c))return}W.push({gf:a,Df:b,kf:c});W.sort(function(h,n){return h.Df<n.Df})}function Gd(a){for(var b=0;b<W.length;++b)W[b].gf==a&&(W.splice(b,1),--b)}function Hd(){if(Cd&&Id.Fe)for(var a=0;a<W.length;++a){var b=W[a];W.splice(a,1);--a;b.gf.apply(null,b.kf)}}var V=[];
function Ed(a){var b=V[a];b.target.removeEventListener(b.re,b.Nf,b.ve);V.splice(a,1)}function Jd(a){function b(d){++Cd;Id=a;Hd();a.ze(d);Hd();--Cd}if(a.we)a.Nf=b,a.target.addEventListener(a.re,b,a.ve),V.push(a),Kd||(La.push(Dd),Kd=!0);else for(var c=0;c<V.length;++c)V[c].target==a.target&&V[c].re==a.re&&Ed(c--)}function Ld(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Md(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Nd={},Kd,Id,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd={},Zd=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Y(a){a=2<a?y(a):a;return Zd[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function $d(a){var b=ae(),c=be(8),d=c+4,e=be(a.id.length+1);A(a.id,e,a.id.length+1);if(a=Y(e))E[c>>2]=a.width,E[d>>2]=a.height;c=[E[c>>2],E[d>>2]];ce(b);return c}function de(a,b,c){a=Y(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function ee(a,b,c){if(a.rg){var d=ae(),e=be(a.id.length+1);A(a.id,e,a.id.length+1);de(e,b,c);ce(d)}else a.width=b,a.height=c}
function fe(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ee(a,d,e),a.style.width=f,a.style.height=h,a.style.backgroundColor=n,p||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=p,a.style.paddingLeft=r,a.style.paddingRight=q,a.style.paddingTop=u,a.style.paddingBottom=w,a.style.marginLeft=m,a.style.marginRight=
v,a.style.marginTop=x,a.style.marginBottom=C,document.body.style.margin=X,document.documentElement.style.overflow=na,document.body.scroll=nc,a.style.uf=L,a.Le&&a.Le.Ce.viewport(0,0,d,e),Yd.Se&&G.get(Yd.Se)(37,0,Yd.mf))}var c=$d(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,n=a.style.backgroundColor,p=document.body.style.backgroundColor,r=a.style.paddingLeft,q=a.style.paddingRight,u=a.style.paddingTop,w=a.style.paddingBottom,m=a.style.marginLeft,v=a.style.marginRight,x=a.style.marginTop,C=a.style.marginBottom,
X=document.body.style.margin,na=document.documentElement.style.overflow,nc=document.body.scroll,L=a.style.uf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function ge(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function he(a){return 0>Zd.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function ie(a,b){if(0!=b.ff||0!=b.Ye){fe(a);var c=b.ig?innerWidth:screen.width,d=b.ig?innerHeight:screen.height,e=he(a),f=e.width;e=e.height;var h=$d(a),n=h[0];h=h[1];3==b.ff?(ge(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.ff&&(c*h<n*d?(f=h*c/n,ge(a,(d-f)/2,0),d=f):(f=n*d/h,ge(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Of&&(a.style.uf="pixelated");
f=2==b.Ye?devicePixelRatio:1;0!=b.Ye&&(c=c*f|0,d=d*f|0,ee(a,c,d),a.Le&&a.Le.Ce.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Md()?-3:-1;Yd=b;b.Se&&G.get(b.Se)(37,0,b.mf);return 0}function je(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Ue)a.Ue();else return document.body.requestPointerLock||document.body.Ue?-3:-1;return 0}var ke=[];
function le(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),h=f&&wd(d);f?(f.name=h,d[h]=f):U(1282);E[b+4*e>>2]=h}}function me(a,b,c,d,e,f,h,n){b=Q[b];if(a=N[a](b,c))d=n&&A(a.name,n,d),e&&(E[e>>2]=d),f&&(E[f>>2]=a.size),h&&(E[h>>2]=a.type)}function ne(a,b){Ga[a>>2]=b;Ga[a+4>>2]=(b-Ga[a>>2])/4294967296}
function oe(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:E[b+4*a>>2]=e[a];break;case 2:F[b+4*a>>2]=e[a];break;case 4:D[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:U(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:ne(b,
d);break;case 0:E[b>>2]=d;break;case 2:F[b>>2]=d;break;case 4:D[b>>0]=d?1:0}}else U(1281)}function pe(a){var b=Ba(a)+1,c=B(b);A(a,c,b);return c}function qe(a,b,c,d){if(c)if(a=N.getUniform(Q[a],R[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:E[c>>2]=a;break;case 2:F[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:E[c+4*b>>2]=a[b];break;case 2:F[c+4*b>>2]=a[b]}else U(1281)}
function re(a,b,c,d){if(c)if(a=N.getVertexAttrib(a,b),34975==b)E[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:E[c>>2]=a;break;case 2:F[c>>2]=a;break;case 5:E[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:E[c+4*b>>2]=a[b];break;case 2:F[c+4*b>>2]=a[b];break;case 5:E[c+4*b>>2]=Math.fround(a[b])}else U(1281)}
function se(a,b,c,d,e){a-=5120;a=1==a?z:4==a?E:6==a?F:5==a||28922==a?Ga:Fa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=ud;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var te=[],ue=[];function ve(a,b){if(!Md())return-1;a=Y(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Cd&&Id.Fe?ie(a,b):b.Lf?(Fd(ie,1,[a,b]),1):-2:-3:-4}
function we(a,b){var c={target:Y(2),re:"beforeunload",we:b,ze:function(d){d=d||event;var e=G.get(b)(28,0,a);e&&(e=y(e));if(e)return d.preventDefault(),d.returnValue=e},ve:!0};Jd(c)}function xe(a,b,c,d,e,f){Od||(Od=B(256));a={target:Y(a),re:f,we:d,ze:function(h){h=h||event;var n=h.target.id?h.target.id:"",p=Od;A(Ld(h.target),p+0,128);A(n,p+128,128);G.get(d)(e,p,b)&&h.preventDefault()},ve:c};Jd(a)}
function ye(a,b,c,d,e){Qd||(Qd=B(280));Jd({target:a,re:e,we:d,ze:function(f){f=f||event;var h=Qd,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!n;E[h>>2]=p;E[h+4>>2]=Md();var r=p?n:Pd,q=r&&r.id?r.id:"";A(Ld(r),h+8,128);A(q,h+136,128);E[h+264>>2]=r?r.clientWidth:0;E[h+268>>2]=r?r.clientHeight:0;E[h+272>>2]=screen.width;E[h+276>>2]=screen.height;p&&(Pd=n);G.get(d)(19,h,b)&&f.preventDefault()},ve:c})}
function ze(a,b,c,d,e,f){Rd||(Rd=B(164));a={target:Y(a),Fe:!0,re:f,we:d,ze:function(h){var n=Rd,p=n>>2;E[p]=h.location;E[p+1]=h.ctrlKey;E[p+2]=h.shiftKey;E[p+3]=h.altKey;E[p+4]=h.metaKey;E[p+5]=h.repeat;E[p+6]=h.charCode;E[p+7]=h.keyCode;E[p+8]=h.which;A(h.key||"",n+36,32);A(h.code||"",n+68,32);A(h.char||"",n+100,32);A(h.locale||"",n+132,32);G.get(d)(e,n,b)&&h.preventDefault()},ve:c};Jd(a)}
function Ae(a,b,c){a>>=2;E[a]=b.screenX;E[a+1]=b.screenY;E[a+2]=b.clientX;E[a+3]=b.clientY;E[a+4]=b.ctrlKey;E[a+5]=b.shiftKey;E[a+6]=b.altKey;E[a+7]=b.metaKey;Ea[2*a+16]=b.button;Ea[2*a+17]=b.buttons;E[a+9]=b.movementX;E[a+10]=b.movementY;c=he(c);E[a+11]=b.clientX-c.left;E[a+12]=b.clientY-c.top}function Be(a,b,c,d,e,f){Sd||(Sd=B(64));a=Y(a);Jd({target:a,Fe:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,re:f,we:d,ze:function(h){h=h||event;Ae(Sd,h,a);G.get(d)(e,Sd,b)&&h.preventDefault()},ve:c})}
function Ce(a,b,c,d,e){Td||(Td=B(260));Jd({target:a,re:e,we:d,ze:function(f){f=f||event;var h=Td,n=document.pointerLockElement||document.Pe||document.Cf||document.Bf;E[h>>2]=!!n;var p=n&&n.id?n.id:"";A(Ld(n),h+4,128);A(p,h+132,128);G.get(d)(20,h,b)&&f.preventDefault()},ve:c})}
function De(a,b,c,d){Ud||(Ud=B(36));a=Y(a);Jd({target:a,re:"resize",we:d,ze:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var h=Ud;E[h>>2]=e.detail;E[h+4>>2]=f.clientWidth;E[h+8>>2]=f.clientHeight;E[h+12>>2]=innerWidth;E[h+16>>2]=innerHeight;E[h+20>>2]=outerWidth;E[h+24>>2]=outerHeight;E[h+28>>2]=pageXOffset;E[h+32>>2]=pageYOffset;G.get(d)(10,h,b)&&e.preventDefault()}}},ve:c})}
function Ee(a,b,c,d,e,f){Vd||(Vd=B(1684));a=Y(a);Jd({target:a,Fe:"touchstart"==f||"touchend"==f,re:f,we:d,ze:function(h){for(var n={},p=h.touches,r=0;r<p.length;++r){var q=p[r];n[q.identifier]=q}p=h.changedTouches;for(r=0;r<p.length;++r)q=p[r],q.Wf=1,n[q.identifier]=q;p=h.targetTouches;for(r=0;r<p.length;++r)n[p[r].identifier].$f=1;p=Vd;q=p>>2;E[q+1]=h.ctrlKey;E[q+2]=h.shiftKey;E[q+3]=h.altKey;E[q+4]=h.metaKey;q+=5;var u=he(a),w=0;for(r in n){var m=n[r];E[q]=m.identifier;E[q+1]=m.screenX;E[q+2]=m.screenY;
E[q+3]=m.clientX;E[q+4]=m.clientY;E[q+5]=m.pageX;E[q+6]=m.pageY;E[q+7]=m.Wf;E[q+8]=m.$f;E[q+9]=m.clientX-u.left;E[q+10]=m.clientY-u.top;q+=13;if(31<++w)break}E[p>>2]=w;G.get(d)(e,p,b)&&h.preventDefault()},ve:c})}function Fe(a,b,c){var d=Zd[1];Wd||(Wd=B(8));Jd({target:d,re:"visibilitychange",we:c,ze:function(e){e=e||event;var f=Wd,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);E[f>>2]=document.hidden;E[f+4>>2]=h;G.get(c)(21,f,a)&&e.preventDefault()},ve:b})}
function Ge(a,b,c,d){Xd||(Xd=B(96));Jd({target:a,Fe:!0,re:"wheel",we:d,ze:function(e){e=e||event;var f=Xd;Ae(f,e,a);Ha[f+64>>3]=e.deltaX;Ha[f+72>>3]=e.deltaY;Ha[f+80>>3]=e.deltaZ;E[f+88>>2]=e.deltaMode;G.get(d)(9,f,b)&&e.preventDefault()},ve:c})}var He={};
function Ie(){if(!Je){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in He)a[b]=He[b];var c=[];for(b in a)c.push(b+"="+a[b]);Je=c}return Je}var Je;function Ke(a){return 0===a%4&&(0!==a%100||0===a%400)}function Le(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Me=[31,29,31,30,31,30,31,31,30,31,30,31],Ne=[31,28,31,30,31,30,31,31,30,31,30,31];function Oe(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ke(a.getFullYear())?Me:Ne)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Pe(a,b,c,d){function e(m,v,x){for(m="number"===typeof m?m.toString():m||"";m.length<v;)m=x[0]+m;return m}function f(m,v){return e(m,v,"0")}function h(m,v){function x(X){return 0>X?-1:0<X?1:0}var C;0===(C=x(m.getFullYear()-v.getFullYear()))&&0===(C=x(m.getMonth()-v.getMonth()))&&(C=x(m.getDate()-v.getDate()));return C}function n(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function p(m){m=Oe(new Date(m.se+1900,0,1),m.Xe);var v=new Date(m.getFullYear()+1,0,4),x=n(new Date(m.getFullYear(),0,4));v=n(v);return 0>=h(x,m)?0>=h(v,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var r=E[d+40>>2];d={lg:E[d>>2],kg:E[d+4>>2],Ve:E[d+8>>2],Qe:E[d+12>>2],Ke:E[d+16>>2],se:E[d+20>>2],We:E[d+24>>2],Xe:E[d+28>>2],Dg:E[d+32>>2],jg:E[d+
36>>2],mg:r?y(r):""};c=y(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in r)c=c.replace(new RegExp(q,"g"),r[q]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");r={"%a":function(m){return u[m.We].substring(0,3)},"%A":function(m){return u[m.We]},"%b":function(m){return w[m.Ke].substring(0,3)},"%B":function(m){return w[m.Ke]},"%C":function(m){return f((m.se+1900)/100|0,2)},"%d":function(m){return f(m.Qe,2)},"%e":function(m){return e(m.Qe,2," ")},"%g":function(m){return p(m).toString().substring(2)},"%G":function(m){return p(m)},"%H":function(m){return f(m.Ve,
2)},"%I":function(m){m=m.Ve;0==m?m=12:12<m&&(m-=12);return f(m,2)},"%j":function(m){return f(m.Qe+Le(Ke(m.se+1900)?Me:Ne,m.Ke-1),3)},"%m":function(m){return f(m.Ke+1,2)},"%M":function(m){return f(m.kg,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.Ve&&12>m.Ve?"AM":"PM"},"%S":function(m){return f(m.lg,2)},"%t":function(){return"\t"},"%u":function(m){return m.We||7},"%U":function(m){var v=new Date(m.se+1900,0,1),x=0===v.getDay()?v:Oe(v,7-v.getDay());m=new Date(m.se+1900,m.Ke,m.Qe);return 0>
h(x,m)?f(Math.ceil((31-x.getDate()+(Le(Ke(m.getFullYear())?Me:Ne,m.getMonth()-1)-31)+m.getDate())/7),2):0===h(x,v)?"01":"00"},"%V":function(m){var v=new Date(m.se+1901,0,4),x=n(new Date(m.se+1900,0,4));v=n(v);var C=Oe(new Date(m.se+1900,0,1),m.Xe);return 0>h(C,x)?"53":0>=h(v,C)?"01":f(Math.ceil((x.getFullYear()<m.se+1900?m.Xe+32-x.getDate():m.Xe+1-x.getDate())/7),2)},"%w":function(m){return m.We},"%W":function(m){var v=new Date(m.se,0,1),x=1===v.getDay()?v:Oe(v,0===v.getDay()?1:7-v.getDay()+1);m=
new Date(m.se+1900,m.Ke,m.Qe);return 0>h(x,m)?f(Math.ceil((31-x.getDate()+(Le(Ke(m.getFullYear())?Me:Ne,m.getMonth()-1)-31)+m.getDate())/7),2):0===h(x,v)?"01":"00"},"%y":function(m){return(m.se+1900).toString().substring(2)},"%Y":function(m){return m.se+1900},"%z":function(m){m=m.jg;var v=0<=m;m=Math.abs(m)/60;return(v?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.mg},"%%":function(){return"%"}};for(q in r)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),r[q](d)));q=
ob(c,!1);if(q.length>b)return 0;D.set(q,a);return q.length-1}var Qe=[];function Hb(a,b,c,d){a||(a=this);this.parent=a;this.Be=a.Be;this.Oe=null;this.id=yb++;this.name=b;this.mode=c;this.ne={};this.oe={};this.rdev=d}
Object.defineProperties(Hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Yf:{get:function(){return 16384===(this.mode&61440)}},Xf:{get:function(){return 8192===(this.mode&61440)}}});Zb();zb=Array(4096);Ob(I,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");mb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Qb("/dev/null",259);lb(1280,pb);lb(1536,qb);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);var a=ib();K("/dev","random",a);K("/dev","urandom",a);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Ob({Be:function(){var b=sb(a,"fd",16895,73);b.ne={lookup:function(c,d){var e=xb[+d];if(!e)throw new H(8);c={parent:null,Be:{yf:"fake"},ne:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=bc;g.FS_createDataFile=dc;g.FS_createPreloadedFile=hc;g.FS_createLazyFile=fc;g.FS_createDevice=K;g.FS_unlink=Sb;g.requestFullscreen=function(a,b){Yc(a,b)};g.requestAnimationFrame=function(a){yc(a)};
g.setCanvasSize=function(a,b,c){$c(g.canvas,a,b);c||ad()};g.pauseMainLoop=function(){vc=null;Ac++};g.resumeMainLoop=function(){Ac++;var a=rc,b=sc,c=tc;tc=null;zc(c,0,!1,Cc,!0);qc(a,b);vc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Rc(a,b,c,d)};for(var N,Z=0;32>Z;++Z)ke.push(Array(Z));var Re=new Float32Array(288);
for(Z=0;288>Z;++Z)te[Z]=Re.subarray(0,Z+1);var Se=new Int32Array(288);for(Z=0;288>Z;++Z)ue[Z]=Se.subarray(0,Z+1);function ob(a,b){var c=Array(Ba(a)+1);a=Aa(a,c,0,c.length);b&&(c.length=a);return c}
var Ue={ba:function(a){return B(a+16)+16},aa:function(a,b,c){(new cb(a)).Tf(b,c);db++;throw a;},V:function(a,b,c){lc=c;try{var d=oc(a);switch(b){case 0:var e=mc();return 0>e?-28:Ub(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=mc(),d.flags|=e,0;case 12:return e=mc(),Ea[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return E[Te()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof kc&&f instanceof H||t(f),-f.ye}},Ya:function(a,
b,c){lc=c;try{var d=oc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=mc();return E[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=mc();if(!d.oe.Vf)throw new H(59);return d.oe.Vf(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:t("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof kc&&f instanceof H||t(f),-f.ye}},Za:function(a,
b,c){lc=c;try{var d=y(a),e=c?mc():0;return Ub(d,b,e).fd}catch(f){return"undefined"!==typeof kc&&f instanceof H||t(f),-f.ye}},U:function(){t()},d:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=pc();else return E[Te()>>2]=28,-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0},t:function(){t("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},wa:function(a){if(12448==a)return O=12288,1;O=12300;return 0},Ha:function(a,
b,c,d,e){if(62E3!=a)O=12296,c=0;else{if(b)for(;;){a=E[b>>2];if(12321==a)P.alpha=0<E[b+4>>2];else if(12325==a)P.depth=0<E[b+4>>2];else if(12326==a)P.stencil=0<E[b+4>>2];else if(12337==a)a=E[b+4>>2],P.antialias=0<a;else if(12338==a)a=E[b+4>>2],P.antialias=1==a;else if(12544==a)P.yg=12547!=E[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(E[e>>2]=1),c&&0<d&&(E[c>>2]=62002),O=12288,c=1):(O=12300,c=0)}return c},Fa:function(a,b,c,d){if(62E3!=a)return O=12296,0;for(a=1;;){b=E[d>>2];if(12440==b)a=E[d+4>>
2];else if(12344==b)break;else return O=12292,0;d+=8}if(2!=a)return O=12293,0;P.wf=a-1;P.zg=0;id=Tc(g.canvas,P);if(0!=id)return O=12288,Uc(id),g.og=!0,Kc.forEach(function(e){e()}),Uc(null),62004;O=12297;return 0},Da:function(a,b){if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;O=12288;return 62006},Ea:function(a,b){if(62E3!=a)return O=12296,0;if(62004!=b)return O=12294,0;a=id;Ad===M[a]&&(Ad=null);if("object"===typeof Nd)for(var c=M[a].Ce.canvas,d=0;d<V.length;++d)V[d].target!=c||Ed(d--);
M[a]&&M[a].Ce.canvas&&(M[a].Ce.canvas.Le=void 0);M[a]=null;O=12288;ed==b&&(ed=0);return 1},Ca:function(a,b){if(62E3!=a)return O=12296,0;if(62006!=b)return O=12301,1;fd==b&&(fd=0);gd==b&&(gd=0);O=12288;return 1},Ga:function(a,b,c,d){if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;if(!d)return O=12300,0;O=12288;switch(c){case 12320:return E[d>>2]=P.alpha?32:24,1;case 12321:return E[d>>2]=P.alpha?8:0,1;case 12322:return E[d>>2]=8,1;case 12323:return E[d>>2]=8,1;case 12324:return E[d>>2]=8,1;
case 12325:return E[d>>2]=P.depth?24:0,1;case 12326:return E[d>>2]=P.stencil?8:0,1;case 12327:return E[d>>2]=12344,1;case 12328:return E[d>>2]=62002,1;case 12329:return E[d>>2]=0,1;case 12330:return E[d>>2]=4096,1;case 12331:return E[d>>2]=16777216,1;case 12332:return E[d>>2]=4096,1;case 12333:return E[d>>2]=0,1;case 12334:return E[d>>2]=0,1;case 12335:return E[d>>2]=12344,1;case 12337:return E[d>>2]=P.antialias?4:0,1;case 12338:return E[d>>2]=P.antialias?1:0,1;case 12339:return E[d>>2]=4,1;case 12340:return E[d>>
2]=12344,1;case 12341:case 12342:case 12343:return E[d>>2]=-1,1;case 12345:case 12346:return E[d>>2]=0,1;case 12347:return E[d>>2]=0,1;case 12348:return E[d>>2]=1;case 12349:case 12350:return E[d>>2]=0,1;case 12351:return E[d>>2]=12430,1;case 12352:return E[d>>2]=4,1;case 12354:return E[d>>2]=0,1;default:return O=12292,0}},Q:function(){O=12288;return 62E3},ua:function(){return O},Ja:function(a,b,c){if(62E3==a)return b&&(E[b>>2]=1),c&&(E[c>>2]=4),dd=!0,O=12288,1;O=12296;return 0},Ba:function(a,b,c,
d){if(62E3!=a)return O=12296,0;if(0!=d&&62004!=d)return O=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return O=12301,0;Uc(d?id:null);ed=d;gd=b;fd=c;O=12288;return 1},va:function(a,b){if(62E3!=a)return O=12296,0;O=12288;if(hd[b])return hd[b];switch(b){case 12371:a=Ca("Emscripten");break;case 12372:a=Ca("1.4 Emscripten EGL");break;case 12373:a=Ca("");break;case 12429:a=Ca("OpenGL_ES");break;default:return O=12300,0}return hd[b]=a},Aa:function(){if(dd)if(g.xe)if(g.xe.isContextLost())O=12302;else return O=
12288,1;else O=12290;else O=12289;return 0},za:function(a,b){if(62E3!=a)return O=12296,0;0==b?qc(0,0):qc(1,b);O=12288;return 1},Ia:function(a){if(62E3!=a)return O=12296,0;gd=fd=ed=0;dd=!1;O=12288;return 1},xa:function(){O=12288;return 1},ya:function(){O=12288;return 1},a:function(a,b,c){Qe.length=0;var d;for(c>>=2;d=z[b++];)(d=105>d)&&c&1&&c++,Qe.push(d?Ha[c++>>1]:E[c]),++c;return ab[a].apply(null,Qe)},sa:function(){vc=null;Ac++;tc=null},pa:function(){if(!Md())return-1;Gd(ie);var a=Zd[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ta:function(){Gd(je);if(document.exitPointerLock)document.exitPointerLock();else if(document.qe)document.qe();else return-1;return 0},l:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},f:function(a,b,c){a=Y(a);if(!a)return-4;a=he(a);Ha[b>>3]=a.width;Ha[c>>3]=a.height;return 0},j:pc,Md:function(a){N.activeTexture(a)},Ld:function(a,b){N.attachShader(Q[a],
S[b])},ka:function(a,b){N.ue.beginQueryEXT(a,T[b])},Kd:function(a,b,c){N.bindAttribLocation(Q[a],b,y(c))},Id:function(a,b){N.bindBuffer(a,nd[b])},Hd:function(a,b){N.bindFramebuffer(a,od[b])},Gd:function(a,b){N.bindRenderbuffer(a,pd[b])},Fd:function(a,b){N.bindTexture(a,qd[b])},ca:function(a){N.bindVertexArray(rd[a])},Ed:function(a,b,c,d){N.blendColor(a,b,c,d)},Dd:function(a){N.blendEquation(a)},Cd:function(a,b){N.blendEquationSeparate(a,b)},Bd:function(a,b){N.blendFunc(a,b)},Ad:function(a,b,c,d){N.blendFuncSeparate(a,
b,c,d)},zd:function(a,b,c,d){N.bufferData(a,c?z.subarray(c,c+b):b,d)},yd:function(a,b,c,d){N.bufferSubData(a,b,z.subarray(d,d+c))},xd:function(a){return N.checkFramebufferStatus(a)},wd:function(a){N.clear(a)},vd:function(a,b,c,d){N.clearColor(a,b,c,d)},ud:function(a){N.clearDepth(a)},td:function(a){N.clearStencil(a)},sd:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},rd:function(a){N.compileShader(S[a])},qd:function(a,b,c,d,e,f,h,n){N.compressedTexImage2D(a,b,c,d,e,f,n?z.subarray(n,n+h):null)},pd:function(a,
b,c,d,e,f,h,n,p){N.compressedTexSubImage2D(a,b,c,d,e,f,h,p?z.subarray(p,p+n):null)},od:function(a,b,c,d,e,f,h,n){N.copyTexImage2D(a,b,c,d,e,f,h,n)},nd:function(a,b,c,d,e,f,h,n){N.copyTexSubImage2D(a,b,c,d,e,f,h,n)},md:function(){var a=wd(Q),b=N.createProgram();b.name=a;Q[a]=b;return a},ld:function(a){var b=wd(S);S[b]=N.createShader(a);return b},kd:function(a){N.cullFace(a)},jd:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=nd[d];e&&(N.deleteBuffer(e),e.name=0,nd[d]=null)}},id:function(a,b){for(var c=
0;c<a;++c){var d=E[b+4*c>>2],e=od[d];e&&(N.deleteFramebuffer(e),e.name=0,od[d]=null)}},hd:function(a){if(a){var b=Q[a];b?(N.deleteProgram(b),b.name=0,Q[a]=null,sd[a]=null):U(1281)}},na:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=T[d];e&&(N.ue.deleteQueryEXT(e),T[d]=null)}},gd:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],e=pd[d];e&&(N.deleteRenderbuffer(e),e.name=0,pd[d]=null)}},fd:function(a){if(a){var b=S[a];b?(N.deleteShader(b),S[a]=null):U(1281)}},ed:function(a,b){for(var c=
0;c<a;c++){var d=E[b+4*c>>2],e=qd[d];e&&(N.deleteTexture(e),e.name=0,qd[d]=null)}},Td:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2];N.deleteVertexArray(rd[d]);rd[d]=null}},dd:function(a){N.depthFunc(a)},cd:function(a){N.depthMask(!!a)},bd:function(a,b){N.depthRange(a,b)},ad:function(a,b){N.detachShader(Q[a],S[b])},$c:function(a){N.disable(a)},_c:function(a){N.disableVertexAttribArray(a)},Zc:function(a,b,c){N.drawArrays(a,b,c)},Pd:function(a,b,c,d){N.drawArraysInstanced(a,b,c,d)},Qd:function(a,
b){for(var c=ke[a],d=0;d<a;d++)c[d]=E[b+4*d>>2];N.drawBuffers(c)},Yc:function(a,b,c,d){N.drawElements(a,b,c,d)},Od:function(a,b,c,d,e){N.drawElementsInstanced(a,b,c,d,e)},Xc:function(a){N.enable(a)},Wc:function(a){N.enableVertexAttribArray(a)},ja:function(a){N.ue.endQueryEXT(a)},Vc:function(){N.finish()},Uc:function(){N.flush()},Tc:function(a,b,c,d){N.framebufferRenderbuffer(a,b,c,pd[d])},Sc:function(a,b,c,d,e){N.framebufferTexture2D(a,b,c,qd[d],e)},Rc:function(a){N.frontFace(a)},Qc:function(a,b){le(a,
b,"createBuffer",nd)},Oc:function(a,b){le(a,b,"createFramebuffer",od)},oa:function(a,b){for(var c=0;c<a;c++){var d=N.ue.createQueryEXT();if(!d){for(U(1282);c<a;)E[b+4*c++>>2]=0;break}var e=wd(T);d.name=e;T[e]=d;E[b+4*c>>2]=e}},Nc:function(a,b){le(a,b,"createRenderbuffer",pd)},Mc:function(a,b){le(a,b,"createTexture",qd)},Sd:function(a,b){le(a,b,"createVertexArray",rd)},Pc:function(a){N.generateMipmap(a)},Lc:function(a,b,c,d,e,f,h){me("getActiveAttrib",a,b,c,d,e,f,h)},Kc:function(a,b,c,d,e,f,h){me("getActiveUniform",
a,b,c,d,e,f,h)},Jc:function(a,b,c,d){a=N.getAttachedShaders(Q[a]);var e=a.length;e>b&&(e=b);E[c>>2]=e;for(b=0;b<e;++b)E[d+4*b>>2]=S.indexOf(a[b])},Ic:function(a,b){return N.getAttribLocation(Q[a],y(b))},Hc:function(a,b){oe(a,b,4)},Gc:function(a,b,c){c?E[c>>2]=N.getBufferParameter(a,b):U(1281)},Fc:function(){var a=N.getError()||vd;vd=0;return a},Ec:function(a,b){oe(a,b,2)},Dc:function(a,b,c,d){a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=
a.name|0;E[d>>2]=a},Bc:function(a,b){oe(a,b,0)},zc:function(a,b,c,d){a=N.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(E[c>>2]=b)},Ac:function(a,b,c){if(c)if(a>=md)U(1281);else{var d=sd[a];if(d)if(35716==b)a=N.getProgramInfoLog(Q[a]),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b)E[c>>2]=d.cf;else if(35722==b){if(-1==d.Me){a=Q[a];var e=N.getProgramParameter(a,35721);for(b=d.Me=0;b<e;++b)d.Me=Math.max(d.Me,N.getActiveAttrib(a,b).name.length+1)}E[c>>
2]=d.Me}else if(35381==b){if(-1==d.Ne)for(a=Q[a],e=N.getProgramParameter(a,35382),b=d.Ne=0;b<e;++b)d.Ne=Math.max(d.Ne,N.getActiveUniformBlockName(a,b).length+1);E[c>>2]=d.Ne}else E[c>>2]=N.getProgramParameter(Q[a],b);else U(1282)}else U(1281)},ea:function(a,b,c){if(c){a=N.ue.getQueryObjectEXT(T[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;ne(c,d)}else U(1281)},ga:function(a,b,c){if(c){a=N.ue.getQueryObjectEXT(T[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;E[c>>2]=d}else U(1281)},da:function(a,b,c){if(c){a=
N.ue.getQueryObjectEXT(T[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;ne(c,d)}else U(1281)},fa:function(a,b,c){if(c){a=N.ue.getQueryObjectEXT(T[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;E[c>>2]=d}else U(1281)},ha:function(a,b,c){c?E[c>>2]=N.ue.getQueryEXT(a,b):U(1281)},yc:function(a,b,c){c?E[c>>2]=N.getRenderbufferParameter(a,b):U(1281)},wc:function(a,b,c,d){a=N.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(E[c>>2]=b)},vc:function(a,b,c,d){a=N.getShaderPrecisionFormat(a,
b);E[c>>2]=a.rangeMin;E[c+4>>2]=a.rangeMax;E[d>>2]=a.precision},uc:function(a,b,c,d){if(a=N.getShaderSource(S[a]))b=0<b&&d?A(a,d,b):0,c&&(E[c>>2]=b)},xc:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(S[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=N.getShaderParameter(S[a],b):U(1281)},tc:function(a){if(td[a])return td[a];switch(a){case 7939:var b=N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+
d}));b=pe(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||U(1280);b=pe(b);break;case 7938:b=pe("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=pe(b);break;default:return U(1280),0}return td[a]=b},sc:function(a,b,c){c?F[c>>2]=N.getTexParameter(a,b):U(1281)},qc:function(a,b,c){c?E[c>>2]=
N.getTexParameter(a,b):U(1281)},nc:function(a,b){b=y(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=sd[a]&&sd[a].hf[b])&&0<=c&&c<a[0]?a[1]+c:-1},pc:function(a,b,c){qe(a,b,c,2)},oc:function(a,b,c){qe(a,b,c,0)},kc:function(a,b,c){c?E[c>>2]=N.getVertexAttribOffset(a,b):U(1281)},mc:function(a,b,c){re(a,b,c,2)},lc:function(a,b,c){re(a,b,c,5)},jc:function(a,b){N.hint(a,b)},ic:function(a){return(a=nd[a])?N.isBuffer(a):0},hc:function(a){return N.isEnabled(a)},
fc:function(a){return(a=od[a])?N.isFramebuffer(a):0},ec:function(a){return(a=Q[a])?N.isProgram(a):0},la:function(a){return(a=T[a])?N.ue.isQueryEXT(a):0},dc:function(a){return(a=pd[a])?N.isRenderbuffer(a):0},cc:function(a){return(a=S[a])?N.isShader(a):0},bc:function(a){return(a=qd[a])?N.isTexture(a):0},Rd:function(a){return(a=rd[a])?N.isVertexArray(a):0},ac:function(a){N.lineWidth(a)},$b:function(a){N.linkProgram(Q[a]);Bd(a)},_b:function(a,b){3317==a&&(ud=b);N.pixelStorei(a,b)},Zb:function(a,b){N.polygonOffset(a,
b)},ia:function(a,b){N.ue.queryCounterEXT(T[a],b)},Yb:function(a,b,c,d,e,f,h){(h=se(f,e,c,d,h))?N.readPixels(a,b,c,d,e,f,h):U(1280)},Wb:function(){},Vb:function(a,b,c,d){N.renderbufferStorage(a,b,c,d)},Ub:function(a,b){N.sampleCoverage(a,!!b)},Tb:function(a,b,c,d){N.scissor(a,b,c,d)},Sb:function(){U(1280)},Rb:function(a,b,c,d){b=xd(b,c,d);N.shaderSource(S[a],b)},Qb:function(a,b,c){N.stencilFunc(a,b,c)},Pb:function(a,b,c,d){N.stencilFuncSeparate(a,b,c,d)},Ob:function(a){N.stencilMask(a)},Nb:function(a,
b){N.stencilMaskSeparate(a,b)},Mb:function(a,b,c){N.stencilOp(a,b,c)},Lb:function(a,b,c,d){N.stencilOpSeparate(a,b,c,d)},Kb:function(a,b,c,d,e,f,h,n,p){N.texImage2D(a,b,c,d,e,f,h,n,p?se(n,h,d,e,p):null)},Jb:function(a,b,c){N.texParameterf(a,b,c)},Ib:function(a,b,c){N.texParameterf(a,b,F[c>>2])},Hb:function(a,b,c){N.texParameteri(a,b,c)},Gb:function(a,b,c){N.texParameteri(a,b,E[c>>2])},Fb:function(a,b,c,d,e,f,h,n,p){var r=null;p&&(r=se(n,h,e,f,p));N.texSubImage2D(a,b,c,d,e,f,h,n,r)},Eb:function(a,
b){N.uniform1f(R[a],b)},Db:function(a,b,c){if(288>=b)for(var d=te[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);N.uniform1fv(R[a],d)},Cb:function(a,b){N.uniform1i(R[a],b)},Bb:function(a,b,c){if(288>=b)for(var d=ue[b-1],e=0;e<b;++e)d[e]=E[c+4*e>>2];else d=E.subarray(c>>2,c+4*b>>2);N.uniform1iv(R[a],d)},Ab:function(a,b,c){N.uniform2f(R[a],b,c)},zb:function(a,b,c){if(144>=b)for(var d=te[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);
N.uniform2fv(R[a],d)},yb:function(a,b,c){N.uniform2i(R[a],b,c)},xb:function(a,b,c){if(144>=b)for(var d=ue[2*b-1],e=0;e<2*b;e+=2)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2];else d=E.subarray(c>>2,c+8*b>>2);N.uniform2iv(R[a],d)},wb:function(a,b,c,d){N.uniform3f(R[a],b,c,d)},vb:function(a,b,c){if(96>=b)for(var d=te[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);N.uniform3fv(R[a],d)},ub:function(a,b,c,d){N.uniform3i(R[a],b,c,d)},tb:function(a,
b,c){if(96>=b)for(var d=ue[3*b-1],e=0;e<3*b;e+=3)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2];else d=E.subarray(c>>2,c+12*b>>2);N.uniform3iv(R[a],d)},sb:function(a,b,c,d,e){N.uniform4f(R[a],b,c,d,e)},rb:function(a,b,c){if(72>=b){var d=te[4*b-1],e=F;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=F.subarray(c>>2,c+16*b>>2);N.uniform4fv(R[a],d)},qb:function(a,b,c,d,e){N.uniform4i(R[a],b,c,d,e)},pb:function(a,b,c){if(72>=b)for(var d=
ue[4*b-1],e=0;e<4*b;e+=4)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2],d[e+3]=E[c+(4*e+12)>>2];else d=E.subarray(c>>2,c+16*b>>2);N.uniform4iv(R[a],d)},ob:function(a,b,c,d){if(72>=b)for(var e=te[4*b-1],f=0;f<4*b;f+=4)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2];else e=F.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(R[a],!!c,e)},nb:function(a,b,c,d){if(32>=b)for(var e=te[9*b-1],f=0;f<9*b;f+=9)e[f]=F[d+4*f>>2],e[f+1]=F[d+(4*f+4)>>2],e[f+2]=F[d+
(4*f+8)>>2],e[f+3]=F[d+(4*f+12)>>2],e[f+4]=F[d+(4*f+16)>>2],e[f+5]=F[d+(4*f+20)>>2],e[f+6]=F[d+(4*f+24)>>2],e[f+7]=F[d+(4*f+28)>>2],e[f+8]=F[d+(4*f+32)>>2];else e=F.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(R[a],!!c,e)},mb:function(a,b,c,d){if(18>=b){var e=te[16*b-1],f=F;d>>=2;for(var h=0;h<16*b;h+=16){var n=d+h;e[h]=f[n];e[h+1]=f[n+1];e[h+2]=f[n+2];e[h+3]=f[n+3];e[h+4]=f[n+4];e[h+5]=f[n+5];e[h+6]=f[n+6];e[h+7]=f[n+7];e[h+8]=f[n+8];e[h+9]=f[n+9];e[h+10]=f[n+10];e[h+11]=f[n+11];e[h+12]=f[n+12];e[h+
13]=f[n+13];e[h+14]=f[n+14];e[h+15]=f[n+15]}}else e=F.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(R[a],!!c,e)},lb:function(a){N.useProgram(Q[a])},kb:function(a){N.validateProgram(Q[a])},jb:function(a,b){N.vertexAttrib1f(a,b)},hb:function(a,b){N.vertexAttrib1f(a,F[b>>2])},gb:function(a,b,c){N.vertexAttrib2f(a,b,c)},fb:function(a,b){N.vertexAttrib2f(a,F[b>>2],F[b+4>>2])},eb:function(a,b,c,d){N.vertexAttrib3f(a,b,c,d)},db:function(a,b){N.vertexAttrib3f(a,F[b>>2],F[b+4>>2],F[b+8>>2])},cb:function(a,b,
c,d,e){N.vertexAttrib4f(a,b,c,d,e)},bb:function(a,b){N.vertexAttrib4f(a,F[b>>2],F[b+4>>2],F[b+8>>2],F[b+12>>2])},Nd:function(a,b){N.vertexAttribDivisor(a,b)},ab:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},$a:function(a,b,c,d){N.viewport(a,b,c,d)},q:function(){return 0},Ra:function(a,b,c){z.copyWithin(a,b,b+c)},i:function(){return Math.random()},qa:function(a,b,c){return ve(a,{ff:E[c>>2],Ye:E[c+4>>2],Of:E[c+8>>2],Lf:b,Se:E[c+12>>2],mf:E[c+16>>2]})},P:function(a,b){a=Y(a);return a?a.requestPointerLock||
a.Ue?Cd&&Id.Fe?je(a):b?(Fd(je,2,[a]),1):-2:-1:-4},g:function(){t("OOM")},u:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;we(a,b);return 0},G:function(a,b,c,d){xe(a,b,c,d,12,"blur");return 0},k:de,o:function(a,b,c){a=Y(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},I:function(a,b,c,d){xe(a,b,c,d,13,"focus");return 0},x:function(a,b,c,d){if(!Md())return-1;a=Y(a);if(!a)return-4;ye(a,b,c,d,"fullscreenchange");ye(a,b,c,d,"webkitfullscreenchange");
return 0},A:function(a,b,c,d){ze(a,b,c,d,2,"keydown");return 0},y:function(a,b,c,d){ze(a,b,c,d,1,"keypress");return 0},z:function(a,b,c,d){ze(a,b,c,d,3,"keyup");return 0},Jd:function(a,b,c){a=G.get(a);zc(a,b,c)},N:function(a,b,c,d){Be(a,b,c,d,5,"mousedown");return 0},L:function(a,b,c,d){Be(a,b,c,d,33,"mouseenter");return 0},K:function(a,b,c,d){Be(a,b,c,d,34,"mouseleave");return 0},O:function(a,b,c,d){Be(a,b,c,d,8,"mousemove");return 0},M:function(a,b,c,d){Be(a,b,c,d,6,"mouseup");return 0},B:function(a,
b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.qe||document.body.Pe||document.body.Ue))return-1;a=Y(a);if(!a)return-4;Ce(a,b,c,d,"pointerlockchange");Ce(a,b,c,d,"mozpointerlockchange");Ce(a,b,c,d,"webkitpointerlockchange");Ce(a,b,c,d,"mspointerlockchange");return 0},w:function(a,b,c,d){De(a,b,c,d);return 0},C:function(a,b,c,d){Ee(a,b,c,d,25,"touchcancel");return 0},E:function(a,b,c,d){Ee(a,b,c,d,23,"touchend");return 0},D:function(a,b,c,d){Ee(a,b,c,d,24,"touchmove");
return 0},F:function(a,b,c,d){Ee(a,b,c,d,22,"touchstart");return 0},v:function(a,b,c){if(!Zd[1])return-4;Fe(a,b,c);return 0},J:function(a,b,c,d){a=Y(a);return"undefined"!==typeof a.onwheel?(Ge(a,b,c,d),0):-1},p:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Wa:function(a){for(var b=pc();pc()-b<a;);},Ua:function(a,b){try{var c=0;Ie().forEach(function(d,e){var f=b+c;e=E[a+4*e>>2]=f;for(f=0;f<d.length;++f)D[e++>>0]=d.charCodeAt(f);
D[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof kc&&d instanceof H||t(d),d.ye}},Va:function(a,b){try{var c=Ie();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0}catch(e){return"undefined"!==typeof kc&&e instanceof H||t(e),e.ye}},X:function(a){try{var b=oc(a);Wb(b);return 0}catch(c){return"undefined"!==typeof kc&&c instanceof H||t(c),c.ye}},Xa:function(a,b,c,d){try{a:{for(var e=oc(a),f=a=0;f<c;f++){var h=E[b+(8*f+4)>>2],n=e,p=E[b+8*f>>2],r=h,
q=void 0,u=D;if(0>r||0>q)throw new H(28);if(null===n.fd)throw new H(8);if(1===(n.flags&2097155))throw new H(8);if(16384===(n.node.mode&61440))throw new H(31);if(!n.oe.read)throw new H(28);var w="undefined"!==typeof q;if(!w)q=n.position;else if(!n.seekable)throw new H(70);var m=n.oe.read(n,u,p,r,q);w||(n.position+=m);var v=m;if(0>v){var x=-1;break a}a+=v;if(v<h)break}x=a}E[d>>2]=x;return 0}catch(C){return"undefined"!==typeof kc&&C instanceof H||t(C),C.ye}},Qa:function(a,b,c,d,e){try{var f=oc(a);a=
4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Xb(f,a,d);$a=[f.position>>>0,(Za=f.position,1<=+Math.abs(Za)?0<Za?(Math.min(+Math.floor(Za/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Za-+(~~Za>>>0))/4294967296)>>>0:0)];E[e>>2]=$a[0];E[e+4>>2]=$a[1];f.af&&0===a&&0===d&&(f.af=null);return 0}catch(h){return"undefined"!==typeof kc&&h instanceof H||t(h),h.ye}},_a:function(a,b,c,d){try{a:{for(var e=oc(a),f=a=0;f<c;f++){var h=Yb(e,D,E[b+8*f>>2],E[b+(8*f+4)>>2],void 0);if(0>h){var n=
-1;break a}a+=h}n=a}E[d>>2]=n;return 0}catch(p){return"undefined"!==typeof kc&&p instanceof H||t(p),p.ye}},c:function(a){var b=Date.now();E[a>>2]=b/1E3|0;E[a+4>>2]=b%1E3*1E3|0;return 0},Ma:function(a){N.activeTexture(a)},W:function(a,b){N.attachShader(Q[a],S[b])},Xb:function(a,b){N.bindBuffer(a,nd[b])},La:function(a,b){N.bindTexture(a,qd[b])},Oa:function(a,b){N.blendFunc(a,b)},H:function(a,b,c,d){N.bufferData(a,c?z.subarray(c,c+b):b,d)},ma:function(a){N.clear(a)},ra:function(a,b,c,d){N.clearColor(a,
b,c,d)},Y:function(a){N.compileShader(S[a])},ib:function(){var a=wd(Q),b=N.createProgram();b.name=a;Q[a]=b;return a},_:function(a){var b=wd(S);S[b]=N.createShader(a);return b},$:function(a,b,c){N.drawArrays(a,b,c)},Pa:function(a){N.enable(a)},S:function(a){N.enableVertexAttribArray(a)},gc:function(a,b){le(a,b,"createBuffer",nd)},Ud:function(a,b){le(a,b,"createFramebuffer",od)},Na:function(a,b){le(a,b,"createTexture",qd)},T:function(a,b){return N.getAttribLocation(Q[a],y(b))},b:function(a,b){b=y(b);
var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=sd[a]&&sd[a].hf[b])&&0<=c&&c<a[0]?a[1]+c:-1},Sa:function(a){N.linkProgram(Q[a]);Bd(a)},Z:function(a,b,c,d){b=xd(b,c,d);N.shaderSource(S[a],b)},Cc:function(a,b,c,d,e,f,h,n,p){N.texImage2D(a,b,c,d,e,f,h,n,p?se(n,h,d,e,p):null)},m:function(a,b,c){N.texParameteri(a,b,c)},s:function(a,b){N.uniform1f(R[a],b)},rc:function(a,b){N.uniform1i(R[a],b)},h:function(a,b,c){N.uniform2f(R[a],b,c)},
n:function(a){N.useProgram(Q[a])},R:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},e:function(){return 0},Ka:function(){return 0},Ta:function(a,b,c,d){return Pe(a,b,c,d)},r:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b}};
(function(){function a(e){g.asm=e.exports;va=g.asm.Vd;Da=e=va.buffer;g.HEAP8=D=new Int8Array(e);g.HEAP16=Ea=new Int16Array(e);g.HEAP32=E=new Int32Array(e);g.HEAPU8=z=new Uint8Array(e);g.HEAPU16=Fa=new Uint16Array(e);g.HEAPU32=Ga=new Uint32Array(e);g.HEAPF32=F=new Float32Array(e);g.HEAPF64=Ha=new Float64Array(e);G=g.asm.le;Ja.unshift(g.asm.Wd);Sa("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+
f);t(f)})}var d={a:Ue};Ra("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ua||"function"!==typeof WebAssembly.instantiateStreaming||Va()||Ta("file://")||"function"!==typeof fetch?c(b):fetch(Ua,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Wd).apply(null,arguments)};g._setFade=function(){return(g._setFade=g.asm.Xd).apply(null,arguments)};g._changePause=function(){return(g._changePause=g.asm.Yd).apply(null,arguments)};g._setSpeed=function(){return(g._setSpeed=g.asm.Zd).apply(null,arguments)};g._reverseA=function(){return(g._reverseA=g.asm._d).apply(null,arguments)};g._nextFrame=function(){return(g._nextFrame=g.asm.$d).apply(null,arguments)};
g._getAvgResistance=function(){return(g._getAvgResistance=g.asm.ae).apply(null,arguments)};g._getAvgSize=function(){return(g._getAvgSize=g.asm.be).apply(null,arguments)};g._getCount=function(){return(g._getCount=g.asm.ce).apply(null,arguments)};g._getTotalDeaths=function(){return(g._getTotalDeaths=g.asm.de).apply(null,arguments)};g._restart=function(){return(g._restart=g.asm.ee).apply(null,arguments)};g._main=function(){return(g._main=g.asm.fe).apply(null,arguments)};
var B=g._malloc=function(){return(B=g._malloc=g.asm.ge).apply(null,arguments)},Te=g.___errno_location=function(){return(Te=g.___errno_location=g.asm.he).apply(null,arguments)},ae=g.stackSave=function(){return(ae=g.stackSave=g.asm.ie).apply(null,arguments)},ce=g.stackRestore=function(){return(ce=g.stackRestore=g.asm.je).apply(null,arguments)},be=g.stackAlloc=function(){return(be=g.stackAlloc=g.asm.ke).apply(null,arguments)};g.addRunDependency=Ra;g.removeRunDependency=Sa;g.FS_createPath=bc;
g.FS_createDataFile=dc;g.FS_createPreloadedFile=hc;g.FS_createLazyFile=fc;g.FS_createDevice=K;g.FS_unlink=Sb;var Ve;function qa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Qa=function We(){Ve||Xe();Ve||(Qa=We)};
function Xe(){function a(){if(!Ve&&(Ve=!0,g.calledRun=!0,!wa)){g.noFSInit||$b||($b=!0,Zb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?K("/dev","stdin",g.stdin):Rb("/dev/tty","/dev/stdin"),g.stdout?K("/dev","stdout",null,g.stdout):Rb("/dev/tty","/dev/stdout"),g.stderr?K("/dev","stderr",null,g.stderr):Rb("/dev/tty1","/dev/stderr"),Ub("/dev/stdin",0),Ub("/dev/stdout",1),Ub("/dev/stderr",1));bb(Ja);Ab=!1;bb(Ka);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ye){var b=g._main;try{var c=
b(0,0);Bc(c,!0)}catch(d){d instanceof qa||"unwind"==d||((b=d)&&"object"===typeof d&&d.stack&&(b=[d,d.stack]),k("exception thrown: "+b),da(1,d))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)b=g.postRun.shift(),Ma.unshift(b);bb(Ma)}}if(!(0<Oa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Na();bb(Ia);0<Oa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);
a()},1)):a())}}g.run=Xe;function Bc(a,b){xa=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);wa=!0}da(a,new qa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ye=!0;g.noInitialRun&&(Ye=!1);Xe();
